### ISSUE TITLE
Barakoa Villages Causing Crashes

### ISSUE THREAD

**Issue by scarecrowskeith** [LunaPixelStudios/Better-Minecraft#10]
Better-Minecraft [FORGE] 1.16.5 v50

When playing together on a server via BisectHosting, players began crashing and receiving JSON errors that prevented them from joining again. After exploring a bit we figured out that proximity (within two chunks) to Barakoa villages from Mowzie's Mobs was causing the issues and could only be fixed by forcibly removing players from the area (done by deleting player data or restoring backups.) The Barakoa themselves are okay when they spawn in savannahs, the issue is with their villages.

We talked to BisectHosting and were directed to ask the modpack devs. I do not currently have any players experiencing this crash after moving them out of the area, we actively avoid the villages, but I would be willing to go force one and create a report - I just need to know what to provide.

Thank you so much!

**Comment by switchnlade** [comment]
Hey there! Next time please use the template for the bug reports. In order to better assist, we need some logs. Can you please recreate the crash and send the logs? Crash logs from the crash along with the latest.log having an attempt to log onto the server after would be great.

**Comment by KhanhPham05** [comment]
Uhm hi there, before we can get any deeper into your issue, please provide us the server and client crash report as well as lastest.log, please?

**Comment by SharkieTV** [comment]
No Response

**Comment by scarecrowskeith** [comment]
Hello,

I am sorry this took me some time - I am chronically ill and could not get this done as quickly as I hoped. I also apologize for missing the reporting template; I was not aware there was one available. I know you all are busy, and I appreciate all of your patience. 

Because this issue happens to individual players - it doesn't crash the whole server - I am attaching my personal logs. I can try to find server logs if those are needed. I will attach one for pre-crash, post-crash, and an attempt to get back on

Pre-crash:
[2022-01-09-1.log.gz](https://github.com/LunaPixelStudios/Better-Minecraft/files/7836682/2022-01-09-1.log.gz)
Post-crash:
[2022-01-09-2.log.gz](https://github.com/LunaPixelStudios/Better-Minecraft/files/7836683/2022-01-09-2.log.gz)
Attempting to get back onto the server:
[2022-01-09-3.log.gz](https://github.com/LunaPixelStudios/Better-Minecraft/files/7836684/2022-01-09-3.log.gz)
.
The error code accompanying this issues is:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid tag id: 17

Again, I apologize for taking so long and my unawareness.

Thank you all for all your help.

**Comment by SharkieTV** [comment]
please update to v51 or see if removing DiscordRichPresence mod helps. Does the server crash or just the players?

**Comment by scarecrowskeith** [comment]
There is one entirely separate instance where the entire server crashes (using christmas trees from csspirit) but this issue affects individual players. Anyone else who is not near the villages continues playing without issues.

I will grab the server logs tonight when I can access the computer. A backup has been restored since these logs so I'll try to find the right one but also recreate it again to get fresh ones.

**Comment by SharkieTV** [comment]
Please update to v51 and see if the issue persists,  its hard to help with old outdated versions anymore due to them being fixed in newer versions of the pack. Also removed Simple Discord RPC Mod too.

**Comment by scarecrowskeith** [comment]
Okay. I will put those together and return with the outcome.

**Comment by scarecrowskeith** [comment]
This worked for me! Thank you.

Unfortunately when I was working with the new version all my map data got deleted/replaced so I will inform everyone to make sure they create a new profile entirely in CurseForge. Is it a correct assumption that copying/replacing map data from v50 to v51 over will move all the data or is XaeroWorldMap and XaeroWaypoints different between enough the versions data can't be transferred?

**Comment by scarecrowskeith** [comment]
*different enough between

Sorry

**Comment by SharkieTV** [comment]
> copying

Yes copying the data should work.
