### ISSUE TITLE
World crash when creating new world pt. 2

### ISSUE THREAD

**Issue by FruitMaestro** [LunaPixelStudios/Better-Minecraft#100]
### Describe the Bug

The answers I received did not resolve the issue: https://github.com/LunaPixelStudios/Better-Minecraft/issues/99 . Is there a chance to reopen a thread?

### Reproduction Steps

1. Open Minecraft
2. Click "Create New World"
3. Crash

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v41.5 and v54.5

### Optifine

No

**Comment by switchnlade** [comment]
You can manually reopen threads, please do that instead of creating a new one, I will answer on there.
