### ISSUE TITLE
Bosses of Mass Destruction Gauntlet destroys gravestone

### ISSUE THREAD

**Issue by Cosmoledo** [LunaPixelStudios/Better-Minecraft#101]
### Describe the Bug

When you die, a gravestone will be generated at your death point, so that you can get back your items safely. Luckily this gravestone is immune to most effects and can not be destroyed easily. Unfortunately I had to find out that the Boss "Nether Gauntlet" does destroy it. So that all your items are gone. Forever.

### Reproduction Steps

1. Create a new world (Cheats on)
2. Cheat Netherite items (Armor, Sword)
3. Enchant everything (Protection, Sharpness)
4. Summon the boss `/summon bosses_of_mass_destruction:gauntlet`
5. Hit his eye, until his health is below 50%. He is now in his second stage and will sometimes attack you with a red beam, which destroys blocks
6. Let him kill you
7. Stay behind your gravestone, so that his beam hits it
8. Gravestone will be destroyed

### Operating System

Any

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

14.5

### Optifine

I used Optifine

**Comment by switchnlade** [comment]
Mod author is aware and is working on a fix, until then we can't do anything about.
