### ISSUE TITLE
Cant load modpack or start minecraft with it

### ISSUE THREAD

**Issue by StinkieBuns** [LunaPixelStudios/Better-Minecraft#102]
### Describe the Bug

cant run the mod pack, error: cannot create java virtual machine 
tried un & reinstalling modpack, java, minecraft 
restarted comp. and still nothing 

all programs are up to date 

### Reproduction Steps

1. start modpack on curseforge 
2.
3.
...

### Screenshots and Videos

![153106777-e303db11-9760-44da-baa9-ca05916275e8](https://user-images.githubusercontent.com/99303003/153107002-514d2c95-dada-4cb7-97bd-92aa65a1ba49.png)
![153106935-1ce9123d-4d2e-4b4e-abad-816fee3262c2](https://user-images.githubusercontent.com/99303003/153107007-0f329438-da41-4099-980a-a48a8546c4f3.png)

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v14.5.zip

### Optifine

No

### Other Mods

n/a

**Comment by SharkieTV** [comment]
This is an Issue with CF launcher see if using GDLauncher works
