### ISSUE TITLE
My quests dont exist

### ISSUE THREAD

**Issue by FrogoDogo** [LunaPixelStudios/Better-Minecraft#104]
### Describe the Bug

i updated to the new better minecraft and all my quests are gone i can open the quest menu but cant see any quests

### Reproduction Steps

1. update a world

### Operating System

widows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55 

### Optifine

No

### Other Mods

no

**Comment by SharkieTV** [comment]
Fixed in v55 HF
