### ISSUE TITLE
Duplicate item type for Fried Egg unusable in recipes

### ISSUE THREAD

**Issue by kylania** [LunaPixelStudios/Better-Minecraft#105]
### Describe the Bug

The new module for food, Farmer's Delight includes a recipe to make a Fried Egg by putting a single default Minecraft Egg in a Campfire, Smoker, or Furnace to create a Fried Egg item.  This item is then used in various recipes from the same mod to make other dishes.

The problem is that Additional Additions mod also adds in the exact same recipe of a single Minecraft Egg making a Fried Egg in the same devices, however the AA mod version is not useable in any Farmer's Delight recipes, so we basically cannot make anything requiring a Fried Egg in Farmer's Delight.

Possibly need to ore dictionary the two Fried Eggs items so they can be used in recipes or remove the Additional Additions Fried Egg since it's unusable and duplicate?

### Reproduction Steps

1. Place a Minecraft Egg on a Campfire.
2. Wait.
3. Receive an Additional Additions Fried Egg item.
4. Not be able to cook Noodle Soup from Farmer's Delight mod since the Fried Egg is the wrong item type.
...

### Screenshots and Videos

![2022-02-09_23 37 53](https://user-images.githubusercontent.com/119372/153344604-10b5c734-bb35-4c2d-979c-a536b7ee879a.png)
![2022-02-09_23 38 13](https://user-images.githubusercontent.com/119372/153344608-3f982465-feb7-410f-b046-2fb1da255086.png)
![2022-02-09_23 38 23](https://user-images.githubusercontent.com/119372/153344611-5ae357e8-b096-4ce4-88c1-bdbaa963fcbd.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

14.5

### Optifine

No

### Other Mods

None other than the mod pack.

**Comment by SharkieTV** [comment]
Thanks will remove the recipe for the AA mod in the next update.
