### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by IgyTxt** [LunaPixelStudios/Better-Minecraft#106]
### Describe the Bug

After i dl the modpack sever i lunch start and i have a error telling me i don't have the right java version, i try to see on the web witch java version i need but i didn't found so can you help me. sry for my english

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![unknown](https://user-images.githubusercontent.com/99499922/153637891-0c7fd9f6-99f6-424d-8d5e-633c5a7b4db1.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

16.5

### Optifine

No

**Comment by switchnlade** [comment]
1.18.1 requires java 17 to run
