### ISSUE TITLE
1.18 - Alex's Mobs crash 

### ISSUE THREAD

**Issue by Thatsmusic99** [LunaPixelStudios/Better-Minecraft#109]
### Describe the Bug

A while ago, Alex's Mobs released an update to fix crashes involving the Kangaroo mob. This version is 1.17.0, the current version of the mod in the modpack is 1.16.0. 

### Reproduction Steps

1. Summon a kangaroo,
2. Tame it with a carrot,
3. Open the pouch and try to put on a chestplate or helmet.

### Crash Report or Log

https://paste.gg/p/anonymous/792a61f7492e4b6ea09bf9e3db0b4d15

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16.5

### Optifine

No

**Comment by SharkieTV** [comment]
Will update pack around Monday or Sunday if I have time, in the meantime dont put anything in the kangaroo until and updates comes out

**Comment by Thatsmusic99** [comment]
> same need help with this aswell

In the meantime, you should be able to update the mod yourself by downloading it [here](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/3642864), replacing it with the old jar in your mods folder. Do note you most likely won't be able to join any BMC servers in the meantime.

> Will update pack around Monday or Sunday if I have time, in the meantime dont put anything in the kangaroo until and updates comes out

Cheers for the quick update, you do you. Wanted to bring it up since some kid got petty at me and my partner when they couldn't use the modpack. Customer support jobs are a thrilling experience. :)

**Comment by SharkieTV** [comment]
> Cheers for the quick update, you do you. Wanted to bring it up since some kid got petty at me and my partner when they couldn't use the modpack. Customer support jobs are a thrilling experience. :)

I mean this isn't my job haha but I try to help out on my free time
