### ISSUE TITLE
Red waypoints on death, won't go away

### ISSUE THREAD

**Issue by KallonPrime** [LunaPixelStudios/Better-Minecraft#11]
### Describe the Bug

Better-Minecraft [FORGE] 1.16.5 v52.5

On death I reclaimed my items from corpse and it disappeared, I disabled the death marker in waypoints menu but the red death beacon still remains and won't go away.

Only alterations I made to the game upon spawn was to enable all resource packs with exception of:
Quark programmer art
Xali's enchanted books
Programmer art
Twilight classic

### Reproduction Steps

1. Die
2. Attempt to remove waypoint
3. 
...

### Screenshots and Videos

![2022-01-07_07 35 41](https://user-images.githubusercontent.com/97278595/148508727-b0dac210-a3b7-49e0-ac96-ab3a234a08cf.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v52.5

### Optifine

No

**Comment by SharkieTV** [comment]
Press "\" then bottom left gear icon (Settings) > Set "Disable Waypoints on death" to false

**Comment by KallonPrime** [comment]
Ah, I don't have a backslash on my keyboard

**Comment by KallonPrime** [comment]
Nvm I found a work around, thanks
