### ISSUE TITLE
Friend cannot join Better Minecraft (FORGE) v55.5??

### ISSUE THREAD

**Issue by itzeppelin** [LunaPixelStudios/Better-Minecraft#111]
### Describe the Bug

I am hosting the server from my computer. I can join it no problem. I am launching Minecraft client side from curseforge Better Minecraft (FORGE) v55.5. Although when I click run.bat(java -Xmx2096M -Xms2096M -jar forge.jar nogui
PAUSE), when loading I get this issue before it continues to successfully open the server for me:
(I have agreed to the eula.txt, true being lowercase.

forge.jar present. Moving on...
minecraft_server."1.16.5".jar present. Moving on...
User did not agree to Mojang's EULA.
eula.txt present. Moving on...
Starting server...
Minecraft version: "1.16.5"
Forge version: "36.2.26"
Java version:
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Java args:
2022-02-12 11:16:14,769 main WARN Advanced terminal features are not available in this environment

They receive this error when trying to join:
![image](https://user-images.githubusercontent.com/74391268/153722088-db18ad5c-49a4-436a-a510-d2fcecbe3871.png)

although I did notice Unrecognized option: --version instead of -version but I downloaded for windows, and when I type java -version in CMD I get this:

C:\Users\itzep>java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

I have no idea if this issue is on my end considering Ive done everything I can think of to fix it.

### Reproduction Steps

1. We both made sure that we were running the correct client-side version, and for me the correct server version.
2. Uninstalling and reinstalling java, removing a version on my end that fixed my issue with connecting myself. They did the same thing, as well as restarting the computers.
3. We both altered the firewalls on PC and router. I made sure to port forward correctly, as I used to do this all the time.
4. We tried the java fix as well but they are getting the same issue.
5. I have Minecraft in my M: drive instead of C: drive. Does java need to be in the same place as Minecraft?
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/74391268/153722480-50e5ba0e-e529-4be0-a522-bb95f3a9eca7.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5

### Optifine

I used Optifine

**Comment by switchnlade** [comment]
We will need some logs, can you upload your latest.log from the server and the latest.log from their client? They are both located in the 'logs' folder of the respective modpack folders, server's log in the server's folder, client's log in the client's folder. Also a note on the --version, it's just a mistyped harmless info thing, you can change it to the correct command or ignore it.

**Comment by itzeppelin** [comment]
It randomly stopped working on my end so I'm about to get it fixed and we will send the logs.
