### ISSUE TITLE
1.18.1 Crashing every few minutes on fabric

### ISSUE THREAD

**Issue by TheRealShame** [LunaPixelStudios/Better-Minecraft#112]
Describe the Bug
Getting regular server crashes

Reproduction Steps
...

Screenshots and Videos
No response

Crash Report or Log

[crash-2022-02-12_19.06.33-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8055124/crash-2022-02-12_19.06.33-server.txt)

Operating System
Windows11

Minecraft Version
1.18.1

Modloader
Fabric

Modpack Version
V15

Optifine
Nope

Other Mods
Allstackable 1.5.2
Chunky 1.2.164
Cloth Config
Proper Modcab Modifier 3.1
Worldedit 7.2.8
wraith silkspawners 1.1.0

**Comment by SharkieTV** [comment]
Remove the Mods you added and see if it still crashes

**Comment by TheRealShame** [comment]
> Remove the Mods you added and see if it still crashes

All ready tried and same story

**Comment by TheRealShame** [comment]
> A chunk is corrupted and that's probably due to adding those mods, I cant recreate the issue and no one else has reported it and due to the log not mentioning what's causing the issue there is not much I can help with other that try a fresh world and not modify the pack and see if you can create this crash again.

Thank you ;) We might start a new world since it was an old world that we copied over. Though it was working fine untill recently. Thank you for trying!
