### ISSUE TITLE
Unable to install fresh server pack.

### ISSUE THREAD

**Issue by hansjiejie** [LunaPixelStudios/Better-Minecraft#113]
### Describe the Bug

title^

### Reproduction Steps

1. Extract sever pack
2. Run start.bat
3. Crash. 

### Crash Report or Log

[start.bat] https://pastebin.com/n8VLEDWS
[latest.log] https://pastebin.com/m6SzQKTT
[debugt.log] https://pastebin.com/cXwqguBq

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v55.5 HF

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
Uninstall Java 17, 1.16.5 needs to use Java 8

**Comment by hansjiejie** [comment]
Yup found this out a min ago while installing serverpack for bmc v54 and saw a README.txt. Maybe re-add a README txt file to re-direct users from common issue like this again?
