### ISSUE TITLE
End city Dimension won't load all chunks

### ISSUE THREAD

**Issue by Lunexle** [LunaPixelStudios/Better-Minecraft#114]
### Describe the Bug

I went into the end, Killed the ender dragon and then went into the end city dimension, I got some stuff there and died a couple of times, after a couple of deaths I went back and almost all the chunks weren't loading, I couldn't get my items or body back. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![unknown](https://user-images.githubusercontent.com/99624821/153785047-a1d2caad-7d44-4bd2-bf42-68767bc36bd4.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v53.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
No Response
