### ISSUE TITLE
Deep dark dimensions not loading or dont exist

### ISSUE THREAD

**Issue by Gitmiggy** [LunaPixelStudios/Better-Minecraft#115]
### Describe the Bug

Going to Y:0 in various  locations and hitting the bedrock. Cant seem to find the deep dark dimension, was it removed? Or bug?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V55

### Optifine

No

**Comment by switchnlade** [comment]
It was changed, requires a light n dark to enter which you will need to craft, consult the JEI menu for the recipe, after you got it, place it on bedrock and use a diamond on it. Then to get out, kill one of the warden variants (open mouth one I believe) and finish the quest in the quest book to receive a dark n light block and a gold ingot, place that down and use the gold ingot to leave.
