### ISSUE TITLE
[1.18.1 bmc v17] Quest Book End section "Kill the void worm" not updated for Upgraded Netherite

### ISSUE THREAD

**Issue by FxKedan** [LunaPixelStudios/Better-Minecraft#117]
### Describe the Bug

Title

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v17

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Will fix in new update
