### ISSUE TITLE
enderman's spawn rate is different from that of vanilla.

### ISSUE THREAD

**Issue by ch0v** [LunaPixelStudios/Better-Minecraft#118]
### Describe the Bug

I built an enderman xp farm in end world and found that enderman's spawn rate is different from that of vanilla. Is this intended?

### Reproduction Steps

1.
2.
3.
...

### Operating System

win 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by SharkieTV** [comment]
Its not been changed and should work. Are you sure you build a proper Farm?

**Comment by TheRealShame** [comment]
I've noticed this too, however, building the spawn platform at the top bigger, maybe about twice the size, fixed that problem for me.
