### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by MrsBailey666** [LunaPixelStudios/Better-Minecraft#119]
### Describe the Bug

it really laggy im playing your better minecraft (fabric) mod and its SUPER laggy but i love the mod is there a way you can fix the lag so i can play the mod?

### Reproduction Steps

1.idk just make it not lag
2.
3.
...

### Screenshots and Videos

i dont have any it was that laggy

### Operating System

java

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

better minecraft

### Optifine

No

### Other Mods

no

**Comment by SharkieTV** [comment]
How much ram have you allocated to the modpack?
What are your pc specs?

**Comment by SharkieTV** [comment]
No Response
