### ISSUE TITLE
Invisible world, except for some mobs, and underwater

### ISSUE THREAD

**Issue by VioletOrc** [LunaPixelStudios/Better-Minecraft#12]
### Describe the Bug

As a friend of mine joins the server I host or plays single player(1.16.5 52v), her world doesn't show up, it's completely invisible, only mobs are visible. When going underwater she can see blocks, but that's it.

We have tried mipmap levels, undoing all the texture packs and so on, qlso reinstalling the pack twice. 

Might some of you know what to do about this?

Thanks in advance

VioletOrc

### Reproduction Steps

1.installing the better mc modpack
2.sees only mobs or entities
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V52

### Optifine

No

**Comment by SharkieTV** [comment]
With this description you should've added a Screenshot at least but see of Disabling Use Chunk Multi-Draw in Video Settings > Advanced and also should be fixed in v53

**Comment by VioletOrc** [comment]
![Screenshot 2022-01-07 145521](https://user-images.githubusercontent.com/97293624/148554190-794a2190-96fd-4344-af71-969550a1b854.png)
![Screenshot 2022-01-07 145505](https://user-images.githubusercontent.com/97293624/148554205-87c39994-31e0-4b05-aded-99e4f2fb25ac.png)
![Screenshot 2022-01-07 145443](https://user-images.githubusercontent.com/97293624/148554215-83e92463-1dc8-4e0f-8fbb-1f0c5e030a25.png)

My friend had to make a couple, but here they are. Chunk multi draw didnt really help, but we will try to update to v53 and see if that solves it

**Comment by VioletOrc** [comment]
V53 indeed fixed the problem, thanks for the comment
