### ISSUE TITLE
i cant move 

### ISSUE THREAD

**Issue by Falloutwolfgod** [LunaPixelStudios/Better-Minecraft#120]
### Describe the Bug

my controls are not working i can go backwards but not foward

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

newest one

### Optifine

No

**Comment by SharkieTV** [comment]
Not sure what do help since since it works for everyone else. You sure your keyboard works?

**Comment by SharkieTV** [comment]
No Response
