### ISSUE TITLE
Copper Tiles Recipe Incorrect

### ISSUE THREAD

**Issue by hopey3182** [LunaPixelStudios/Better-Minecraft#121]
### Describe the Bug

When making copper tiles the recipe should be 1 copper block to 4 copper tiles in the stonecutter, but in this pack it is a 1-1 ratio so one copper block is only converted to 1 copper tile.

### Reproduction Steps

1. Look at stonecutter copper tile recipe in JEI
2. Put copper block in stonecutter
3. Scroll and select copper tile in stonecutter
4. Only get 1 copper tile instead of 4 
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

### Other Mods

Smooth Swapping
Presence Footsteps
Ambient Environment 
Chipped
Light Overlay
Macaw's Trapdoors
Macaw's Paintings 
Macaw's Fences and Walls
Macaw's Light and Lamps
Appleskin
Infinite Music
Promenade

**Comment by SharkieTV** [comment]
The Mod called Consistency+ changes this recipe and I have contacted them about the issue
