### ISSUE TITLE
Modded bows in backslot appear large

### ISSUE THREAD

**Issue by TaterMcTate** [LunaPixelStudios/Better-Minecraft#122]
### Describe the Bug

Modded bows including dragon bow, Torchbow and Crossbow with Spyglass appearing larger and out of position when equipped on backslot. This occurs in inventory player preview and in third person. Items dropped on ground or held in hand appear normally.

Other vanilla or modded tools/weapons and vanilla bows and crossbows are rendering correctly on the backslot

### Reproduction Steps

Updated on CurseForge from v15 to v16 shortly after update was announced.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/99800487/154248467-70412b30-a59a-4a28-9591-1485732a4875.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16

### Optifine

No

**Comment by switchnlade** [comment]
Revert the backslot mod to v1.2.4.
