### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by TheRealShame** [LunaPixelStudios/Better-Minecraft#124]
### Describe the Bug

Our server keeps on crashing after a while. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/qCdHyKKN

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

### Other Mods

Fresh world with no extra mods or datapacks

**Comment by SharkieTV** [comment]
This crash is doesn't give me any info on what could be the issue, could you see if updating to v16 helps if not send a new crash. It look chunk might be corrupted

**Comment by TheRealShame** [comment]
Updated to 16.5 and still same problem. Started having this problem in V14 on a previous world with some extra mods added. After also thinking maybe there are corrupted chunks, we started a fresh world with no extra mods added. Same problem

**Comment by SharkieTV** [comment]
Could you send the new Crash report?

**Comment by TheRealShame** [comment]
Will do as soon as I get home after work. Thank you

**Comment by QiSang1219** [comment]
一去地狱就会崩掉

**Comment by switchnlade** [comment]
> Uploading 错误报告-2022-2-18_22.14.11.zip… 这个是错误报告

English: Update to the latest version, v16.5
Translated: 更新到 v16.5。因为我们只说英语，所以用谷歌翻译翻译。

Note to OP of the this issue thread, this message isn't for you, it's for this person who tagged onto it for some reason.

**Comment by Tomyzzr** [comment]
> 
Came across this thread when looking for fabric mods, the Chinese translation is correct this time XD
