### ISSUE TITLE
Vein Mining Missing in Fabric v16

### ISSUE THREAD

**Issue by mincapweebertarian** [LunaPixelStudios/Better-Minecraft#125]
### Describe the Bug

Looking at the change log, there's no mention of the removal of vein mining, but it seems to have been removed from the mod list. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMC v16

### Optifine

No

**Comment by SharkieTV** [comment]
This has been reported and will be added back in next update
