### ISSUE TITLE
Wrong fabric loader in update v16!(Hosted Server)

### ISSUE THREAD

**Issue by Jauniu** [LunaPixelStudios/Better-Minecraft#126]
### Describe the Bug

The fabric loader 0.13.2 advised to use in the new v16 update could be wrong. Launching on a specific server host with this or any other loader except for fabric loader 0.13.1 does not work. So you must use fabric loader 0.13.1 if you are facing issues while trying to start the server. That is what I found. Launching server with 0.13.1 worked perfectly with no issues so far.

### Reproduction Steps

1. Using start.bat for a hosted server
2.
3.
...

### Screenshots and Videos

-

### Crash Report or Log

-

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16

### Optifine

No

### Other Mods

No.

**Comment by switchnlade** [comment]
Server runs perfectly on fabric 0.13.2. This sounds like a host issue, so get in touch with them if what I'm reading means you are using a third part host.
