### ISSUE TITLE
Best way to Pre Generate Server World?

### ISSUE THREAD

**Issue by slayer1201** [LunaPixelStudios/Better-Minecraft#127]
### Describe the Bug

Newby here How do i go about pre generating my world with better Minecraft fabric server v16?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMF v16 Server

### Optifine

No

**Comment by switchnlade** [comment]
Here's a curseforge link to a fabric pregen mod: https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator. 
Also please note this is for bug/crash reports, not general help questions that can be answered via our discord.
