### ISSUE TITLE
Shift+Click with sword does NOT turn a villager into a guard

### ISSUE THREAD

**Issue by MythBeyondLegend** [LunaPixelStudios/Better-Minecraft#128]
i was informed you can make guards by shift clicking a sword or crossbow on an unemployed or nitwit villager, but it does not work. Idk if theres a confliction or what. Can i have some help? how do i make more guards!?

Thank you

**Comment by SharkieTV** [comment]
Could you next time please use the Template that is provided as I have no idea what modpack and versions and mod loader you are on.

Can I please get the following
Modpack Version
Modloader
Minecraft Version

**Comment by MythBeyondLegend** [comment]
oh yeah sorry about that
i guess it would be

latest release
Forge - 0.12.12
1.18.1

**Comment by switchnlade** [comment]
Do you mean fabric? Also please instead of saying latest, say the exact version number as our fabric packs are now on 0.13.2 as of their latest update.

**Comment by MythBeyondLegend** [comment]
Hey, so i updated to v16.5, same problem. New guards cant be recreated and you cant update their inventory. Unless maybe im doing it wrong? im shift clicking them with a sword, and they just shake their heads

**Comment by LuciustheDragon** [comment]
> Hey, so i updated to v16.5, same problem. New guards cant be recreated and you cant update their inventory. Unless maybe im doing it wrong? im shift clicking them with a sword, and they just shake their heads

What kind of sword are you trying to give them?

**Comment by MythBeyondLegend** [comment]
Ive tried stone and iron sword. Do i need to be hero to turn them into guards aswell?

**Comment by SharkieTV** [comment]
This is probably an issue with the mod itself since its a new fabric port

**Comment by SharkieTV** [comment]
Will be fixed in next version
