### ISSUE TITLE
Random crashes in Nether

### ISSUE THREAD

**Issue by KacperPichola** [LunaPixelStudios/Better-Minecraft#13]
### Describe the Bug

After a short while (sometimes longer, sometimes shorter) of walking around in nether game crashes. 

### Reproduction Steps

1. Play around a new save
2. Go into nether
3. Walk around for a little while
4. Game crashes

### Crash Report or Log

https://gist.github.com/KacperPichola/67ab4daf21c8b68a1945c66e6523c791

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v8.5

### Optifine

No

**Comment by switchnlade** [comment]
This seems that it is a java memory error related to your graphics card drivers. Here's some possible fixes:
- Update graphics drivers to latest version (if this fails, try an earlier one)
- Disable any and all overlays, especially overwolf (if needed, move over to GDLauncher or MultiMc and uninstall/close overwolf)
- Update your java
- If you are using shaders, disable those and see if it's fixed
Sadly that's the most I could find via google on the issue and do not know of any other possible solutions.

**Comment by SharkieTV** [comment]
Yeah also if you have optifine installed remove it and see if you get the crash still after all that as this is a Java Crash. Unless you send the wrong file that was not in Crash Reports or Logs folder

**Comment by SharkieTV** [comment]
No Response
