### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by rdad123** [LunaPixelStudios/Better-Minecraft#130]
### Describe the Bug

Whenever I try to go to the nether the game crashes. It says there is no mod causing it. 

### Reproduction Steps

1.build nether portal
2.enter the nether

### Crash Report or Log

https://bytebin.lucko.me/LjeEKHLM2f

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V16

### Optifine

No

### Other Mods

No

**Comment by switchnlade** [comment]
Fixed in v16.5
