### ISSUE TITLE
Omnis magic resistance bug

### ISSUE THREAD

**Issue by KallonPrime** [LunaPixelStudios/Better-Minecraft#131]
### Describe the Bug

Crashing for unknown reason, can no longer load save without crashing.

The game crashed whilst ticking entity Error: java.lang.IllegalArgumentException: Can't find attribute omnis:magic_resistance Exit Code: -1

### Reproduction Steps

1. I went to the glowstone biome in the Nether
2. Stood on the glowing mushrooms and looked up recipes for dullstone fragments
3. Crash
...

### Crash Report or Log

https://gist.github.com/KallonPrime/37ac152d6b34d7253343237b94b166a8#file-crash-2022-02-18_13-14-00-server-txt

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5

### Optifine

No

**Comment by SharkieTV** [comment]
Fixed in v55.5 HF, your on the non Hot Fix Version
