### ISSUE TITLE
Can't install Optifine

### ISSUE THREAD

**Issue by Honeycomb38** [LunaPixelStudios/Better-Minecraft#132]
### Describe the Bug

I'm trying to install Optifine 1.18.1 to Better Minecraft but when I put it in the mods folder, the game won't load... it gets stuck on the Lunapixel Studios loading screen. Is there a file that is conflicting with Optifine? I am kind of new to mods etc.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft 1.18.1

### Optifine

No

**Comment by switchnlade** [comment]
- OPTIFINE: Remove Rubidium Mod if you want to use Optifine

**Comment by Honeycomb38** [comment]
Thanks switchnlade but I don't actually see that mod with that name in the folder. I am looking in curseforge>minecraft>instances>Better Minecraft [FORGE]-1.18.1>mods

**Comment by Honeycomb38** [comment]
It just sits at the loading screen Lunapixel Studios at the top and the loading bar along the bottom, right before it would go to the main screen to choose single player, multiplayer etc...

**Comment by switchnlade** [comment]
How long have you let it load? It will go into not responding sometimes, best to just leave it to load and not close it.

**Comment by Honeycomb38** [comment]
ok, why is that? We've let it sit almost 10 minutes with no change to the screen. and is there a file that would conflict with Optifine? It loads fine when Optifine is removed which leads me to believe that it has something specifically to do with adding that file, but my son would really love to use Optifine if possible. I just don't really know what I'm doing to try and solve this on my own

**Comment by Honeycomb38** [comment]
yes, it is v17.5

**Comment by switchnlade** [comment]
Well, I just tested on v17.5 with the same optifine version and it loaded up just fine. You can give GDLauncher or MultiMC a try with OF, but if that fails too, then no idea what else would fix it.

**Comment by Honeycomb38** [comment]
ok, thanks for having a look
