### ISSUE TITLE
Decree Bug with the villager board

### ISSUE THREAD

**Issue by MythBeyondLegend** [LunaPixelStudios/Better-Minecraft#133]
used the inventory organization button, and then backed out of the board, when i came back in, all the decrees were gone, and after a bit, all of the other trades were gone. Cant get the decrees back either.
shown in the video below

latest release
Forge - 0.12.12
1.18.1

https://user-images.githubusercontent.com/99859848/154748991-af99f1dc-9f19-44af-acd0-fb2f034b0096.mp4

**Comment by switchnlade** [comment]
Do you mean fabric? Also please instead of saying latest, say the exact version number as our fabric packs are now on 0.13.2 as of their latest update. And yes, this is a copy paste from your other issue. Please do correct this for us.

**Comment by MythBeyondLegend** [comment]
yeah fabric. sorry, im new to this so not fully understanding the stuff, my bad

Operating System
Windows 10

Minecraft Version
1.18.1

Modloader
Fabric

Modpack Version
v15

**Comment by switchnlade** [comment]
Ight, mind testing on v16.5?

**Comment by MythBeyondLegend** [comment]
sure thing

**Comment by SharkieTV** [comment]
So basically if you remove the decrees like it did you need to make new ones or get new ones
