### ISSUE TITLE
Rich Soil Farmland do not let me plant any Seeds. Fabric V 16.5

### ISSUE THREAD

**Issue by Cratios** [LunaPixelStudios/Better-Minecraft#134]
### Describe the Bug

I can not plant any seeds on Rich soil Farmland except tomatoes 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric 

### Optifine

No

**Comment by Cratios** [comment]
V16.5

**Comment by switchnlade** [comment]
Oddly enough this is caused by a conflict with Paradise Lost (the aether mod) and farmer's delight. I'll report it to the authors to get it fixed up.

**Comment by switchnlade** [comment]
At the moment until they respond to my report, I believe rich soil is unusable with paradise lost installed. Good news is that normal farmland (the vanilla way) still works without issues so use that for now.

**Comment by Cratios** [comment]
Thank you very much for the information.
