### ISSUE TITLE
Locked Quests Unable to be Completed

### ISSUE THREAD

**Issue by TheBlueWyvern** [LunaPixelStudios/Better-Minecraft#135]
### Describe the Bug

After many updates, I have seen some additional changes on the ftb quests. The problem is that some of the quests are locked at dimensions I have been before the update. This include some quests that I have finished previously such as "The Beginning" quest from the Overworld. The quests from Everbright and Everdawn doesn't seem to have any issues, since I've been there and completed recently.

This issue however also happens when I'm trying to obtain the Abyss portal through completing every End quest in order. So I repeat the steps by first entering the End, but it didn't say that I've completed the first quest "Enter the End Dimension". I've finished defeating the Ender Dragon again to see if it is mandatory to complete them in order, but none of them seem to fix the issue. 

Not sure if there is a way to resolve this.

*The date of the survival world I've created is on 12th July 2021.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-02-18_20 13 02](https://user-images.githubusercontent.com/88636026/154760835-7c13ccd0-fe08-4e01-8733-f617141c054c.png)
![2022-02-18_21 01 20](https://user-images.githubusercontent.com/88636026/154760906-4e5b1bfa-8706-4e58-818e-01ca87c01b7c.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5

### Optifine

I used Optifine

**Comment by switchnlade** [comment]
Run the command  '/ftbquests editing_mode true' and there should be some options to force complete the quest. After you do that, run ' /ftbquests editing_mode false'. Take care to not mess with anything else while doing this, rather not make a mess of the quests. My guess this is just something that's occurred from the updates like you have said. If it gets confusing at any point, just let me know, I'll load up my game to make a more detailed guide.

**Comment by TheBlueWyvern** [comment]
Okay I'll give a try.

**Comment by TheBlueWyvern** [comment]
So I go to settings, "reset progress" or "complete instantly"?

**Comment by TheBlueWyvern** [comment]
Just reset the quest, and enter the End again. Now it worked fine! Thanks for the help!
