### ISSUE TITLE
End flying bug

### ISSUE THREAD

**Issue by ForsakenHightech** [LunaPixelStudios/Better-Minecraft#136]
### Describe the Bug

my player got buged in End dimension for some reason, and flying down infinitely without dying in void, after this bug i cant kill myself using command, or close game
![Screenshot_1](https://user-images.githubusercontent.com/100040530/154812113-6326a776-3d19-4963-8493-e0a53fbbebc4.png)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v14.zip

### Optifine

No

**Comment by switchnlade** [comment]
I see you put v14 as your version. Currently BMC fabric is on v16.5. Please update to see if your issue is fixed on the later versions. If it isn't, please upload your latest.log from the 'logs' folder.
