### ISSUE TITLE
16.5 (Beta) Update

### ISSUE THREAD

**Issue by PixelBrickcell** [LunaPixelStudios/Better-Minecraft#137]
### Describe the Bug

Alright so, I just downloaded the new 16.5 update from 15.0. I saw that all of my settings were reset, which is typical but, with it I noticed i cannot crouch. I have the crouch keybind enabled on the left shift and it ain't working. Is it a bug or am I missing something?

### Reproduction Steps

It's in the keybind settings and on the "Sneak" bind. I have a keybind on it, but it isn't working.

### Screenshots and Videos

Well ye, it is pretty self explanatory.

### Crash Report or Log

The keybind isn't just working.

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16.5

### Optifine

No

### Other Mods

None.

**Comment by switchnlade** [comment]
Well, my crouch key is working, see if deleting the options.txt file does anything. It's in your main modpack folder, if you installed via curseforge or gdlauncher, just right click the modpack and select open folder to get to it. If that fails, try a fresh install, make sure to make a copy of your saves, xaero (all 3 of em), and local (FTB chunks' map stuff) folders so you keep your worlds and all map data.

**Comment by PixelBrickcell** [comment]
Alright, thank you for your advice! :D
