### ISSUE TITLE
Changing Quark sleep configs makes server unplayable

### ISSUE THREAD

**Issue by codyzhou04** [LunaPixelStudios/Better-Minecraft#138]
### Describe the Bug

I changed the server configs in quark to make it so less people are required to sleep at one time to past the night. Restarted the server to see it take effect and one out of 5 of us could join. For the rest it said internal server error. Restarted it again and this time no one could join. I tried changing the config back, making a new server and copying the world files, and deleting all the config files altogeher (config and serverconfig). 

### Reproduction Steps

1. Changing the quark config in [tweaks.improved_sleeping] "Percent Req" = 1.0 to anything presumably but I did .333
2. Try joining the server

### Crash Report or Log

https://pastebin.com/EqgpHM5t

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

2.2.3-1

### Optifine

No

### Other Mods

discord integration but i highly doubt this impacted anything

**Comment by SharkieTV** [comment]
Dont change the config, it messes with some mods so put it back to 1.0 and hopefully it hasnt corrupted anything.
