### ISSUE TITLE
What mod is this? (potions)

### ISSUE THREAD

**Issue by SpiritWolfed** [LunaPixelStudios/Better-Minecraft#139]
I have a question about what mod adds the ability to stack potions? Personally I think it is too OP so I would like to take it out or change the config just for my personal use. Appreciate it!
 Also IDK how to correctly do the labels SORRY! :(

**Comment by switchnlade** [comment]
What mc version is this for? Also if it's 1.18.1, is it forge or fabric?

**Comment by SpiritWolfed** [comment]
1.16.5 forge

**Comment by switchnlade** [comment]
That'd be Charm. You can set "StackablePotions enabled" to false in the charm-common.toml file in the config folder to disable the feature.

**Comment by SpiritWolfed** [comment]
Thank you so much!!! You saved me like 6+ hours :)) much appreciation
