### ISSUE TITLE
Minecraft mods require some random installations

### ISSUE THREAD

**Issue by 260s** [LunaPixelStudios/Better-Minecraft#14]
### Describe the Bug

better minecraft v52.5 was working fine until i installed v53 i got 11 mods that are asking for some installations and i dont really know how to do it so you can check the images i put here

### Reproduction Steps

1. Open curse forge.
2. Run better minecraft v53.
3. Issue pops up.

### Screenshots and Videos

![Capture](https://user-images.githubusercontent.com/65308615/148603022-b2ee76ec-02af-4140-af50-66227f6bb01d.PNG)
![Capture](https://user-images.githubusercontent.com/65308615/148603114-9ec8dc72-7821-4d08-8aa1-10e8bd0d47ef.PNG)

### Crash Report or Log

https://pastebin.com/kL0tUYCg

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v53

### Optifine

No

### Other Mods

No

**Comment by 260s** [comment]
Nvm i just reinstalled the game and it fixed it

**Comment by switchnlade** [comment]
Glad to hear it's fixed, closing the issue now.
