### ISSUE TITLE
Question / Searching for specific mod (1.18.1)

### ISSUE THREAD

**Issue by Canada-LaVearn** [LunaPixelStudios/Better-Minecraft#140]
Sorry in advance for opening an issue for this

I am trying to find the mod in the FABRIC version of this modpack that causes item drops to have "physics" (tumble through the air and land on the flat side) as id like to use it in other modpacks.

In case this helps:
Minecraft 1.18.1
Fabric Modloader
Modpack Version v16.5

Thank you in advance!

**Comment by switchnlade** [comment]
I believe that is Sentimentality 3. It adds in quite a bit of stuff, including the different physics for dropped items.
