### ISSUE TITLE
Wyrzuca kolege z servera jak spojrzy na mnie

### ISSUE THREAD

**Issue by Gipsik** [LunaPixelStudios/Better-Minecraft#142]
### Describe the Bug

Wyrzuca kolege z servera jak spojrzy na mnie 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/20245456/154841222-447c7333-5d8a-4c1c-8baf-6cdf4563b5ae.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16.5

### Optifine

No

**Comment by SharkieTV** [comment]
YOu aren't even using the modpack to play. Install a launcher and paly the modpack
