### ISSUE TITLE
Cannot launch Better Minecraft Forge

### ISSUE THREAD

**Issue by perscitia** [LunaPixelStudios/Better-Minecraft#143]
### Describe the Bug

When launching Better Minecraft Forge from either ATLauncher or GDLauncher, the loading screen for Minecraft comes up but the app crashes soon after and fails to start.

### Reproduction Steps

1. Launch Better MInecraft Forge 1.18.1 V18 from ATLauncher
2. Mojang loading screen appears and begins to load
3. At about 10% of load the game crashes
3.
...

### Crash Report or Log

https://shared-assets.adobe.com/link/108ab3aa-3b5c-4066-51d5-0118708b8a0e

### Operating System

Mac OS 11.6.2

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by switchnlade** [comment]
I just tested with ATlauncher and v18, loaded up without issue. Thing is I have windows 10 so I can't accurately test with the same OS. As a guess, this is probably related to something on your side in regards to install. Does GDL give the same error?

**Comment by perscitia** [comment]
I am unable to download Better Minecraft in GDL; I have tried several times and restarted my computer but it is forever spinning on the 'download mods' step
<img width="217" alt="Screen Shot 2022-02-20 at 4 52 21 PM" src="https://user-images.githubusercontent.com/100091100/154868108-fad581d9-f329-4c8d-9a02-55f4c3929fa9.png">
.

**Comment by switchnlade** [comment]
Ah yeah, that one, supposedly it's fixed via setting the release channel to beta in the settings, but you can test via MultiMC. Do note this will require having your own java installed, this guide from them shows how to set it up: https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java. You can then download the modpack by selecting add instance at the top left and choosing it from the curseforge tab.

**Comment by perscitia** [comment]
Okay don't know if this needs to be a separate issue but I am able to launch the game through MultiMC after following all of those directions, however when I try to join my friend's server I get a 'java quit unexpectedly' window as well as a 'process crashed with error 6' message in MultiMC and the game crashes.
<img width="997" alt="Screen Shot 2022-02-20 at 5 26 57 PM" src="https://user-images.githubusercontent.com/100091100/154869093-e8b8e74f-ee05-494d-857b-27dfddd9c9cb.png">
<img width="693" alt="Screen Shot 2022-02-20 at 5 27 07 PM" src="https://user-images.githubusercontent.com/100091100/154869095-f26fa886-56d5-46a7-bf0a-7dd9a2c78587.png">

**Comment by switchnlade** [comment]
Can you upload the full log please?

**Comment by perscitia** [comment]
I was able to download Better Minecraft FORGE 1 18 1 on GD launcher by setting the release channel to beta but when I try to launch it I'm getting Uncaught Fatal Exception Code 1 
<img width="529" alt="Screen Shot 2022-02-20 at 5 30 42 PM" src="https://user-images.githubusercontent.com/100091100/154869201-0ffeb4c9-2f29-4b05-87dd-3314948614d2.png">

**Comment by perscitia** [comment]
Here's the MultiMC log https://paste.ee/p/be1D3

**Comment by switchnlade** [comment]
Please remove the rubidium mod from the mods folder. On multimc you can access this by clicking on the "minecraft folder" button on the right while having bmc forge selected, then navigate to the mods folder and find the file named rubidium. Screenshot below for what to click to access the folder.
![image](https://user-images.githubusercontent.com/96159041/154869346-a84ad5f3-ef2c-4c4d-a384-796c968e6f73.png)

**Comment by perscitia** [comment]
I removed rubidium but I am having the same result; Java quit unexpectedly and process crashed with exitcode 6

**Comment by perscitia** [comment]
Wait apologies I didn't realize that dragging rubidium out of that folder copies it instead of removing it. Trying again now.

**Comment by perscitia** [comment]
Removing rubidium worked but I got an out of memory error. Changing my memory allotment to 6000 MiB has solved the problem! I can't thank you enough for your help.

**Comment by switchnlade** [comment]
No problem, glad we were able to get it working.
