### ISSUE TITLE
No Leather?

### ISSUE THREAD

**Issue by NeonBonsai** [LunaPixelStudios/Better-Minecraft#144]
I can’t seem to find a way to get leather anywhere other than in chest loot. Cows drop hide and there seems to be no way to convert it or zombie flesh to leather for recipes that need it. Is this by design? I’ve seen others in lets plays converting zombie flesh but my game doesn’t have a recipe for that. 
The only recipe for leather is using lizard hide.

**Comment by SharkieTV** [comment]
Please fill out with the Template that is provided
