### ISSUE TITLE
Can't make a villager get a job

### ISSUE THREAD

**Issue by criz004** [LunaPixelStudios/Better-Minecraft#145]
### Describe the Bug

Hi! 
My english is not so good, so i apologize for any misspell

I was ready to make a villager farm to get some librarians and get enchanted books easier. Everything was good, the reproduction was succesfull and i took the villagers and enter them in a trading hall
I got every single villager on every single room, and then, i placed the lectern and then... nothing happened
Also... this does not happen with all villagers, there is a little amount of villagers that respond correctly with the lectern, but after a few attempts of breaking and placing again, they stop working too
If this is a mechanic for any mod in the modpack, i would be very gratefull if you make me know what i need to do to fix this

### Reproduction Steps

1. Get any villager (in my case was an unemployed and never got a job) on a minecart
2. Push the villager on a little space
3. Break the rails
4. Place the lectern to get a librarian
5. Nothing happens!

### Operating System

Windows 10 Home Single Language

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5 HF

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
This does work, you are probably doing it at the wrong time or his trades are locked

**Comment by criz004** [comment]
> This does work, you are probably doing it at the wrong time or his trades are locked

I was waiting all the day, and tried with other villagers, and still not work :(
