### ISSUE TITLE
Void totem is not working.

### ISSUE THREAD

**Issue by Mowdan** [LunaPixelStudios/Better-Minecraft#146]
### Describe the Bug

The void totem does not seem to be working. I tested it a few times to make sure it wasn't a fluke and I tested it with no other mods and the mod by itself is working, it just doesn't work in the modpack.

### Reproduction Steps

1. Have a void totem in the main hand, off hand, and trinket slot or any combination.
2. Jump into the void from the spawn platform in the end or anywhere else.
3. "fell out of the world" death message instead of totem crack and teleport.

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft [FABRIC] v16.5.zip

### Optifine

No

**Comment by SharkieTV** [comment]
Ill look into it

**Comment by SharkieTV** [comment]
The mod dev is working on a fix, will add it back to the Modpack when its ready
