### ISSUE TITLE
Cannot launch game through minecraft launcher

### ISSUE THREAD

**Issue by longtimeperson** [LunaPixelStudios/Better-Minecraft#147]
### Describe the Bug

I launch the minecraft launcher through curseforge, then try and run the game, the game starts to load some mods and it crashes without giving me a report. The most it says is "Error code: 1"
![Screenshot 2022-02-21 033116](https://user-images.githubusercontent.com/100132324/154947130-cf0720dc-fcfe-4113-a324-462bba20ec06.png)

### Reproduction Steps

1. Launch minecraft launcher via curseforge
2. Run the game through minecraft launcher

### Screenshots and Videos

![Screenshot 2022-02-21 033306](https://user-images.githubusercontent.com/100132324/154947396-27fd7ef0-fc8a-4a7a-8c7a-d112dcfa7729.png)
![Screenshot 2022-02-21 033116](https://user-images.githubusercontent.com/100132324/154947422-cf8ae584-07e5-453a-9a17-0b0cfe808060.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5 HF

### Optifine

No

**Comment by SharkieTV** [comment]
Need a log and you haven't allocated enough ram to the modpack. 3GB is not enough you need to atleast allocate 6-8gb and if you are using optifine you will have long load times

**Comment by longtimeperson** [comment]
Where do I find the log requested?

**Comment by SharkieTV** [comment]
in the modpack folder

**Comment by SharkieTV** [comment]
No Response
