### ISSUE TITLE
world wont load

### ISSUE THREAD

**Issue by Marshdpotatoes** [LunaPixelStudios/Better-Minecraft#148]
### Describe the Bug

so, i've been playing better minecraft for a few days now, and i have to say, it's really fun, i like it a lot. but, today i've ran into my first issue. 

so, i've been trying to play all day, and for some odd reason, the world will not load. i've tried reinstalling the mod pack, backing up my world, tweaking with the data, waiting for it to load, and irregardless of what i do, i can't get it to load.

is this  a modpack issue or just my world being corrupted? any help would be amazing. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5hf

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Need the latest.log to see what the issue is

**Comment by Marshdpotatoes** [comment]
how do i find the log?

**Comment by SharkieTV** [comment]
in the modpack folder

**Comment by SharkieTV** [comment]
No Response
