### ISSUE TITLE
Better End outdated with broken functions.

### ISSUE THREAD

**Issue by Rhinolegs** [LunaPixelStudios/Better-Minecraft#15]
### Describe the Bug

Better end is running on an old version with bugs. Currently Ender Dust is uncraftable. This blocks access to Terminite bars. Additionally the craft for Terminite armor requires Terminite Forged Plates which are also uncrafted. This further blocks access to Crystalite gear / equipment. 

### Reproduction Steps

1.Craft anvil
2.Craft netherite hammer
3.Place netherite hammer in anvil in 1st slot and ender pearl in 2nd slot.
4.Ender dust will not be crafted.

### Screenshots and Videos

![268cd36d05128101e61adf67a3219095](https://user-images.githubusercontent.com/97319350/148619661-9d8d8d11-77e4-4187-be7f-ca8560225f42.png)
![b05e79320d24e3497e219da8c8768b4f](https://user-images.githubusercontent.com/97319350/148619694-ddb1804d-7e1b-477f-8557-3889ee373b1b.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v8 and v8.5

### Optifine

No

### Other Mods

None

**Comment by Rhinolegs** [comment]
I believe all these are working in newer versions of better end but the mod pack uses a better end version that is several months outdated.

**Comment by SharkieTV** [comment]
The latest BetteEnd for 1.18.1 is in Alpha and they have not implemented all their features yet. I you have issues report that to the Mod Devs.
