### ISSUE TITLE
Uncraftable Barrel Variations 

### ISSUE THREAD

**Issue by HeroicCentipede** [LunaPixelStudios/Better-Minecraft#150]
### Describe the Bug

The mod Blockus doesn't seem to be working properly. The barrels that are supposed to be made of the different types of wood always turn into spruce barrels no matter what wood you use. The different barrels for other mods such as  Better Nether, Better End, and Edenring all have crafting recipes while the blockus barrels do not. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16.5

### Optifine

No

**Comment by SharkieTV** [comment]
Fixed in latest update
