### ISSUE TITLE
My entire game is frozen except my character

### ISSUE THREAD

**Issue by Karama1** [LunaPixelStudios/Better-Minecraft#151]
### Describe the Bug

So I've been playing the mod for fun (Forged edition btw), and yesterday, when I got to the end, the game was working until my friend (who joined via LAN) died. Suddenly, the enemies are all frozen, adding cheats won't allow you to use any commands, I've tried /reload and that too didn't work. I can move around, mine (nothing drops) and place blocks (does use the block up from my inventory). Placing water/lava stays in the single block it's placed in. I'm running minecraft through the CursedForge for 1.16.5. In addition to this, any already placed effects (when they ware out) are at 00:00

Also, I must mention, anytime I save and exit the world, it's stuck on "Saving world" but the Tips still change.

### Reproduction Steps

1. Friend join via LAN
2. Go to end
3. Friend dies
4. Game suddenly doesn't work (Least for me)
...

### Screenshots and Videos

![1](https://user-images.githubusercontent.com/96311734/155229401-d69a9477-2bad-4964-893a-13e6eabae9bb.png)
![image](https://user-images.githubusercontent.com/96311734/155229444-9659c672-a52a-4af8-a74d-23b4f9fa8691.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55.5 HF

### Optifine

No

### Other Mods

_No response
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8120814/latest.log)
_

**Comment by SharkieTV** [comment]
LAN is untested and should not be used, there are too many variables it causes. Please use a the serverpack to run a local server
