### ISSUE TITLE
Blue Skies Duplication Bug

### ISSUE THREAD

**Issue by 0TheCho0** [LunaPixelStudios/Better-Minecraft#152]
### Describe the Bug

If you are in some of the structures in which you can´t place blocks and you put a backpack it gives you back but when you take it from the inventory you take a copy of your backpack.

### Reproduction Steps

1.Go to a boss structure in wi¿hich you cannot place blocks
2.Place the backpack
3.Move it in the inventory
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v51

### Optifine

No

**Comment by SharkieTV** [comment]
That has been fixed in future updates
