### ISSUE TITLE
Game doesn't load in to the world.

### ISSUE THREAD

**Issue by Hentreeb** [LunaPixelStudios/Better-Minecraft#153]
### Describe the Bug

I downloaded and started to play 1.18.1 better Minecraft from CurseForge. (I play on Mac) It loaded in-game and I started a new world, I had 4GB RAM allocated. On 100% the world crashed. (I have put an image with the error code) Then I tried again with 6,8,9k and the same thing happened. I went to CurseForge's discord and they couldn't help me and said to contact you. How can I fix it?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2022-02-23 at 15 29 57](https://user-images.githubusercontent.com/96792951/155364868-24263158-890c-4370-a697-de5c03e39dc4.png)
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8126132/latest.log)

### Crash Report or Log

The report is under screenshots.

### Operating System

Apple Mac Mini 2012 Pro

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Forge v18.zip

### Optifine

No

**Comment by SharkieTV** [comment]
The log doesnt suggest that anything is wrong. Can you do a fresh install and make sure to allocate 8gb and remove the mod called Simple RPC and see if that helps?
Also how much ram does your laptop have?

**Comment by Hentreeb** [comment]
Can anyone please help?

**Comment by SharkieTV** [comment]
I replied so whats your problem?

**Comment by Hentreeb** [comment]
Hello!

Sorry about that, I didn't see the reply. I fixed the problem myself right now, just had to download the older 1.18 version. Thank you for your help tho!
________________________________
