### ISSUE TITLE
The Graveyard structures spawning on the "floor" of the Aether dimension from "Paradise Lost - the Aether Reborn"

### ISSUE THREAD

**Issue by mbrozzo** [LunaPixelStudios/Better-Minecraft#154]
### Describe the Bug

Please see the issue I opened on the Graveyard's page with the full details: https://github.com/finallion/The_Graveyard_-FABRIC-/issues/29

### Reproduction Steps

Enter the Aether dimension and use /locate graveyard:haunted_house (or any other graveyard structure)

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/22538059/155439307-6b44f81e-9150-4305-bc50-48fa2335c528.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

16.5

### Optifine

No

**Comment by SharkieTV** [comment]
Thanks for the report, there is currently nothing I can expect wait for an updte from the graveyard dev
