### ISSUE TITLE
Crashing server via Bee's action...?

### ISSUE THREAD

**Issue by LocketGoma** [LunaPixelStudios/Better-Minecraft#155]
### Describe the Bug

[crash-2022-02-25_00.31.41-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8133726/crash-2022-02-25_00.31.41-server.txt)
[crash-2022-02-25_00.03.04-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8133728/crash-2022-02-25_00.03.04-server.txt)
[crash-2022-02-25_00.01.04-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8133729/crash-2022-02-25_00.01.04-server.txt)

I update server 17.5 to 18

after update, so quite when server begin... but "the day is light and shine...", Crashed.

I saw logs, but i just think... the bee's action is error point.

And, i roll-back server, and re-install server. but error still occur.

I moved error point, and i found something. some mod's "Common flax plant" and Bee are interaction each other, crashing.

Can you check that error? thanks..

### Reproduction Steps

1. some many bees
2.planting common flax
3.waiting...
...

### Operating System

mac OS Monterey

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

### Other Mods

DiscordIntegration
Dynmap-forge

**Comment by LocketGoma** [comment]
![image](https://user-images.githubusercontent.com/16269328/155557769-ba3d0d1c-6fc4-42cc-84eb-4c29aa05a90c.png)
add screenshot. sorry i using Korean lang pack

**Comment by SharkieTV** [comment]
See if removing the mod called Radium Reforged helps

**Comment by LocketGoma** [comment]
[crash-2022-02-25_21.02.45-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8140958/crash-2022-02-25_21.02.45-server.txt)
Still crashing...

**Comment by SharkieTV** [comment]
Remove supplementaries and selenelib mods then

**Comment by LocketGoma** [comment]
> Remove supplementaries and selenelib mods then

I'm not trying your suggestion, but maybe (still this time from my last reply time) crash error not appear when I just removed flax plant...................... 
anyway, i trying your suggestion. thanks.

**Comment by LocketGoma** [comment]
I tested some interaction in "Supplementaries" Mod, and I checking somethings...
1. Between Wild flax and Bee's interaction is ok (not crash)
2. Bomb, Bluebomb interaction is also ok
3. rope arrow interaction is also ok

just "Common flax and bee's interaction" is crashing my server.

**Comment by SharkieTV** [comment]
Thanks for the report
