### ISSUE TITLE
(Suggestion) Alternative to rubidium that allows shaders

### ISSUE THREAD

**Issue by JasonDerulo1259** [LunaPixelStudios/Better-Minecraft#156]
[The Oculus Mod](https://www.curseforge.com/minecraft/mc-mods/oculus) Is a newly released, forge-compatible port of [The Iris Mod](https://www.curseforge.com/minecraft/mc-mods/irisshaders)

It is quite new, and a bit buggy, but for the most part it works just like [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium), but with the ability to load shaders.

(FYI its also developed by the same person)

**Comment by SharkieTV** [comment]
Suggestions are done in he Discord and yes it will be added
