### ISSUE TITLE
Very unbalanced loot from a Mining System

### ISSUE THREAD

**Issue by DuckyBlender** [LunaPixelStudios/Better-Minecraft#157]
### Describe the Bug

The loot from a mining system is very unbalanced, usually there are 10 diamonds and much more (screenshot)
Keep in mind that I was looting with a friend and this is only half.

### Reproduction Steps

1. Load a world
2. Locate a Mining System
3. Loot the barrels

### Screenshots and Videos

![javaw_B1A9QP8RHC](https://user-images.githubusercontent.com/42645784/155716349-b4682480-136b-41e4-b83f-b5abd502abbf.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
Oh wow, that seems wrong, the Dungeon is very rare but that loot seems a bit messed up, can you give me the seed and location?

**Comment by DuckyBlender** [comment]
> Oh wow, that seems wrong, the Dungeon is very rare but that loot seems a bit messed up, can you give me the seed and location?

I checked yesterday, it happens in every single Mining System (from dungeons arise mod) and the loot is in the barrels.
There are usually like 10 diamonds in a barrel and prot 2/4 diamond armor
Happens on v17, gonna confirm in v18 in just a minute.

**Comment by SharkieTV** [comment]
Reported this to the Dev, he said he will balance the loot more as its not suppose to be like that. Thanks
