### ISSUE TITLE
Autowalk bug

### ISSUE THREAD

**Issue by Lephox781** [LunaPixelStudios/Better-Minecraft#158]
### Describe the Bug

Occasionally walks automatically without pressing any key binds. Prevent any measure of trying to stop it. Stop auto walking on its own. Please fix thank you.

### Reproduction Steps

1. WASD
2. Bugs occurred - automatically walks on its own for more than 5 seconds
3.
...

### Operating System

window 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by SharkieTV** [comment]
If you press Caps you auto walk, its a keybind
