### ISSUE TITLE
cant load the modpack

### ISSUE THREAD

**Issue by SamuelHaydenGaming** [LunaPixelStudios/Better-Minecraft#159]
### Describe the Bug

whenever i open minecraft to play better minecraft, it says 60 mods are having issues loading and require java language provider fml 39, you have 36.2, i tried everything i possibly could, from reinstalling forge, to reinstalling the modpack, nothing worked, i just hope someone has a solution

### Reproduction Steps

1. open minecraft with forge (with the modpack active)
2. get to the mojang loading screen
3. get this error
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v55 or v56 i dont exactly remember

### Optifine

I used Optifine

### Other Mods

valhelsia structures, spiders 2.0, and there were like 5 more but i dont remember any other ones, sorry

**Comment by SharkieTV** [comment]
Are you using an official launcher like Curseforge?
Can you try a fresh install with none of your mods added

**Comment by SharkieTV** [comment]
No Response
