### ISSUE TITLE
Tons of recipe conflicts with Sentimentality 3

### ISSUE THREAD

**Issue by Lucipo** [LunaPixelStudios/Better-Minecraft#16]
### Describe the Bug

Tons of recipes that either conflict or a recipe is better than other recipe

EX: 6 wood planks for a trapdoor gives the output of either 2 trapdoors, or 12. 
Tridents can be crafted with 3 iron and 2 sticks versus the balanced recipe already in the pack.
Wooden stairs can be crafted into 4 stairs or 8 stairs.

I would like to recommend that recipes for all stairs and trapdoors from all mods are changed to output 8 and 12 respectively, as well as the old recipes being disabled/removed, for consistency's sake. Building should also not be more expensive for the sake of being expensive in regard to the increased output of stairs and trapdoors and others.

A closer look should be had with sentimentality 3, lots of conflicts I have not discovered yet I would assume.

### Reproduction Steps

1. Attempt to craft wooden stairs/trapdoors
2. Shows two possible recipes, one with 8/12 output and one with the default output of 4/2

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/36358294/148629519-a97fd0b3-d0d5-40d7-a7fa-7eba174c393f.png)
![image](https://user-images.githubusercontent.com/36358294/148629522-827c9370-4ba3-4303-bd91-f9dd51ca93c1.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

8.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
It seems that they added it straight as a vanilla recipe so removing it removes both recipes. I have ask the dev team to create a config to disable those recipes as I already tried everything with KubeJS and it doesn't seem to want to get rid of the recipe. Also if you didn't already know you can use the stone cutter as a woodcutter.

**Comment by SharkieTV** [comment]
Talked to the Dev they will add a config to disable these and will to do so in a future update
