### ISSUE TITLE
Infinitely Spawning Pillagers from a Pillager Outpost

### ISSUE THREAD

**Issue by DuckyBlender** [LunaPixelStudios/Better-Minecraft#160]
### Describe the Bug

I spawned near a pillager outpost and wanted to make some tools. When I came back to the outpost there were like 100 of them and it was borderline impossible to beat them. They just kept spawning

### Reproduction Steps

1. Locate a Pillager Outpost
2. Go in survival
3. Wait
...

### Screenshots and Videos

![2022-02-24_18 39 36](https://user-images.githubusercontent.com/42645784/155849752-e269236c-4eb6-4dbc-9720-56dd371100c4.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by DuckyBlender** [comment]
Yes, I know that they should be spawning infinitly, my problem is that there is no mob cap. There can be hundreds of them and keep spawning.

**Comment by SharkieTV** [comment]
Could you give the seed and location?
