### ISSUE TITLE
Pets from Alexs mobs keep teleporting to me

### ISSUE THREAD

**Issue by bestserv** [LunaPixelStudios/Better-Minecraft#162]
### Describe the Bug

all my pets from alexs mobs keep teleporting to me when I get too far away even when they are sitting, I have tried everything from leading them while sitting, leading them while wandering, and just sitting them the only exception to this it the Laviathan it only seems to apply to alexs mob's pets. quark and blue skies pets are also exceptions to this teleporting bug. 

### Reproduction Steps

1.tame pets from alexs mobs ex. Bald Eagle, Crow, Kangaroo, Mantis Shrimp, And Tarantula Hawks.
2.sit them all down and move far away (like 150 blocks should be good maybe)
3.they all teleport to you
this bug also seems to be on and off at times for some reason

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v17.5

### Optifine

No

### Other Mods

no

**Comment by SharkieTV** [comment]
So the Mod called Companion is doing this, remove it if you dont want that to happen, ill let the Mod Dev know

**Comment by bestserv** [comment]
thank you
