### ISSUE TITLE
Enchantments removed 

### ISSUE THREAD

**Issue by popwhizz** [LunaPixelStudios/Better-Minecraft#163]
### Describe the Bug

As of the most recent update iv lost the vein miner enchantment on all my tools, the mod is still in the mod file and my game has not had any crashes its just disappeared 

### Reproduction Steps

1. update to v56 with a diamond pick with vein miner
2. play game
3. enchantment disappears 
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V56

### Optifine

No

**Comment by SharkieTV** [comment]
1.18 doesn't have v56 so I assume its 1.16.5 and not much I can do other than did you backup your world? See if copying over the playerdata files helps. This update was not meant to remove anything but with all the Mods updates a mod could've affected it without knowing.
