### ISSUE TITLE
BETTER MINECRAFT. HELP! 

### ISSUE THREAD

**Issue by rollandcarasi** [LunaPixelStudios/Better-Minecraft#164]
### Describe the Bug

Hi fellas, i tried to open open better minecraft yesterday, i even did the forge server with Better Minecraft, everything ran up quickly and nicely, till i opened up minecraft and tried to join my server, instead of exploring i got : ,,***** tried to join in, invalid session'' and on my screen with minecraft i got something with ,,Invalid indentify, invalid name'' something like that, what i m supposed to do?

### Reproduction Steps

1.I installed Better Minecraft Server Pack from https://www.curseforge.com/minecraft/modpacks
2.i watched this tutorial on how to run your server https://youtu.be/uS2U5ZKspDA
3. And then, the bug came up, i launched TLauncher, installed forge 1.16.5 because that s the BM version i wanted too, i did exactly as the tutorial said.
4. When i created the server as that Mr. says in the video, i joined and on my screen appeared ,,Invalid name'' or something like that, even in the better minecraft console it said ,, This player tried to join in, invalid session''

### Screenshots and Videos

I dont have screenshots but i think i can remake the whole problem, or redo my mistake i guess

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

**Comment by Voixle** [comment]
so your trying to Run it in a Server? in tlauncher have you ever tried setting online-mode=false?

**Comment by rollandcarasi** [comment]
i m trying to run the server from better minecraft server pack, and when i launch tlauncher, and try to join the server it says the username is invalid

**Comment by DuckyBlender** [comment]
you need to enable online-mode to false in server.properties if you want to join using TLauncher
also, please actually buy the game

**Comment by rollandcarasi** [comment]
i do have bought the game
i tried even using the minecraft from xbox game pass
and one more thing, i dont have server.properties

**Comment by rollandcarasi** [comment]
and now i get ,,Unexpected data from client''

**Comment by SharkieTV** [comment]
TLauncher is not allowed nor do I helped with Cracked Lanchers

**Comment by SharkieTV** [comment]
@rollandcarasi @Voixle @DuckyBlender  Deleted all your replies because as you know its Illegal to use Cracked Minecraft and next time dont help people with a Cracked Launcher or Cracked MC.

**Comment by DuckyBlender** [comment]
> @rollandcarasi @Voixle @DuckyBlender  Deleted all your replies because as you know its Illegal to use Cracked Minecraft and next time dont help people with a Cracked Launcher or Cracked MC.

Sure, sorry
