### ISSUE TITLE
start server on linux

### ISSUE THREAD

**Issue by Tizfaver** [LunaPixelStudios/Better-Minecraft#166]
Hi, how do i start in the terminal the server? from Ubuntu? I tryed starting all files from the directory: libraries\net\minecraftforge\forge\1.18.1-39.0.79\
But only problems... thanks! I think this will be usefull for all people trying to host in a Linux server!

**Comment by Tizfaver** [comment]
Oh, i solved, in the terminal just start "sudo bash start.sh", hope somebody find this helpfull!

**Comment by kotori** [comment]
Generally, its a bad idea to run system services like this as root (i.e sudo).
You probably want to run the start.sh script as a non-privileged user to minimize the risk of your Entire server getting owned.

Something like the following would be wiser:

# Create a new non-root user to run minecraft as:
useradd minecraft
# Give the directory you installed BetterMC to appropriate privileges, this would be fixed your execution issue above btw.
chown -R minecraft:minecraft /opt/gameserver/minecraft/bettermc
# Jump into the BetterMC path:
cd  /opt/gameserver/minecraft/bettermc
# Run the start script as the minecraft user.
su - minecraft -c "start.sh"
