### ISSUE TITLE
Custom Textures for Enchanted Books, weapons, crops, etc. won't load

### ISSUE THREAD

**Issue by ShaynesRibShack** [LunaPixelStudios/Better-Minecraft#168]
### Describe the Bug

Hi, I was loading up Better Minecraft one day when the game crashed before the modpack loaded. This was out of the ordinary. When I finally loaded everything, and joined the server my cousin and I started, the textures for the crops, the enchanted books, the netherite tools, and other things were vanilla rather than what the modpack intended. I enjoyed the change and the depth that it added to the game, but I can't figure out how to change it back. When I went back to the crash report it said that Terra Incognita failed to load and extended mushrooms failed to load. Both had problems during the common set up phase

### Reproduction Steps

I can't repeat the bug

### Screenshots and Videos

![2022-02-28_22 25 45](https://user-images.githubusercontent.com/100658170/156099264-ceffb93f-cd35-41e0-81f2-d90036ec7586.png)
![2022-02-28_22 24 33](https://user-images.githubusercontent.com/100658170/156099278-cd414d9d-fd85-4fa0-85f6-36df034f7a79.png)
![2022-02-28_22 24 52](https://user-images.githubusercontent.com/100658170/156099281-8d0b374e-17c5-48ba-88d2-94866d774baa.png)
![2022-02-28_22 25 04](https://user-images.githubusercontent.com/100658170/156099286-9eb0b929-896c-4680-8e09-11dd91e89d31.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v54.4

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
You just have the resourcepacks unloaded, must've just been a loading issue

**Comment by ShaynesRibShack** [comment]
Ok thank you
