### ISSUE TITLE
Server Overloading, all players lagging out

### ISSUE THREAD

**Issue by Montruh** [LunaPixelStudios/Better-Minecraft#17]
### Describe the Bug

Hi, my friends and I have recently started a Better Minecraft Server on CurseForge, using Bisect Hosting. We settled on a premium package containing 6GB of ram, the recommended amount. The server starts up fine, works well for about 2 minutes, then we all seem to "lag out" for about 30 seconds, then back to normal. We pretty much have to just continue this chain the rest of our play-through. I don't believe it's a client side issue, since its coming up in server crash logs, and we all have decent rigs, as well as networks. Don't know why this is, hopefully someone can give me some insight! 

P.S. already tried turning server tick rate above 60k as well as changing it to "-1"

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/WdzyQPb6

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v8.5

### Optifine

No

**Comment by SharkieTV** [comment]
Hi, how long have you had this world for? It seems like some sort of block is causing it and it not letting me know what block. 
If you haven't played for too long and since you have premium can you make a new instance and make a new world on v9 and see if this issue persists?

**Comment by Montruh** [comment]
Thank you for the reply! Sorry if this is a dumb question, but i'm not the most familiar when it comes to modded minecraft and curse forge altogether, but where can I find the v9 for the modpack? Thanks!

**Comment by SharkieTV** [comment]
Ah ok seems like they have not updated it yet. Could you try a new world on v8.5? and see if that still causes the issue?
If it does, v9 should be out anytime soon and possibly see if that fixed it. Your currently the only one reporting this issue so im tryna see if maybe it was world specific. Because so far out of the 33K downloads for v8.5 your the only one reporting this.

**Comment by Montruh** [comment]
BisectHosting seemed to have updated within the time frame between last post and now. Updated server, updated client, loaded new world, seem to still have same issue. Even just idling for 2 minutes and the cycle of "lagging out" begins. Noticed this is what pops in console when the "lag" occurs. 
![image](https://user-images.githubusercontent.com/97383956/148700508-0c2050a3-51a8-43bb-8866-429e92b93c06.png)

At this point my only guess is allocated RAM, but the recommended is 5, and the server hosting has 6 so idk

**Comment by Montruh** [comment]
Well, seems to have been a problem with BisectHosting! Ran a couple tests using the spark mod, ran the results back to the support ticket on BisectHosting, and it was apparently a node issue. Ty for the support Sharkie!

**Comment by erpark-us** [comment]
Montruh what did you end up doing to fix this? I am having the same issue with my friends using BisectHosting?

**Comment by Montruh** [comment]
> Montruh what did you end up doing to fix this? I am having the same issue with my friends using BisectHosting?

I contacted BisectHosting with a support ticket basically explaining my issue. They said I had a "node" issue.

**Comment by erpark-us** [comment]
Ok stupid question because im not tech savy but did they end up fixing it for you, or is it something you fixed yourself?

**Comment by Montruh** [comment]
> Ok stupid question because im not tech savy but did they end up fixing it for you, or is it something you fixed yourself?

Oh no worries! They fixed it for me, no problem!

**Comment by SharkieTV** [comment]
@Montruh Cool, also if you are going to play with a lot of friends I recommend running a pregen.
