### ISSUE TITLE
About the balance of game

### ISSUE THREAD

**Issue by shajjl** [LunaPixelStudios/Better-Minecraft#170]
A Vindicator can kill me in two attacks，even if I have a full set of iron armor with protection3. We don‘’t have powerful Enchanting but Skeleton have powerful arms. 
I think add more equipments such as iron shield is a good way. As compensation，maybe you could try increasing the refresh rate of the monster. 
Another question ：Dose the place of ornaments only can be equipped with XP ring and branches？or I have missed something :(

from version 1.18.1    v17

**Comment by shajjl** [comment]
about the refresh rate : I just feel that there are few monsters in the wild ，even in hard

**Comment by SharkieTV** [comment]
Some Dungeons have boosted mobs and are not meant to be fought until you have better gear.
Their is no mod that adds other Shields.
The spawn rate for monsters are quite plenty actually unless you were in a spot where their werent.

And im not sure what place of ornaments is.

**Comment by SharkieTV** [comment]
No Response

**Comment by shajjl** [comment]
> Some Dungeons have boosted mobs and are not meant to be fought until you have better gear. Their is no mod that adds other Shields. The spawn rate for monsters are quite plenty actually unless you were in a spot where their werent.
> 
> And im not sure what place of ornaments is.

I mean that 'trinket slot'.  I only found the Ender Heart and XP Conduit could be placed on that slot.

**Comment by shajjl** [comment]
> Some Dungeons have boosted mobs and are not meant to be fought until you have better gear. Their is no mod that adds other Shields. The spawn rate for monsters are quite plenty actually unless you were in a spot where their werent.
> 
> And im not sure what place of ornaments is.

I mean that 'trinket slot'. I only found  few item to put there. Most of them were useless.:(

**Comment by shajjl** [comment]
Problem: Since invisibility cape can't let the monster ignore me while sneaking and being invisible, what's use of it. XD
