### ISSUE TITLE
1.17.1 Optifine crash

### ISSUE THREAD

**Issue by VuFlub** [LunaPixelStudios/Better-Minecraft#171]
### Describe the Bug

Crash on launch with optifine

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Latest 1.17.1

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Not sure what you mean by you are using Minecraft version 1.16 with Modpack version 1.17.1?
There is only 1.16.5 and 1.18.1 and it tells you on the page what you need to do to use Optifine
