### ISSUE TITLE
Shaders in video settings 

### ISSUE THREAD

**Issue by OverthinkKidd** [LunaPixelStudios/Better-Minecraft#172]
### Describe the Bug

Hey I noticed that in the v4 the standard chests become invisible when the shader is activated in the settings, is this only the case with me? But have already tried several shaders, is just especially bad for exploring, if you do not even see the chests

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18.1

### Modloader

Forge

### Modpack Version

better minecraft plus v4 1.18.1

### Optifine

No

### Other Mods

dynamic lights

**Comment by SharkieTV** [comment]
I assume it has to be the dynamic lights mod you added, can you link it?

**Comment by OverthinkKidd** [comment]
Yes sure here the [link ](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights/files/3556319)

even if I don't think it's because of that, because even if I remove it I have the same problem, already from the moment I activate the shader the chest disappears in front of me

**Comment by SharkieTV** [comment]
Maybe see if removing Entity Culling works?

**Comment by OverthinkKidd** [comment]
I will test it

**Comment by OverthinkKidd** [comment]
Unfortunately no change

**Comment by SharkieTV** [comment]
yeah it seems like there is an issue with this. Ill look into it

**Comment by OverthinkKidd** [comment]
Thanks a lot, because I would really like to play with shader, there is actually no option in the modpack to allow torches to glow in the hand without adding dynamic lights?

**Comment by SharkieTV** [comment]
Ill add add dynamic lights in the next update. Ill also try to fix the issue too.

**Comment by MrMonsterYT0** [comment]
I got the same issue without shaders
