### ISSUE TITLE
Structures from The Graveyard generate at the bottom of the Aether

### ISSUE THREAD

**Issue by RelativeProgramming** [LunaPixelStudios/Better-Minecraft#173]
### Describe the Bug

At the very bottom of the Aether several dungeons/structures from The Graveyard can be found, that clearly don't belong there (floating grass, etc.).

### Reproduction Steps

1. Generate new World
2. Go to Aether Dimension
3. Look for Dungeons at height 0

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate #154
