### ISSUE TITLE
FTBLIBRARY, Xaeros World Map won't : set day/night,  teleport to a location

### ISSUE THREAD

**Issue by rollandcarasi** [LunaPixelStudios/Better-Minecraft#174]
### Describe the Bug

So i got my server of Forge running and doing as fine as he can, and i m running Minecraft Java, with the CurseForge app and it's mod ,,Better Minecraft'' And when i started playing i noticed that i can't teleport anywhere, i can't set day or night from Minecraft only from the cmd console that shows the server's status, and that s wierd, i can't configurat nothing in the mods playlist neither, i need help, please?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/99193425/156827478-493f441d-71f7-4e5a-bbde-f4614301f846.mp4

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.1

### Optifine

No

**Comment by SharkieTV** [comment]
You need to be an operator (Admin). Type op USERNAME in the terminal. This is not an issue with the pack you need special perms.

**Comment by rollandcarasi** [comment]
I did that
