### ISSUE TITLE
End Portal and Obsidian towers spawn higher everytime we spawn the dragon

### ISSUE THREAD

**Issue by TheRealShame** [LunaPixelStudios/Better-Minecraft#175]
### Describe the Bug

As stated, every time we spawn the ender dragon with end crystals, a new portal spawn a few blocks higher and the obsidian towers spawn higher aswell.

### Reproduction Steps

1. Place end crystals on old portal
2. New portal spawns ontop of player and suffocates.
3. New obsidian towers spawn higher than previous ones
...

### Screenshots and Videos

![2022-03-04_23 11 34](https://user-images.githubusercontent.com/28262941/156842588-84167a69-558e-4276-9c64-3df6edb4f7a1.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V17

### Optifine

No

### Other Mods

Nothing

**Comment by SharkieTV** [comment]
This does not seem to happen in a new world. I can only assume this happens because of updating your world from previous versions.

**Comment by TheRealShame** [comment]
So only resetting the end will work?

**Comment by SharkieTV** [comment]
I guess that could work but you have to use NBTExplorer to properly reset it

**Comment by TheRealShame** [comment]
Thanks will look at it
