### ISSUE TITLE
Crashing and can't even loggin

### ISSUE THREAD

**Issue by starkg06** [LunaPixelStudios/Better-Minecraft#177]
### Describe the Bug

I just oppened the last version of the server and as soon as i enter the server it disconnect me, also the server icon its not showed in server list.

here's report link: [https://bytebin.lucko.me/zYSW0GS5YR](https://github.com/LunaPixelStudios/Better-Minecraft/issues/url)
please help i really want to play it with friends

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![crash1](https://user-images.githubusercontent.com/82785890/156851365-08061f47-33db-4503-b2df-3d04b57564df.png)
![crash2](https://user-images.githubusercontent.com/82785890/156851372-ee8c8025-2322-4153-a1fe-84242ec225bf.png)

### Crash Report or Log

https://bytebin.lucko.me/jLw7cK7U9C

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
From the Terminal is seems you are running a Vanilla Server and thats why you are crashing when trying to join

**Comment by SharkieTV** [comment]
No Response
