### ISSUE TITLE
Tried to load a block entity for block warning

### ISSUE THREAD

**Issue by DuckFeatures** [LunaPixelStudios/Better-Minecraft#178]
### Describe the Bug

Fresh install of the latest version (v17) autoinstall from mcprohosting(serverhost) once it finishes installing i launch the server and once everything has been loaded and prepared i get nothing but server warnings i don't get lag at all or crashes but its a worry not too sure if the screenshot is helpful enough

### Reproduction Steps

1.Launch server
2.It loads and initialize
3.Then i get aload of server warnings
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/100981722/156865098-1023ad1b-e691-468a-a074-7422a1e40309.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17 

### Optifine

No

**Comment by SharkieTV** [comment]
The Block warning is normal
