### ISSUE TITLE
Crashed Fabric Better MC v17

### ISSUE THREAD

**Issue by rlane85** [LunaPixelStudios/Better-Minecraft#179]
### Describe the Bug

Was just exploring shortly after nightfall and game crashed. Nice error reporting though. Only setting I changed besides keybinds were view and sim distance & disabled fullscreen

Love this modpack btw! Been playing FML version, but getting bored waiting for long load times so decided to try out the fabric version. A++!

### Reproduction Steps

1.  Run around aimlessly around 7pm game time
2. Disable fullscreen
3. set view distance and simulation distance to 20
...
Profit

### Crash Report or Log

 https://crashy.net/xmkvQKR0SSLtrmNAiha1

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
It seems like Sodium mod is causing the issue, I am unable to replicate it, I think what is happening is your pc is struggling to run the pack when you turned fullscreen off as it then renders everything else in the background as fullscreen focuses on the pack and it crashes because of it. What are your pc specs?

**Comment by rlane85** [comment]
> What are your pc specs?

That could very well be the issue. 10 years ago this thing was a beast, now it's definitely turned into sort of a Frankenstein's monster. It's decent, but also falling out of maintenance. 

I've got 32GB of RAM (allocate 6 usually for most modpacks). It's a i7-3970X 3.5GHz 6 core CPU. 2x GTX 680s. Should be plenty but like I said...the system is very old.

And yes, it does crash on Fabric way more than Forge. Mostly because of Sodium usually. But there are few other "obvious" issues that I sort of ruled that out. I can usually run at those settings by just not enabling shaders and I don't see any dipping of FPS too much. But, these type of errors with Fabric are completely confusing to me. So, thanks for the thought! If you can't reproduce it, I'd go ahead and close it unless you get some similar reports.

**Comment by SharkieTV** [comment]
Try playing around with the Video Settings on Fabric and if none of them works don't play windowed Mode.
