### ISSUE TITLE
Lan not working

### ISSUE THREAD

**Issue by ThaisHalsey** [LunaPixelStudios/Better-Minecraft#18]
### Describe the Bug

Lan isin't working due to ?firewall? even if firewall is off.
love your work I wish i could play with my girlfriend

### Reproduction Steps

1.
2.
3.
...

### Operating System

Macbook Pro OS

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.1

### Optifine

I used Optifine

**Comment by ThaisHalsey** [comment]
Alright, I understand, thank you so much for your answer! One last thing: I use a MacBook, I have enough RAM to make a server, but I tried and couldn't create a server (I used multiple tutorials that are not specific to my case), do you know a TUTORIAL for installing Better Minecraft server pack on A MAC?

**Comment by SharkieTV** [comment]
You can try this https://www.youtube.com/watch?v=wUD__7Lkybc other than that not much we can help with setting up servers.
