### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by l2blaze1** [LunaPixelStudios/Better-Minecraft#180]
### Describe the Bug

i cant hear anything in minecraft, i tried reinstall launcher, java, change folder but it not work.

### Reproduction Steps

1.
2.
3.
.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/101002392/156889040-e4ac32c0-fab4-4d9a-b31f-099f4f2bda40.png)

### Operating System

window 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
See if removing Dynamic Sound Filters Mod helps

**Comment by l2blaze1** [comment]
> See if removing Dynamic Sound Filters Mod helps

i tried but not work, i still hear anymob sound but not all

**Comment by SharkieTV** [comment]
Well unforntely there is no other mod that messes with audio except that, otherwise it has to be your pc as I cant recreate it. I suggest reinstalling and removing the mod before you launch the Modpack

**Comment by l2blaze1** [comment]
> Well unforntely there is no other mod that messes with audio except that, otherwise it has to be your pc as I cant recreate it. I suggest reinstalling and removing the mod before you launch the Modpack

i really wanna try this modpacks, my 1.16.5 betteminecraft still working well, but mod 1.18.1 have no anysound. can you help that

**Comment by SharkieTV** [comment]
I told you what to do so try it
