### ISSUE TITLE
Losing enchantments

### ISSUE THREAD

**Issue by Henlofren** [LunaPixelStudios/Better-Minecraft#181]
### Describe the Bug

I've lost several enchantments, on both tools and armor, over time playing this modpack. I've lost mending on my diamond pickaxe twice, lost vein mining on my axe, and lost mending on my diamond helmet. I'm unsure what is causing the bug, it seems to lose it when I first join the game, perhaps?

### Operating System

Windows 10 Pro

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V 55HF.zip

### Optifine

No

### Other Mods

I removed Twilight Forest and Dragon Mounts.

**Comment by SharkieTV** [comment]
A mob from Outvoted mod can steal your enchants off if it attacks you

**Comment by Henlofren** [comment]
Ah, thank you so much. Sorry about this then!
