### ISSUE TITLE
Rename "Hosting a Server" to "Renting a Server"

### ISSUE THREAD

**Issue by 0xpr03** [LunaPixelStudios/Better-Minecraft#182]
As the title says, the current title misleads by making you think it's an article about stuff to be aware of when hosting this modpack (minimum RAM, world seed,...). Instead its an Ad in disguise.
I am the "hoster", I want to know stuff I need to think of when hosting this. This is about renting a hosted server.

**Comment by SharkieTV** [comment]
Not sure what your trying to do here but the website literal name is called Bisect Hosting. If you hover over it, it also tells you to get 25% off, It not misleading when your the only person who's miss interpreted it.

**Comment by 0xpr03** [comment]
"Hosting a Server" is something different to me than "Bisect Hosting" - The company. "Hosting" the verb is to me the act of hosting something yourself.
