### ISSUE TITLE
*Bug* Nether Gauntlet Defeated. Quest Book does not Register/Update. Rewards Not Given

### ISSUE THREAD

**Issue by MythBeyondLegend** [LunaPixelStudios/Better-Minecraft#183]
Me and my friend defeated the Nether Gauntlet and it did not update in the Quest book, and we're locked out of the rewards. 

Operating System
window 11

Minecraft Version
1.18

Modloader
Fabric

Modpack Version
v17

https://user-images.githubusercontent.com/99859848/156957944-6fc5d3a3-0177-4de6-a615-458cceae3fc2.mp4

**Comment by MythBeyondLegend** [comment]
Actually i just realized. You have to defeat the soul reaper first in order for that to register dont you

**Comment by SharkieTV** [comment]
You need to defeat the soul reaper before you can kill the Nether Gauntlet
