### ISSUE TITLE
Server hanging causing watchdog to consider crashed

### ISSUE THREAD

**Issue by Simmons928** [LunaPixelStudios/Better-Minecraft#184]
### Describe the Bug

We ran into a server crash on the latest Fabric version of this mod. 
We seems to have been able to narrow it down to a player, upon connecting to the server, causing the hang leading to the watchdog assuming a crash 
If necessary, I can provide a backup I took of the server when the issues started. 

Attempted to load the player in a single player version of the server and the game refused to load. 

I stopped the crash by rolling back the player in question to the last backup before the issue started. 
to test the idea, I first reset him to nothing and when he connected the server did crash. 

### Reproduction Steps

1.Player donut223 Connects to server
2.Server Hangs
3.WatchDog assumes crash

### Crash Report or Log

https://pastebin.com/phzqax70

### Operating System

Window 10(Client) / Linux Unraid 6.9.2 AMP in Docker (Server)

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

### Other Mods

Dynmap-3.3-fabric-1.18
mysql_jdbc-8.0.27+20211227-all

**Comment by SharkieTV** [comment]
It says Dynmap is causing the issue, please only report Issues here if you have not Modified the modpack.

**Comment by Simmons928** [comment]
Sharkie, Thanks for the quick response. 
I am very unfamiliar with reading the crash logs. So I missed that in my attempt to look through the crash log. 
Now that you mention that, I do see that it seems to be one of the only mods mentioned in the crash log as well as the one that is mentioned the most. 
Is that what you are going off of, or is there something else I am not seeing? 
Trying to learn a little, if possible, I don't like to bug people if I don't have to. I especially don't like bugging the wrong people.

**Comment by SharkieTV** [comment]
It's easier for me to have a Crash log with no added mods in order to asses if its actual an issue with the Modpack or the Mods you added. If you can remove both the Mods the and get the issue again then send in the new crash report.

**Comment by Simmons928** [comment]
Removed both Dynmap and the SQL driver. 
I was able to duplicate the crash. 

New Crash Log:
https://pastebin.com/DYzZndAi

**Comment by SharkieTV** [comment]
net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:114)
at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$PositionAndOnGround.apply(PlayerMoveC2SPacket:42)
ru.betterend.util.BlockFixer.lambda$fixBlocks$1(BlockFixer.java:78)
ru.betterend.util.BlockFixer$$Lambda$11307/0x000000080257c000.accept(Unknown Source)

Seems to be some issue with the packet or block he has on him.
Did you recently update the Server?
I think the best way to get him back is to reset his player data but if possible you could try and see what he has on his body by somehow /kill when he spawns or if he knows. 
Or this could simply be an issue with XL Packets mod or Krypton Mod.

So you can try removing one mod at a time of XL Packets Mod or Krypton Mod.
And if they dont work you can try to delete his player data.

**Comment by Simmons928** [comment]
I updated the server saturday the 5th after I noticed another player was getting frequent crashes. when logging in. I can get that those logs too but they will ha e the dynmap and sql mod in them.  I did not think to report it at the time because the problem stopped after the update so I assumed that the issue was solved. 

This happened while we were all on discord together. After some trial and error we figured he likely picked something up that the game did not like but due to what he was doing at the time (exploring the end and raiding an end city) he was not sure what exactly he had on him.

I will do some more testing in the tomorrow to figure out what he has on him and see if I can identify the culprit if it is a block that is causing the problem. 

I rolled his profile back to the last nightly backup and the crashes stopped happening when he logged in. I will let you know if we have something similar happen again.

**Comment by Simmons928** [comment]
Performed some more testing, 
XL Packets nor Krypton being disabled changed the behavior. 
User has noting in their inventory that is causing a problem. 

I flew out to the location in the end where the user that was causing the issue was, and I was able to get the issue to reoccur. 
Looks like I have a corrupted chunk or something like that because the moment I got to the end city where the player was, chunks stopped loading and the watchdog shutdown the server.

**Comment by SharkieTV** [comment]
It is possible an update could have caused that corrupted chunk. You could reset the End Dimension to be safe.
Use NBTExplorer to delete the End Dimension and Dragonfight to reset it properly

**Comment by Simmons928** [comment]
I attempted to delete the chunks in and around that area using MCA Selector but it still does not like that area, 
I keep a full reset on the back burner. It is only a handful of us on the server and they have all been advised to say well clear of the end city in question. If they make a habit of crashing the server, I will go through the reset.
