### ISSUE TITLE
Crash on chunk load (I am assuming)

### ISSUE THREAD

**Issue by Jeramy-T** [LunaPixelStudios/Better-Minecraft#185]
### Describe the Bug

Fresh installation of Better Minecraft FORGE 1.18.1 v18 on MCProhosted server.  Even wiped and reloaded after another world did the same thing and I assumed it was something wrong with that world (but I did not capture the logs from the first load).  I even tested with Radium removed and still received the same crash.

### Reproduction Steps

1.Walk into chunk
2.Server crashes after chunk loads
3.
...

### Crash Report or Log

https://pastebin.com/7KAyJzms

### Operating System

Red Hat Linux

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

### Other Mods

No other mods installed.

**Comment by SharkieTV** [comment]
Can you test without Radium and send me that Crash as this has Radium in it.
This is also something I cant replicate and it doesn't other than its a ServerChunkCache issue. People have had previous issues with my pack with MCProhosted servers. This works fine with Bisect Hosting and Local Hosting.

**Comment by Jeramy-T** [comment]
This is the crash report without Radium:

https://pastebin.com/018KsPjZ

If you have any other ideas for mitigation, please let me know.

Thank you.

**Comment by Jeramy-T** [comment]
I am currently running World Pre Generator on the server and disabled the max tick time.  I will report back if this fixes the issue.

**Comment by SharkieTV** [comment]
The crash doesnt tell me what mod is causing the issue and its just something about Server Chunk Cache.
You are not playing while pregenning right?

**Comment by Jeramy-T** [comment]
No, I was not.  I am waiting for the pregen to end, but I had not pre-gen'd the world prior to playing.  

One thing that caught me from each of the crash reports was the ServerHangWatchdog.  I am testing if the server.config max-tick-time being set to 60 seconds may have been part of the issue as complex chunks may have taken longer to load due to all of the mods.  Prior to pre-gen'ing, my wife had tested loading the problem chunks by pulling the Repurposed Structures mod and the server did not crash, which lends to the idea that the mods are increasing generation times beyond the 60 second window and Server Watchdog is thinking the server is hung.

I will report back within 24 hours if this resolves my issue.

**Comment by Jeramy-T** [comment]
Turning off the max tick time has appeared to have solved my issue.

**Comment by SharkieTV** [comment]
Cool thanks for the report
