### ISSUE TITLE
mid air mob spawning

### ISSUE THREAD

**Issue by Luigi505buzu** [LunaPixelStudios/Better-Minecraft#186]
### Describe the Bug

 i have a problem and hope someone can help. I have been playing better minecraft lately and today i decided to build a mob/xp farm. This includes a ton of water and is way up in the air. The problem is that when i am present next to the floating structure millions of birds and forest animals spawn in the air and fall down. Later i noticed that they all survive the fall and its super laggy. I cant stop them from spawning. Is it because of the water?

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
Could you show a Screenshot of this?
