### ISSUE TITLE
Xaero's World Map and FTBLibrary wont work properly

### ISSUE THREAD

**Issue by rollandcarasi** [LunaPixelStudios/Better-Minecraft#187]
### Describe the Bug

When i want to set day or night while being on my inventory page it wont work, because of ftblibrary you got some blue buttons in the top left corner, but they wont work, they give me a red sentence error in the minecraft chat, and yes, i m an operator, it s on a server too, and so does this happend with Xaero's World Map, i cant teleport. Help

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.1

### Optifine

No

**Comment by SharkieTV** [comment]
I have tested it and it works fine, again if it doesnt work you are not OP like you think you are. Are you able to go creative mod? if not then no you are no OP.
