### ISSUE TITLE
Slime blocks stick to honey blocks

### ISSUE THREAD

**Issue by bldhf** [LunaPixelStudios/Better-Minecraft#188]
### Describe the Bug

Slime blocks stick to honey blocks...

### Reproduction Steps

1. Get a piston
2. Place a slime block in front of it
3. Place a honey block next to the slime block
4. Turn on the piston
5. Observe that they stick to each other. They're not supposed to do that.

### Operating System

MacOS 11.5.2

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by SharkieTV** [comment]
The Mod called The Bumblezone is causing that, If you dont want it you can remove the mod and see if this is also intentional by the Mod Dev
