### ISSUE TITLE
Issue when oppening BMC 1.18.1 v19 forge for the first time

### ISSUE THREAD

**Issue by mathiskrr** [LunaPixelStudios/Better-Minecraft#189]
### Describe the Bug

I launched the better minecraft modpack forge 1.18.1 and got a crash due to a mod (Blue Skies). i didnt change or add mod in the modpack.

### Reproduction Steps

1. i downloaded the modpack
2. i launched it
3. and got the crash due to Blue Skies

### Screenshots and Videos

![Capture d’écran 2022-03-09 193311](https://user-images.githubusercontent.com/94641551/157508035-fb0f87fb-0b80-4aea-81ea-9e9f08fe5808.png)

### Crash Report or Log

https://pastebin.com/NCuyccti

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v19

### Optifine

No

### Other Mods

No mod added

**Comment by SharkieTV** [comment]
Did you try launching it again or a reinstall?

**Comment by mathiskrr** [comment]
Hello thank for the fast answer i did windows update and restart myu computer and the modpack and its working great :D
