### ISSUE TITLE
Game Crashed for unknown reason

### ISSUE THREAD

**Issue by RayquazaKing04** [LunaPixelStudios/Better-Minecraft#19]
### Describe the Bug

My Ram usage is bad without deleting some mods but after deleting, it ran a lot better, I loaded into worlds, however, this one struck me odd since I wanted to make a new one after deleting another few mods to hopefully improve performance, When I try to start a world, everything runs somewhat smooth but after a while on 100% loaded it crashes on me and gives me this error code.
Note: I use the Forge launcher and use fabric loader 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/84650466/148848244-0c06b7ae-fa44-45b7-814b-0cccc0c481eb.png)

### Crash Report or Log

https://pastebin.com/yUCJk1wi

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1.18

### Optifine

I used Optifine

**Comment by Hotdogwastaken49** [comment]
Try removing optifine first to see if Optifine is the cause

**Comment by Hotdogwastaken49** [comment]
If Optifine is not the cause create a new profile with the all the mods but without Optifine to see if its the mods that you removed which is the problem

**Comment by RayquazaKing04** [comment]
I know its not optifine because i have no problem loading into the game mutiple times, runs smoothly but after another time trying to play it would crash.

**Comment by SharkieTV** [comment]
Update to the latest version of the pack, you are also not using optifine so not sure why you saying you are, also allocate more ram as it seems your ram is maxing out.

**Comment by Hotdogwastaken49** [comment]
Ok. Its saying "world is null" meaning the world does not exists are you loading a new or old world. If its a new world does this happen every time you create a new world.

**Comment by RayquazaKing04** [comment]
I could of sworn i had it in the folder, sorry for the mixup, and how would i allocate more ram?

**Comment by SharkieTV** [comment]
How much RAM do you have? 

Here is how to allocate ram.
CurseForge Launcher: https://youtu.be/P3hd9MKWvXw?t=130
GD Launcher: https://youtu.be/P3hd9MKWvXw?t=383
MultiMC: https://youtu.be/P3hd9MKWvXw?t=452
