### ISSUE TITLE
Damage Bug

### ISSUE THREAD

**Issue by BewitchedNight** [LunaPixelStudios/Better-Minecraft#190]
### Describe the Bug

I have had an issue with my player and mobs not taking any fire, water, freezing, or fall damage. I have gone through the gamerules and made sure everything was set to true but that didn't fix it, (Version 17-18 have had this issue)

### Reproduction Steps

There really isn't anything I can say to reproduce it because it starts upon world creation. I have tried to make different worlds and it still happened =. 

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18

### Optifine

No

### Other Mods

Only one mod called rings of ascension fabric

**Comment by SharkieTV** [comment]
Im unbale to reproduce this and am not getting the same issue creating new worlds. All mobs and me take damage.
