### ISSUE TITLE
server connection

### ISSUE THREAD

**Issue by hissinggoat** [LunaPixelStudios/Better-Minecraft#191]
### Describe the Bug

kicked out as soon as i join

### Reproduction Steps

1.logged into mincraft
2.clicked join server 
3.kicked out
...

### Crash Report or Log

https://github.com/hissinggoat/minecraft-crash-file/blob/main/crash-2022-03-09_23.56.26-client.txt

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

17 

### Optifine

No

**Comment by hissinggoat** [comment]
im launching this from curse forge

**Comment by SharkieTV** [comment]
That usually means that mods are mismatched or the server does not have the right mods. Send your log of the Server too.

**Comment by RelativeProgramming** [comment]
I have the same problem. I updated the server and my client to v18, but in the server browser it says I'm still running v17 (I think the problem lies in the bcc.json in the minecraft folder).
(Btw. you need to bump the fabric version in the start.bat)

**Comment by SharkieTV** [comment]
It has nothing to do with the BCC mod, its just a mod that tells you what version the pack is with a config and you can still join regardless. Ill update to fix the config but it doesnt have anything to do with this crash he had

**Comment by StormWolf907** [comment]
My friend and I are having the same issue. We updated our server and now cannot log in. Every time we try it will stop in while loading terrain and then suddenly say Connection Lost.
