### ISSUE TITLE
Chocapic13 sharders black screen

### ISSUE THREAD

**Issue by mathiskrr** [LunaPixelStudios/Better-Minecraft#192]
### Describe the Bug

Hello i wanna use the sharders Chacapic13_V9 to the modpack BMC 1.18.1 but when i enable it i got all in black and can't see nothing. I have a RTX 2060 6Go. Is it possible to delete the mod which is used for the settings and put Optifinie if yes what is the mod??

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![gfhjgfhjgfjghfj](https://user-images.githubusercontent.com/94641551/157643967-40beed8e-8aa1-4155-b87a-ba1d04c66294.png)
![unknozergzergzergwn](https://user-images.githubusercontent.com/94641551/157644029-914ee3fd-00be-4cff-a0ce-aeab196f33a6.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v19

### Optifine

No

**Comment by SharkieTV** [comment]
Nothing I can do about the Shaders. Go talk to the Shader Dev.
Removed Rubidium and Oculus if you want to use Optifine
