### ISSUE TITLE
Mooshrooms are not spawning in mushroom fields after initial chunk load

### ISSUE THREAD

**Issue by MiarKraiM** [LunaPixelStudios/Better-Minecraft#193]
### Describe the Bug

Mooshrooms are only spawning at the initial chunk load and then no more respawn in the Mushroom Fields Biome

### Reproduction Steps

1. create a world
2. teleport to a mushroom fields biome
3. Kill everything
4. other mobs spawn but no mooshrooms
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v17

### Optifine

No

**Comment by SharkieTV** [comment]
Remove the Chirpy's Wildlife mod to fix the Issue
