### ISSUE TITLE
how do i increase ram for the server

### ISSUE THREAD

**Issue by boredbruh** [LunaPixelStudios/Better-Minecraft#194]
have made a server from the server pack of better Minecraft 1.16.5 forge, its launching and everything just dont understand how to increase the ram for the server. 
this is the modpack i am using - and i am using its server pack 
https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack

This is the start.bat file 
:: Start script generated by ServerPackCreator.
:: This script checks for the Minecraft and Forge JAR-files, and if they are not found, they are downloaded and installed.
:: If everything is in order, the server is started.
@ECHO off
SetLocal EnableDelayedExpansion

SET JAVA="java"
SET MINECRAFT="1.16.5"
SET FORGE="36.2.29"
SET ARGS=
SET OTHERARGS="-Dlog4j2.formatMsgNoLookups=true"

SET AGREE="I agree"

IF NOT EXIST forge.jar (

  ECHO Forge Server JAR-file not found. Downloading installer...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('https://files.minecraftforge.net/maven/net/minecraftforge/forge/%MINECRAFT%-%FORGE%/forge-%MINECRAFT%-%FORGE%-installer.jar', 'forge-installer.jar')"

  IF EXIST forge-installer.jar (

    ECHO Installer downloaded. Installing...
    java -jar forge-installer.jar --installServer
    MOVE forge-%MINECRAFT%-%FORGE%.jar forge.jar

    IF EXIST forge.jar (
      DEL forge-installer.jar
      ECHO Installation complete. forge-installer.jar deleted.
    )

  ) ELSE (
    ECHO forge-installer.jar not found. Maybe the Forges servers are having trouble.
    ECHO Please try again in a couple of minutes.
  )
) ELSE (
  ECHO forge.jar present. Moving on...
)

IF NOT EXIST minecraft_server.%MINECRAFT%.jar (
  ECHO Minecraft Server JAR-file not found. Downloading...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar', 'minecraft_server.%MINECRAFT%.jar')"
) ELSE (
  ECHO minecraft_server.%MINECRAFT%.jar present. Moving on...
)

IF NOT EXIST eula.txt (
  ECHO Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA.
  ECHO Mojang's EULA is available to read at https://account.mojang.com/documents/minecraft_eula
  ECHO If you agree to Mojang's EULA then type "I agree"
  set /P "Response="
  IF "%Response%" == "%AGREE%" (
    ECHO User agreed to Mojang's EULA.
    ECHO #By changing the setting below to TRUE you are indicating your agreement to our EULA ^(https://account.mojang.com/documents/minecraft_eula^).> eula.txt
    ECHO eula=true>> eula.txt
  ) else (
    ECHO User did not agree to Mojang's EULA. 
  )
) ELSE (
  ECHO eula.txt present. Moving on...
)

ECHO Starting server...
ECHO Minecraft version: %MINECRAFT%
ECHO Forge version: %FORGE%
ECHO Java version:
%JAVA% --version
ECHO Java args: %ARGS%

%JAVA% "%OTHERARGS%" %ARGS% -jar forge.jar nogui

PAUSE

would be great if someone can tell me how to increase the server ramm ty

**Comment by SharkieTV** [comment]
This is a question that can be asked in the discord.

Change this SET OTHERARGS="-Dlog4j2.formatMsgNoLookups=true"
to something like this
OTHERARGS="-Xms3G -Xmx6G -Dlog4j2.formatMsgNoLookups=true"
