### ISSUE TITLE
BIG BUG

### ISSUE THREAD

**Issue by shajjl** [LunaPixelStudios/Better-Minecraft#196]
### Describe the Bug

All enchanting processes will enchant items with the HIGHEST level!!!

### Reproduction Steps

1.
2.
3.
...

### Operating System

win 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18HF

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Could you elaborate more and show some sort of screenshots or videos?

**Comment by Likan1235** [comment]
I have the same issue, usually all you have to do is get an enchantment with a lower level than it's max and then add it to any item that can accept it.

I can give an example with a fishing rod here when I'm adding a lure 1 book but I'm getting a lure 3 fishing rod.
![image](https://user-images.githubusercontent.com/91690306/158013813-eb5e33ae-e34b-4b68-a407-a012bc72a83a.png)
![image](https://user-images.githubusercontent.com/91690306/158013828-ee57f22a-2989-474d-97ac-2613d916e8f8.png)

**Comment by shajjl** [comment]
![Minecraft_ 1 18 1 - Singleplayer 2022_3_12 19_23_07 (2)](https://user-images.githubusercontent.com/46836484/158016188-dbdb9c6b-a762-44ed-a12c-b212efd9bbfb.png)
![Minecraft_ 1 18 1 - Singleplayer 2022_3_12 19_23_16 (2)](https://user-images.githubusercontent.com/46836484/158016193-7c9bb98a-f2fe-408a-a35d-70dbe26f8f13.png)

**Comment by shajjl** [comment]
Thanks to this bug, I got a lot of good equipment.hahaha :)

**Comment by SharkieTV** [comment]
Thanks for the report will see if this issue still persists in 1.18.2 as 1.18.1 will be discontinued
