### ISSUE TITLE
Game crashes when a skeleton shoots me occasionally

### ISSUE THREAD

**Issue by Henlofren** [LunaPixelStudios/Better-Minecraft#197]
### Describe the Bug

I'm not certain what about it it's not liking, but twice now a skeleton (or maybe an enchanted skeleton) has shot me and caused the game to crash.

Error it gave me:
The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Can't find attribute omnis:magic_resistance
Exit Code: -1

### Reproduction Steps

1. Get shot by skeletons??
2.
3.
...

### Crash Report or Log

https://gist.github.com/Henlofren/4cff33aea70727cd3468a316fe20182d#file-gistfile1-txt

### Operating System

Windows 10 Pro

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V 55HF.zip

### Optifine

No

### Other Mods

Removed Twilight forest.

**Comment by SharkieTV** [comment]
Fixed in latest version of the modpack
