### ISSUE TITLE
Rendering Block Entity Crash

### ISSUE THREAD

**Issue by suiyuan66** [LunaPixelStudios/Better-Minecraft#199]
### Describe the Bug

Crashes while entering certain chunk on server. Player placed a blossom sign from supplementaries mod and crashed. Any other player entering that chunk will crash and be given this error: 

**The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m119194(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$12" is null
Exit Code: -1**

### Reproduction Steps

1.  Place blossom wood sign
2.  Enter chunk 
3.  Game crash
...

### Screenshots and Videos

https://imgur.com/a/utumckR

### Crash Report or Log

https://pastebin.com/z7hwpTX0

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V18

### Optifine

No

**Comment by SharkieTV** [comment]
Seems liek the Rubidium Mod is causing this crash because of a render issue, best is to not place the Sign until a Mod Update fixes it, in the meantime you can either remove the mod to remove the sign to fix the chunk or not remove it and not go to the chunk.
