### ISSUE TITLE
I'm stuck in the end

### ISSUE THREAD

**Issue by MatthewMc123** [LunaPixelStudios/Better-Minecraft#200]
### Describe the Bug

Me and my friend are getting elytra but I cant get home because theres no end gateways Is there anything i can do cos we traveled really far

### Reproduction Steps

1.
2.
3.
...

### Operating System

10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Their are end gateways? Or you can just go back to the main island? or you can use a waystone? Not really a bug and more of a question you can ask in the discord
