### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Annnekkk** [LunaPixelStudios/Better-Minecraft#202]
### Describe the Bug

When I start the server, I aways got this: `[04:35:43] [Server thread/ERROR]: Error reading from the Graveyard config file: Allowed biome category/biome is null. Try to delete the file and restart the game.`
And I can't connect to my server by anyway.
I'm using Azure with B4 VM, and Windows Server 2022

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Uploading image.png…]()

### Operating System

Windows Server 2022

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18

### Optifine

No

**Comment by SharkieTV** [comment]
Can you please provide a full log and the image doesnt work.
Have you tried deleting the Config files?

**Comment by mondjunge** [comment]
Have this problem after updating server from 16.5 to 18. Searched for the graveyard config file. found none. Where should it be located?

**Comment by mondjunge** [comment]
> Have this problem after updating server from 16.5 to 18. Searched for the graveyard config file. found none. Where should it be located?

Of course I found it right after sending this post... config/the-graveyard-config.json5
