### ISSUE TITLE
Crash on Minecraft Launcher start up

### ISSUE THREAD

**Issue by Keigon-art** [LunaPixelStudios/Better-Minecraft#204]
### Describe the Bug

Everytime i load the better minecraft on the minecraft launcher it crashes

### Reproduction Steps

1. Open CurseForge App
2. Press Play button on Better Minecraft [PLUS] v4.zip
3. Goes to the Minecraft Launcher and wait
...

### Screenshots and Videos

![Screenshot 2022-03-15 150131](https://user-images.githubusercontent.com/101611132/158452586-669e9c9a-c44c-4c9b-b080-47d524b68ad3.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] v4.zip

### Optifine

No

**Comment by SharkieTV** [comment]
This only happens if you modify the pack, did you do anything if not then when you say "Press Play button on Better Minecraft [PLUS] v4.zip" the .zip is just throwing me off. It shouldn't say.zip anywhere, just Better Minecraft [PLUS] v4. Can you show a screenshot of the modpack on cursefroge?

**Comment by Keigon-art** [comment]
![Uploading Screenshot 2022-03-15 170827.png…]()

**Comment by Keigon-art** [comment]
![Screenshot 2022-03-15 170827](https://user-images.githubusercontent.com/101611132/158473491-cf867635-410d-4978-8e73-270e3b26fe95.png)

**Comment by SharkieTV** [comment]
ah ok well can you send me your latest.log in your modpack folder in logs folder

**Comment by SirKrunk** [comment]
do you have java 17? its required for 1.18+

**Comment by Keigon-art** [comment]
![Screenshot 2022-03-20 193543](https://user-images.githubusercontent.com/101611132/159190875-57b8f6d7-0e84-4c6c-8e9b-37d5f71427ce.png)
and i do have java 17

**Comment by SirKrunk** [comment]
can you send your logs?

**Comment by Keigon-art** [comment]
[latestest.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8319285/latestest.txt)

**Comment by SirKrunk** [comment]
try playing without shaders

**Comment by SharkieTV** [comment]
It seems to be an issue with Create, I will see if I can fix it in next update

**Comment by SharkieTV** [comment]
1.18.1 is no longer being developed because I am focusing on 1.18.2. 
The Log you send showed nothing and id suggests switching to v20 of the normal pack
