### ISSUE TITLE
No chunks load and mobs are frozen

### ISSUE THREAD

**Issue by Antonio1324tt** [LunaPixelStudios/Better-Minecraft#205]
### Describe the Bug

When I load in I cant open chest, go in portal, or sleep. Mobs also are frozen and only one chunk load

### Reproduction Steps

1. I just died in the end and it bugged out
2.
3.
...

### Screenshots and Videos

![2022-03-15_21 27 50](https://user-images.githubusercontent.com/101685795/158507470-d9f5a52c-2ca7-4383-b5c6-a8acbd0d4a52.png)

### Crash Report or Log

Doesnt give one

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
What are your PC Specs? and how much ram have you allocated? also send a Screenshot of your F3 in game

**Comment by Antonio1324tt** [comment]
LAPTOP-C463589O Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz 64-bit operating system, x64-based processor
I have 8.00ghz of ram
![2022-03-15_22 14 50](https://user-images.githubusercontent.com/101685795/158509841-72d85d8f-67a6-4bce-83e1-9dfa87727af5.png)
m

**Comment by SharkieTV** [comment]
your laptop is struggling cause you only given the game 3GB to work with you need to atleast allocate 6-8gb to the Modpack.
How to allocate RAM:
CurseForge Launcher: https://youtu.be/P3hd9MKWvXw?t=130
GD Launcher: https://youtu.be/P3hd9MKWvXw?t=383
MultiMC: https://youtu.be/P3hd9MKWvXw?t=452
