### ISSUE TITLE
Launcher fails to launch Minecraft

### ISSUE THREAD

**Issue by OffSplash** [LunaPixelStudios/Better-Minecraft#206]
### **Describe The Bug**
When I try to launch any version of Better Minecraft, the launcher is unable to start the game.
This occurs even on a fresh install of Fabric or Forge.

### **Reproduction Steps**
1. Open Curseforge
2. Click play on Better Minecraft [FABRIC] - 1.18.1
3. Once Minecraft launcher has loaded, click play.
4. Minecraft Fails to launch

### **Screenshots and Videos**
![bug screenshot](https://user-images.githubusercontent.com/101744335/158671261-64a6532a-18ed-4eba-b814-1fcfc3d3e568.PNG)

### **Crash Report or Log**
N/A

### **Operating System**
Windows 10 Home

### **Minecraft Version**
1.18.1

### **Modloader**
First experienced on Fabric, then on Forge, Forge being on a fresh install.

### **Modpack Version**
Better Minecraft [FABRIC] v18 HF.zip

### **Optifine**
I did install optifine, however this created a different error, and upon removing optifine, the error/bug present began.

### **Other Mods**
None.

### **Additional Information**
Originally I was unaware that installing Optifine would result in errors, so I added it and tried to play with it installed. 
Of course the game crashed and informed me Optifine was unnecessary, so I removed it the same way I installed it, through adding then removing the .zip to the mods folder for Better Minecraft. 
Since then the current bug has persisted, regardless of attempting to repair the profile using the CurseForge app. 
Along with that, I've deleted and reinstalled the pack, but that didn't seem to change anything.

**Comment by SharkieTV** [comment]
Did you change the path where it installs the packs? This is a launcher error and not much I can really do, you could try another launcher like GDLauncher.
