### ISSUE TITLE
PetFriendlyFire negates environmental (fall/drown/fire/frozen) damage

### ISSUE THREAD

**Issue by RemyStremy** [LunaPixelStudios/Better-Minecraft#208]
### Describe the Bug

When the PetFriendlyFire gamerule is set to false, the player and mobs do not take fall/drown/fire/frozen damage.  When this gamerule is set to true, this issue no longer occurs. 

### Reproduction Steps

1. set /gamerule petFriendlyFire false
2. Entities no longer take any environmental damage

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18 HF

### Optifine

No

**Comment by SharkieTV** [comment]
Can you see if removing the mod Companion works?

**Comment by RemyStremy** [comment]
Sure, I'll let you know how it goes tomorrow morning (AEST).

**Comment by RemyStremy** [comment]
That removes the gamerule, so I guess that fixes the issue.

**Comment by RemyStremy** [comment]
Removing the Companion mod allows players and mobs to take environmental damage again, so I guess it might be a compatibility issue with the gamerule Companion adds

**Comment by SharkieTV** [comment]
Yeah, ill report it to the dev
