### ISSUE TITLE
Sparrow spawning [Mod: Wildlife]

### ISSUE THREAD

**Issue by Themporal2** [LunaPixelStudios/Better-Minecraft#209]
### Describe the Bug

I build my base above an ocean in a skylands biome (a generated floating island).
The sparrow mob from the wildlife mod keeps on spawning there and doesn't despawn. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v18

### Optifine

No

**Comment by SharkieTV** [comment]
Best is to remove the mod, there wont be anymore updates for 1.18.1.
