### ISSUE TITLE
game crashes at loading screen

### ISSUE THREAD

**Issue by Noble-Trash** [LunaPixelStudios/Better-Minecraft#210]
### Describe the Bug

game crashes shortly after launching, does not get past loading screen

### Reproduction Steps

1. open cursedforge, launch modpack
2. click 'play' in the launcher
...

### Screenshots and Videos

![Screen Shot 2022-03-20 at 8 40 45 PM](https://user-images.githubusercontent.com/102008136/159202414-4b649c99-7eea-4aad-b693-813c8dc93d41.png)

### Crash Report or Log

https://pastebin.com/KfE7Ej1E

### Operating System

MacOS 10.13.6

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

### Other Mods

none

**Comment by SharkieTV** [comment]
Seems like a pc specs issue, try to remove Magnesium and Dynamic Lights mod and see if it helps
