### ISSUE TITLE
Game crashes at loading screen 

### ISSUE THREAD

**Issue by hypattia** [LunaPixelStudios/Better-Minecraft#211]
### Describe the Bug

game crashes shortly after launching, does not get past loading screen

log says cannot found idataprovider but i cant understand. 

### Reproduction Steps

1.open cursedforge, launch modpack
2.click 'play' in the launcher
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/81076306/159230374-0e0e765d-7801-4c15-ae49-af4c24a9a698.png)

### Crash Report or Log

https://gist.github.com/hypattia/6a6de852c623fd70dcc13fee060328f5

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v56

### Optifine

No

**Comment by SharkieTV** [comment]
Seems to be an issue with Curseforge, can you see if uninstalling Curseforge and deleting the curseforge folder  in This PC > Main Drive > users > YourUser > curseforge.
This has happened to me and I was only abler to fix it that way
