### ISSUE TITLE
wont let me play my world

### ISSUE THREAD

**Issue by RevilingSpy42** [LunaPixelStudios/Better-Minecraft#213]
### Describe the Bug

it wont let me get in my world

### Reproduction Steps

1.
2.[
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102118450/159409781-447940b8-353a-41fd-b3c4-1b2060fcd56e.png)

### Crash Report or Log

idk

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

better minecraft fabric

### Optifine

No

**Comment by SharkieTV** [comment]
I need more info please, cant help much with no information, what Modpack version are you using, what version did you start on?

**Comment by RevilingSpy42** [comment]
SharkieTV i use better minecraft fabric 1.18.2 and i stayed on this version the whole time and do you have discord that we can talk om

**Comment by RevilingSpy42** [comment]
> I need more info please, cant help much with no information, what Modpack version are you using, what version did you start on?
SharkieTV i use better minecraft fabric 1.18.2 and i stayed on this version the whole time and do you have discord that we can talk on

**Comment by SharkieTV** [comment]
this place is where we talk not discord.
Did you update the pack to v2?
If not I suggest creating a new world on v2 as something seems corrupted or switch to v20 on 1.18.1

**Comment by RevilingSpy42** [comment]
> this place is where we talk not discord. Did you update the pack to v2? If not I suggest creating a new world on v2 as something seems corrupted or switch to v20 on 1.18.1
how do i update it

**Comment by RevilingSpy42** [comment]
> this place is where we talk not discord. Did you update the pack to v2? If not I suggest creating a new world on v2 as something seems corrupted or switch to v20 on 1.18.1

wait is there a version 1.18.1

**Comment by SharkieTV** [comment]
Yes, make a new world on 1.18.1 18HF

**Comment by RevilingSpy42** [comment]
> Yes, make a new world on 1.18.1 18HF

![image](https://user-images.githubusercontent.com/102118450/160258076-07ef42d5-b5d6-4464-b7fa-42eb78b771fd.png)
what that one with a check mark by
