### ISSUE TITLE
Torch Light not showing

### ISSUE THREAD

**Issue by KakashoLin** [LunaPixelStudios/Better-Minecraft#215]
### Describe the Bug

There seems to be an issue that you are unable to show torch light from your hand. It seems to sometimes work with shaders, but for example, in Optifine and other packs you could do it without adding a shader. 

### Reproduction Steps

1. Equip Torch
2. Go to dark area
3. See there is no light if a shader isn't added
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Latest as of 3/23/22

### Optifine

No

### Other Mods

NA

**Comment by SharkieTV** [comment]
please provide a modpack version not date, this is not a bug, dynamic lights mod was added in last version of 1.18.1 and should be in 1.18.2

**Comment by KakashoLin** [comment]
Version: 1.18.2, Forge - 39.0.85,

**Comment by KakashoLin** [comment]
And looks like it is version v4

**Comment by SharkieTV** [comment]
Add this mod to your modpack https://www.curseforge.com/minecraft/mc-mods/dynamic-lights
It wasnt added in yet
