### ISSUE TITLE
Shulker box bugs

### ISSUE THREAD

**Issue by jaydhem** [LunaPixelStudios/Better-Minecraft#216]
### Describe the Bug

just general all around issues, sometimes the shulker will wipe itself unexpectedly and whenever i right click any item in the shulker box, it just disappears,

### Reproduction Steps

1. Put any item into the shulker box from your inventory
2. right click the same shulker box and the item disappears.

### Screenshots and Videos

https://user-images.githubusercontent.com/102402232/160225788-872a6657-3518-4324-a63a-2e3a5d1d5257.mp4

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v1.5.zip

### Optifine

No

### Other Mods

no

**Comment by SharkieTV** [comment]
do you have EasyShulkerBoxes mod in your server mods folder?

**Comment by SharkieTV** [comment]
disable the Shulker options in charm config

**Comment by Fuzss** [comment]
This one: `"ShulkerBoxDragDrop Enabled" = false`
