### ISSUE TITLE
World wont open

### ISSUE THREAD

**Issue by XredR3** [LunaPixelStudios/Better-Minecraft#217]
### Describe the Bug

I just started to have this issue. When I tried to open a world it just crashes and says that a mod or something had crash the game. However when I open a different world. The world loads up with all of the mods.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/85316008/160256787-6fc286b3-39ed-4a80-95b0-4248fa5c2ea4.mp4

https://user-images.githubusercontent.com/85316008/160257020-d8ac263f-a111-4cab-ba2d-23ff9cec08c5.mp4

### Crash Report or Log

https://bytebin.lucko.me/GsUZd17EME

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v2

### Optifine

No

**Comment by SharkieTV** [comment]
How much ram have you allocate? and whats your pc specs as it looks like its hard to run for you?

**Comment by XredR3** [comment]
> How much ram have you allocate? and whats your pc specs as it looks like its hard to run for you?

I have 8gs of ram. my laptop specs are a AMD Ryzen 5 4600H 6 cores, GTX 1650 4g , 1TB SSD, Windows 11

**Comment by SharkieTV** [comment]
Remove the Mod called Illager Expansion, seems to be the cause.
