### ISSUE TITLE
More Villagers Work stations Not working

### ISSUE THREAD

**Issue by Auralaina** [LunaPixelStudios/Better-Minecraft#218]
### Describe the Bug

Villagers will not take the More Villagers work stations, Tested on my server with over a dozen villagers and none would take them.
Tested in singleplayer and still did not work. i created another instance of minecraft with just more villagers installed with the same version of the mod and forge, and it worked fine. Which tells me its likely a conflict with another mod in the pack, i already msged back and forth with the creator of more villagers with the same conclusion reached.

The Villagers will take Vanilla Work Stations perfectly fine.

### Reproduction Steps

1.get a villager
2.Get a more villagers work stations
3.put the station down

and then you shall see they wont take the workstation

### Operating System

Windows 10 but issue happens on server as well

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC+ V2

### Optifine

No

**Comment by SharkieTV** [comment]
Will be fixed in v3
