### ISSUE TITLE
I can't get ore

### ISSUE THREAD

**Issue by LegendDF** [LunaPixelStudios/Better-Minecraft#219]
### Describe the Bug

I'm trying to collect a single stone, but it doesn't matter what I do.

The game breaks the block, after a long time hitting the block.

### Reproduction Steps

1.equipped a netherite pickaxe
2.I hit the stone block with it.
3.After a long time the block breaks.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102468984/160281388-b00d44b7-8ace-43bb-bfc1-7969d40048a4.png)

![image](https://user-images.githubusercontent.com/102468984/160281421-d2838887-4459-4fbd-9291-d413c62c4eb3.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1

### Optifine

No

**Comment by SharkieTV** [comment]
Fixed in v1.5 or v2 please update
