### ISSUE TITLE
Don't Visibly lose a level when using a waystone

### ISSUE THREAD

**Issue by SaltedKiwi** [LunaPixelStudios/Better-Minecraft#220]
### Describe the Bug

When you teleport with a waystone it says the level cost but when teleporting you dont lose any levels. I had 6 levels at the time and whenm i went to teleport for the 7th time wouldnt let me. I updated my xp bar and it dropped to 0 levels.

### Reproduction Steps

1. Gain 1 Level of experience
2. Use waystone to teleport
3. Try to teleport back

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18HF

### Optifine

No

**Comment by SharkieTV** [comment]
Hi, Development of 1.18.1 has stopped and I am focusing on 1.18.2 so their wont be anymore updates sorry.

**Comment by SaltedKiwi** [comment]
I couldn't select 1.18.2
