### ISSUE TITLE
crashes?

### ISSUE THREAD

**Issue by beemyu125** [LunaPixelStudios/Better-Minecraft#221]
### Describe the Bug

whener i load in my world it keeps on saying Minecraft crashed and with no error mod also for some reason if I exit out some time it says go back to sever menu which is weird cause I use single player

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102480113/160292195-08e7f21b-3669-42e4-8858-0e3ab19e250d.png)

### Operating System

window 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v2

### Optifine

I used Optifine

**Comment by beemyu125** [comment]
![image](https://user-images.githubusercontent.com/102480113/160292316-a6771303-acf6-4ee8-b2ac-3213ed0b5926.png)

**Comment by Dawn352** [comment]
Getting the exact same issue everytime i start a raid, just before it appears on the top part of the screen. Now i can not load my singleplayer world as it always tries to start the raid.

**Comment by SharkieTV** [comment]
I need the crash log please and you ticked Optifine so does that mean you modified the pack and added it ?

**Comment by SharkieTV** [comment]
If you did a  raid and it crashed Remove the Mod called Illager Expansion, seems to be the cause.
