### ISSUE TITLE
World will not load

### ISSUE THREAD

**Issue by Dawn352** [LunaPixelStudios/Better-Minecraft#222]
### Describe the Bug

Hi team,

World was working perfectly fine until I created a raid farm and went to activate it. 
"Had bad omen effect and the second I got near my village and was about to start the raid it crashed".

Now when I attempt to load this world it obviously always tries to start the raid, which when "loading the terrain" will not get past this point. Instead, displaying a black screen and eventually crashing.

Recreated this in a new world and same issue when activating a raid.

### Reproduction Steps

1. Loaded new world
2. Got bad omen effect
3. Went to a village to activate
4. Caused crash again and cant open world.

### Screenshots and Videos

Video was too large but same error as 
https://github.com/LunaPixelStudios/Better-Minecraft/issues/217

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v2

### Optifine

No

### Other Mods

Only the default ones downloaded.

**Comment by SharkieTV** [comment]
I If it is the same as #217 then ill close this and check will look for a fix their
