### ISSUE TITLE
Crashes and incompatibility 

### ISSUE THREAD

**Issue by CamboMinecraft** [LunaPixelStudios/Better-Minecraft#223]
### Describe the Bug

 Took me four hours to finally get into it after the game crashing on the loading screen multiple times even after removing unwanted mods. Then after I finally got in after 4 hours, tons of the mods were incompatible and I don’t understand why. Why is this mod pack built for 1.16.5, yet a lot of the mods say “compatible with older version”. Then when I nonetheless tried to get into a world with the few mods left, it crashed once again. This was with 7.5 gigs of ram allocated to Minecraft. I don’t understand what I’m doing wrong and why these mods aren’t compatible.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
Why are you trying to modify the pack in the first place? Your not a Modpack Dev so you don't understand how things work  about Mods. If you have a crash issue I suggest sending the log of the crash with the pack not being modified as it works the way its shipped.
