### ISSUE TITLE
Killing witches during raids have a chance to drop luck potions

### ISSUE THREAD

**Issue by John-2123** [LunaPixelStudios/Better-Minecraft#224]
### Describe the Bug

Fighting a raid with witches causes them to be able to drop luck potions.

### Reproduction Steps

1. set the difficulty to normal 
2. obtain bad omen effect
3.kill a witch during a raid
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102437861/160299449-a60422dd-f2eb-4149-8d6f-753ce2d2de8a.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Fabric - 0.13.3

### Optifine

No

**Comment by SharkieTV** [comment]
So what exactly is the bug?

**Comment by SharkieTV** [comment]
Their are mods that changes raids and witches. Ill probs not check for what mod is causing it as it could just be a mod that does it as a feature.
