### ISSUE TITLE
Cloud parachute

### ISSUE THREAD

**Issue by Lap00n** [LunaPixelStudios/Better-Minecraft#226]
### Describe the Bug

Cant use (right click) nor put in bubble slots. Using fabric 1.18.1 client.

### Reproduction Steps

1. craft cloud parachute of any kind 
2. use 
3. nothing happens
4. die...
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18 HF

### Optifine

No

### Other Mods

none

**Comment by SharkieTV** [comment]
This is a known bug and still have not been able to fix it also that your on 1.18.1 which is now no longer supported due to working on 1.18.2
