### ISSUE TITLE
Crash upon loading world

### ISSUE THREAD

**Issue by Baedau** [LunaPixelStudios/Better-Minecraft#228]
### Describe the Bug

I have been able to play in this world for some time (even using the single player world 'Open to LAN' option to let my partner join the world), however recently it has been giving me this crash in single player as soon as my friend tried to join the world. I decided to make a home server to make hosting the world easier and to try and find a way around this crash, however it does not seem to be working as I cannot get into the world alone half of the time. It has now worked on and off a few times, without me changing the modpack or anything on my computer. I have tried looking up the crash online and I haven't been able to get close to figuring it out. I am not new to minecraft modding, however it has been a while since I have played with mods. Normally I make my own modpacks, but yours intrigued me. Thank you so much for reading and hopefully there is a solution.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Baedau/7595d25edb37b9931cd221319287ee18

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1.18.2 v2

### Optifine

No

**Comment by SharkieTV** [comment]
Hi, LAN is untested and it shows when before you press it, LAN is also unsupported as it causes issues, use a Server Pack to host a Local Server on your PC
