### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by schascho** [LunaPixelStudios/Better-Minecraft#23]
### Describe the Bug

sometimes the Server crashed. 
When my Friend want to join the Server when im in it crashed.
when he join first and i join after him it didn´t crashed instand.
 Help

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7849249/latest.log)
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7849251/latest.log)

### Crash Report or Log
[crash-2022-01-11_19.20.42-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857371/crash-2022-01-11_19.20.42-server.txt)
[crash-2022-01-11_19.26.07-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857372/crash-2022-01-11_19.26.07-server.txt)
[crash-2022-01-12_16.51.10-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857373/crash-2022-01-12_16.51.10-server.txt)
[crash-2022-01-11_15.40.11-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857375/crash-2022-01-11_15.40.11-server.txt)
[crash-2022-01-11_18.29.01-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857376/crash-2022-01-11_18.29.01-server.txt)
[crash-2022-01-11_19.17.14-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7857377/crash-2022-01-11_19.17.14-server.txt)

_No response_

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v10.5

### Optifine

No

**Comment by Hotdogwastaken49** [comment]
Do you have a crash report?

**Comment by SharkieTV** [comment]
@schascho What server host are you using and can you send the Crash Report?

**Comment by schascho** [comment]
updatet  Server Host is Host-unlimited.de

**Comment by SharkieTV** [comment]
I'm not sure as the issue doesn't want to let me know what's wrong, can you add Not Enough Crashes to your server and when it crashes again please send the latest crash.

**Comment by SharkieTV** [comment]
Hi, if you would like me to look further into this issue please send me a crash report with the not enough crashes mod added so I can better further help. If not then is seems to be an issue with the host.
