### ISSUE TITLE
Nether cause server shutdown on Bisect Servers

### ISSUE THREAD

**Issue by Frostyxn** [LunaPixelStudios/Better-Minecraft#230]
### Describe the Bug

Using Bisect hosting servers.  We have been having issues within the Nether.  And now when anyone enters the Nether the player freezes up, eventually gets disconnected, and server has to restart. 

### Reproduction Steps

1. Go to the Nether and wait a few minutes
2. Dont have to move or do anything
3. Player will get disconnected and server will restart
...

### Crash Report or Log

https://gist.github.com/Frostyxn/6f8ed7f8b328f1de36dd85d2df1a376c

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

### Other Mods

No mods added.  Signed up with the Bisect Servers and had them install the Better Minecraft Forge v20 so i didnt have to do it.  Not very adept to that stuff and only was a few bucks to have them install and get everything set up.  Nothing has been added or removed to my knowledge.

**Comment by SharkieTV** [comment]
How much server ram? how many players? On what version did you start the world? 
All it tells me is 
Saving oversized chunk [-12, -7] (1531300 bytes} to external file ./world/DIM-1/entities/c.-12.-7.mcc
Saving oversized chunk [-12, -7] (1531300 bytes} to external file ./world/DIM-1/entities/c.-12.-7.mcc
Saving oversized chunk [-12, -7] (4596918 bytes} to external file ./world/DIM-1/entities/c.-12.-7.mcc

Can you players go back to the overworld and you stop the server and delete the DIM-1 Folder to reset the Nether?
