### ISSUE TITLE
bruh doesnt even open

### ISSUE THREAD

**Issue by beemyu125** [LunaPixelStudios/Better-Minecraft#231]
### Describe the Bug

so whenever i launch it it would crash giving me a code 1 idk whats up

also idk where to find the crash log so I just put in the lastest log thing

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102480113/160734489-ae5a8cbb-70e3-4a08-9cf3-156c1d86f72c.png)
![image](https://user-images.githubusercontent.com/102480113/160734530-85a51251-03e5-4140-9770-763ac740df54.png)
![image](https://user-images.githubusercontent.com/102480113/160734547-f5d03f97-7da5-47c4-a5aa-897d0ce90d42.png)

### Crash Report or Log

https://pastebin.com/icL1TfNM

### Operating System

window 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Can you send me the latest.log in the modpacks logs folder

**Comment by beemyu125** [comment]
> Can you send me the latest.log in the modpacks logs folder

It should be the paste bin thing that i put in

**Comment by HeadHunterShiv** [comment]
@beemyu125 try java 8 v321

**Comment by beemyu125** [comment]
> @beemyu125 try java 8 v321

how do  i get java 8 v321

**Comment by HeadHunterShiv** [comment]
> > @beemyu125 try java 8 v321
> 
> how do i get java 8 v321

https://javadl.oracle.com/webapps/download/AutoDL?BundleId=245807_df5ad55fdd604472a86a45a217032c7d

**Comment by HeadHunterShiv** [comment]
> > @beemyu125 try java 8 v321
> 
> how do i get java 8 v321

https://www.oracle.com/java/technologies/downloads/#java8
select your operating system and install. After that restart your pc and try launching it
