### ISSUE TITLE
Bisect Server Crashing (1.18.2 V2 FABRIC / CurseForge / BisectHosting)

### ISSUE THREAD

**Issue by Zinical** [LunaPixelStudios/Better-Minecraft#232]
### Describe the Bug

The first few days of the server were totally fine, but as of yesterday one of our members would join the server and immediately be disconnected. It happened to myself for a bit and the BisectHosting staff initially configured the Charm mod and it worked for awhile?

As of today the issue returned and now only one person can be on the server at a time, but usually will be forcefully disconnected within a few seconds. If another person tries to join them, both are disconnected and the server restarts. 

The BisectHosting staff also disabled the Illager Expansion mod on our server thinking it was the issue, but that did literally nothing.

Our server is 6 GB of RAM, with enough slots for 12 players, but we usually have a max of 5-6 playing at one time. 

I took our most recent crash report from the server (which for whatever reason says 3/31? But it was 2 AM on 3/30) and ripped the loading info from the server console just now as the second crash log. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Zinical/874bc7878922f952a8bebd7c3414b5ef

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft [FABRIC] v2

### Optifine

No

### Other Mods

none

**Comment by Zinical** [comment]
Didn't leave any reproduction steps as it's seemingly random?

**Comment by SharkieTV** [comment]
v3 has been released lmk if that helps fix it

**Comment by Zinical** [comment]
Unfortunately no, unless I'm just dumb (which I may be). The server is currently crashing before even fully loading. No clue what the issue is on this one.

This is a link to my newest console info! v

PS: My friends love you for being so fast and we now worship you. Thank you for your help! :)

https://gist.github.com/Zinical/7c5386ef2c0c504449deda9ef2f3e1b4

**Comment by HeadHunterShiv** [comment]
> Unfortunately no, unless I'm just dumb (which I may be). The server is currently crashing before even fully loading. No clue what the issue is on this one.
> 
> This is a link to my newest console info! v
> 
> PS: My friends love you for being so fast and we now worship you. Thank you for your help! :)
> 
> https://gist.github.com/Zinical/7c5386ef2c0c504449deda9ef2f3e1b4

Hello there, what you can try is downloading the world and launching it like a singleplayer world to see if it is not crashed. If it isn't then try reinstalling and then pasting the world again there.

**Comment by SharkieTV** [comment]
Try this and see if it works
https://streamable.com/sgsysp
