### ISSUE TITLE
v16.5 won't launch

### ISSUE THREAD

**Issue by moket79** [LunaPixelStudios/Better-Minecraft#234]
### Describe the Bug

every time i try to launche the game with the launcher from curseforge (Better minecraft 1.18.1 v16.5) i have the same issue

currently the operating system is not configured to run this application
the openjdk is marked as interrupted int the task manager
it returns error code 1 on the launcher

i tried to reinstall java, curseforge, the modpack... nothing changes
i also add some memory to the game

### Reproduction Steps

1.install the modpack
2.launch it
3.click play the game
...

### Operating System

windows 10 pro

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16.5

### Optifine

No

### Other Mods

no

**Comment by SharkieTV** [comment]
need a latest.log to help

**Comment by moket79** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8398879/latest.log)

**Comment by moket79** [comment]
i solved the issue by uninstalling microsoft office with the microsoft application found here https://support.microsoft.com/fr-fr/office/d%C3%A9sinstaller-office-d-un-pc-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8
