### ISSUE TITLE
Quark mod causing either Minecraft to not load or causing chests to break (Forge)

### ISSUE THREAD

**Issue by catsmic** [LunaPixelStudios/Better-Minecraft#235]
The Quark mod, as of today, is causing Minecraft to both not load properly (receiving the "mod loading error") or, if I can get into my current world, causing normal chests created both before and after updating to Beta v.20 to not load in properly. By this I mean that any chests in my world that I created before today are taking a long time to show up in game, and when they do, large chests aren't connected, and all of those chests have lost all items within them. This does not seem to have affected chests that have spawned within structures, such as dungeons, villager houses, mineshafts, etc. It also is not affecting any chests that I have created today, even upon saving and quitting the game and then reloading.
Below are the latest.log and the crash report from the mod not loading the first time
[crash-2022-03-31_13.47.43-fml.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8392838/crash-2022-03-31_13.47.43-fml.txt)
[2022-03-31-1.log.gz](https://github.com/LunaPixelStudios/Better-Minecraft/files/8392859/2022-03-31-1.log.gz)

**Comment by SharkieTV** [comment]
Did you skip many updates and updated to v20? How many times does Quark not loading happen?
