### ISSUE TITLE
Server and single player worlds freezing/lagging out?

### ISSUE THREAD

**Issue by SnoweeSznn** [LunaPixelStudios/Better-Minecraft#236]
### Describe the Bug

Not sure what's going on but I have a Fabric server with 4 or so other friends on it and while out exploring and generating chunks the server sometimes just freezes, not loading chunks and essentially crashing the world forcing me to restart the server, at first we figured out it was a certain area that caused the issue so we explored about ~2000 blocks in the other direction before it eventually did the same thing, i looked on forums and some people said to delete the "BetterEnd" mod but i couldn't find it in the modpack, some said to delete the "magnesium" mod but again no results so i guessed those were in the forge modpack, then both one of my friends and i decided to create brand new singleplayer worlds and try to see if we ran into the same issue on them, I found it while loading overworld chunks about a minute into my search, while he found it while running around in the nether for about 5 minutes, i also tried the "bumblezone" datapack fix but my level.dat doesn't have anything named "bumblezone" in the dimensions folder under world gen settings and the server doesn't crash on the hosts end so i cant grab a crash report so I'm currently at a loss for what to do and I'm hoping I could get some help from anyone? I know this is long winded but I just wanted to provide as much information as possible.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

attaching a video showing what the issue is since this probably helps more than my explanation, what happens at the end happens across the server so its not like one person is just lagging
https://streamable.com/rr5krh

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMC V3

### Optifine

No

**Comment by SharkieTV** [comment]
Need the latest.log in the logs folder after the crash too see whats wrong

**Comment by SnoweeSznn** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8400523/latest.log)
this is the latest.log, the server host is https://mc.bloom.host

**Comment by SnoweeSznn** [comment]
> Need the latest.log in the logs folder after the crash too see whats wrong and whos the server host?

[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8400529/latest.log)
grabbed the latest.log, the server host is https://mc.bloom.host

**Comment by JerichoHasFun** [comment]
I am having the same issue but on a single player world. I was doing absolutely fine until I started exploring north of my spawn and started crashing. The problem with me though is I have gotten too close to what ever is crashing the world that if I even load the game then I can't do anything. Some odd things are that the single player world can't exit without task manager but it is still responding. The logs and video are attached below. This is the latest version of the modpack currently available v3 of fabric.
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8401958/latest.log)
https://streamable.com/bu9aag

**Comment by SharkieTV** [comment]
How much ram have you both allocated? I am unable to reproduce this issue, does this happen every time you make a world, send me a seed I can use to see if I get the issue.

**Comment by DcBD** [comment]
I have the same issue with my world, also rim running on 8gb out of 16gb ram.

To reproduce the "crash" you need to go and create a new world:
Seed: `102039`
And teleport to this place: `/tp 58 142 938`
I just stood up in one place and threw bread to see if it's crashed yet. (It takes like 30seconds to get the crash)

I'm guessing it could be some kind of entity spawning and causing the game freeze.

**Comment by DcBD** [comment]
Did some digging and it looks like this mod `unstructured-0.3.1+1.18.2` is crashing the game.

Checked the updated version [unstructured-0.3.2+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/unstructured/files/3729844)  and it also freezes the game.

@SharkieTV

**Comment by Darkovian** [comment]
Also having this issue- player was out generating new chunks looking for a specific biome (black forest, iirc), now the server crashes each time they start back in a specific direction. If they teleport away/etc. it does not crash. Doesn't crash right away though, essentially stops responding and then considers itself crashes after ~200 seconds or so.

Server is on LunaPixel, 8gb ram. I've attached three crash logs, each seem to be caused by this issue. Crashed in the same way each time. Hope this info helps!

[crash-2022-04-02_14.09.01-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8403247/crash-2022-04-02_14.09.01-server.txt)

[crash-2022-04-02_14.15.16-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8403248/crash-2022-04-02_14.15.16-server.txt)

[crash-2022-04-02_14.20.59-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8403249/crash-2022-04-02_14.20.59-server.txt)

**Comment by SnoweeSznn** [comment]
i have 8 gb allocated for the server with 115GB of storage dedicated for the server as well, not sure what the issue is still, but like people mentioned above it's probably a entity/structure/biome issue, I couldn't find a fix at all, so i simply downgraded back to the V2 update and it works fine

**Comment by SharkieTV** [comment]
Ill be removing Unstructured in the next version, it is also possible even if removing the mod it wont cause other chunks to crash but the ones that is crashing might stay their
