### ISSUE TITLE
Game does not load

### ISSUE THREAD

**Issue by SirKrunk** [LunaPixelStudios/Better-Minecraft#24]
Game Version: 1.18.1
Better MC Version: v11.5
Unmodified
Crash report: https://pastebin.com/1M6VXNs4

**Comment by SharkieTV** [comment]
It doesn't seem like you installed it right cause its not using the correct forge version it ships with. Reinstall it.

**Comment by SharkieTV** [comment]
Anyways v12 came out and should fix the issue but you need to make a new profile to get the correct forge version.
https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/files/3603107

**Comment by SirKrunk** [comment]
ok
