### ISSUE TITLE
1.18.2 - better minecraft forge - v4 - Some tags for recipes are incorrect

### ISSUE THREAD

**Issue by ProvoGo** [LunaPixelStudios/Better-Minecraft#240]
### Describe the Bug

  some item tags are wrong resulting in recipes like this
![2022-04-02_14 55 22](https://user-images.githubusercontent.com/36768970/161384726-3d9feee4-5f25-4458-816c-209482ca7e3f.png)
 
Crafting recipes affected:

Arch Illager Boots
Arch Illager Robe
Arch Illager Crown
Hunting Post
Forestry Bench
Nature's Compass
Boric Campfire
Cryptic Campfire
Soul Campfire
Campfire
Fire Brazier
Diamond Magnum Torch
Emerald Magnum Torch
Amethyst Magnum Torch
Smoker
Azalea Planks

Furnace recipes affected:

Charcoal
Voidsteel Nugget

Sawmill recipes affected:

Bowl
Ladder
Stick

### Reproduction Steps

1. Try to craft a forestry bench
2. Unable to craft it with logs

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v4

### Optifine

No

**Comment by SharkieTV** [comment]
Uploading a fix soon, the Mod Ecologics had an update causing this issue.

**Comment by ProvoGo** [comment]
👍
