### ISSUE TITLE
bug that wont drop items out of inventory

### ISSUE THREAD

**Issue by Crossbowninja** [LunaPixelStudios/Better-Minecraft#241]
### Describe the Bug

When I am playing i go to drop a item that i dont want and the item disappears like it was never there.  then out of no where the item reappears back into my inventory I have to exit out the game multiple times to get it to where it doesnt do that anymore but it only stays that way for a short period of time before it start happening again.  

### Reproduction Steps

1. craft item 
2. drop item from inventory
3. item returns back to invetory without it hitting the ground
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft 1.18.2 V3

### Optifine

No

**Comment by fairyboy21** [comment]
there should be a trash slot next to the right side of inventory or sometime trash can if not then make a new world idk if they added trashslot in modpack so yeah

**Comment by SharkieTV** [comment]
Need a video of this please
