### ISSUE TITLE
No quest book at all on FABRIC 1.18.2

### ISSUE THREAD

**Issue by FrostyRezz** [LunaPixelStudios/Better-Minecraft#242]
### Describe the Bug

when i join the world i dont have a quest book at all and no where to get one.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1.18.2

### Optifine

No

### Other Mods

Better Minecraft

**Comment by fairyboy21** [comment]
the quest book can be found on top left when you open up your inventory

**Comment by SharkieTV** [comment]
if you updated you dont get one, if you started a new world on v4 and above you will spawn with it and it can be found top left in inventory, please ask these general questions in the Discord
