### ISSUE TITLE
unknow crash better minecraft forge 1.18.2

### ISSUE THREAD

**Issue by fairyboy21** [LunaPixelStudios/Better-Minecraft#243]
### Describe the Bug

idk why it crashing so yeah can you tell me the reason why 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/PKcKq1AJ

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

4.5

### Optifine

No

**Comment by SharkieTV** [comment]
seems like an issue with Multi MC try another launcher

**Comment by Ozzi-Hero** [comment]
You need Java 17. Not Java 18.
