### ISSUE TITLE
TP doesn't work?

### ISSUE THREAD

**Issue by Bapelzien** [LunaPixelStudios/Better-Minecraft#244]
### Describe the Bug

I can't TP to my set waypoint, should it be like that or what's wrong here?
Does TP only work while in creative maybe?

Kind Regards

### Reproduction Steps

1.
2.
3.
...

### Operating System

W10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Fabric 0.13.3

### Optifine

No

**Comment by SharkieTV** [comment]
TP only works if you are Operator of the server aka you have all the perms. TP is not meant for normal survival.
