### ISSUE TITLE
getting crashes with exit code 1

### ISSUE THREAD

**Issue by zeliotgame** [LunaPixelStudios/Better-Minecraft#245]
after i made mine the 1.18.2 it keeps crashing my game when i try to launch it saying exit code 1 and i see now where on how to fix that

**Comment by SharkieTV** [comment]
use the template and give me info I can help with

**Comment by Kitaki99** [comment]
Hello i have a similar problem with that. I'm in Version 1.18.2 of better Mc Forge and when i press play on the Mc launcher it crushes and shows these two messages.
Do i sent my templates too? And if so, how do i do that? I'm completely new to this.
![Screenshot_1](https://user-images.githubusercontent.com/104082646/164250918-1511943f-fb6d-4dc0-b53e-ccfd4379716d.png)
![Screenshot_2](https://user-images.githubusercontent.com/104082646/164251038-50cf7644-d778-4fef-9e92-2b29c8ff9597.png)
