### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SharkyBooMan** [LunaPixelStudios/Better-Minecraft#246]
### Describe the Bug

Everytime that i tame a wolf, after some time, if they're not sitting down, they would just dissapear

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

**Comment by SharkieTV** [comment]
I am unable to reproduce this issue, what version did you make the world and did you update the Modpack?

**Comment by SharkyBooMan** [comment]
The modpack is version 11 and i made the world in the verson 1.18.2
What do you mean by update the pack?

**Comment by SharkieTV** [comment]
their is not version 11? do you mean 1.18.1 v11? if so your modpack is quite outdated and probably best to update but since youll be skipping so many versions its quite uncertain what issues it can cause.
