### ISSUE TITLE
Farmer's Delight - Rich soildoes not allow plants on it

### ISSUE THREAD

**Issue by Today20092** [LunaPixelStudios/Better-Minecraft#247]
### Describe the Bug

The mod, Farmer’s Delight, allows you to create compost which then turns into rich soil which is tillable and plantable, the rich soil increases the speed in which plants grow. 
In the mod pack the rich soil is broken and does not allow you to place any plants on it.

### Reproduction Steps

1. Create compost
2. Till Rich Soil
3. Try to place wheat seeds, potato, etc, on it.

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1.18.1 v18 HF

### Optifine

No

**Comment by SharkieTV** [comment]
1.18.1 is no longer being worked on and is replaced by 1.18.2
