### ISSUE TITLE
Error loading Mods

### ISSUE THREAD

**Issue by MeowingInsanely** [LunaPixelStudios/Better-Minecraft#248]
Version: Better Minecraft [FORGE] v56
Minecraft Loader: Curseforge

Issue Description: Konkrete, Architectury, Better Advancements are "loading incorrectly".

Error Code:
`java.lang.RuntimeException: Error computing listener list for net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Pre`

Crash Log: https://pastebin.com/XuY0zNha

Attempts to fix:
- Deleting the BM modpack Instance folder & reinstalling the modpack.*
- Repairing the modpack profile through curseforge options.*

*Both works temporarily, Issue reappears after closing minecraft & starting it again.

**Comment by SharkieTV** [comment]
Not much I can do with Mod Loading errors as they rarely occur and are fixed by relaunching. So after closing minecraft & starting it again did you try opening it a few times or just once?

**Comment by MeowingInsanely** [comment]
> Not much I can do with Mod Loading errors as they rarely occur and are fixed by relaunching. So after closing minecraft & starting it again did you try opening it a few times or just once?

Yes, I did try opening it a few times. (Because I kept forgetting to hit "repair" on the profile / hoping that I would't needing to do so)

**Comment by SharkieTV** [comment]
Well the best I can offer is removing the mods you are having issues with or try another launcher.
