### ISSUE TITLE
Mod doesnt work properly 

### ISSUE THREAD

**Issue by Jodsalz66** [LunaPixelStudios/Better-Minecraft#249]
### Describe the Bug

For the first 15 minutes, everything works fine. After that I can't open chests, I can't eat and whenever I break a block it doesn't drop anything. I also can't change my game mode. I tried repairing the game files and it seemed to have fixed it but after 15 minutes the same things happened... 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FABRIC] v3.zip

### Optifine

No

**Comment by SharkieTV** [comment]
Remove Unstructured Mod helped, if not create a new world with it removed and it should work fine.
