### ISSUE TITLE
minimap problem

### ISSUE THREAD

**Issue by Gabuwuw0210** [LunaPixelStudios/Better-Minecraft#25]
### Describe the Bug

When updating to the new version 11.5, a second minimap appeared in the upper right corner of the screen, in addition to not knowing how to remove it, the worldmap is completely black regardless of the configuration that you change.
I don't know if it's just my problem but the FTB Chunks mod doesn't work for me

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![unknown](https://user-images.githubusercontent.com/97574076/149053980-cc7a07d7-695a-42bf-aaab-9d28b992f6de.png)
![unknown](https://user-images.githubusercontent.com/97574076/149053988-5d07bae4-3606-4ce5-9376-f2b486cdf821.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
It seems like you aren't using the configs the Modpack is shipped with, please reinstall the modpack. I'm not sure why the FTB map is currently blank but that will be fixed later. Please reinstall the Modpack.

**Comment by SharkieTV** [comment]
v12 just came out and should fix your issues, please make sure to update to a new profile and drag your save over.
https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/files/3603107
