### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by SalmanDX** [LunaPixelStudios/Better-Minecraft#251]
### Describe the Bug

When I activate a new server, I get an error and a code appears, but I do not know what is the solution to this problem

### Screenshots and Videos

![Screenshot_124](https://user-images.githubusercontent.com/56300337/161978966-78b6a7b0-16c5-4266-a94b-c3fe7d3f0f3e.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Uninstall java 17
