### ISSUE TITLE
Chunk generating error/crash

### ISSUE THREAD

**Issue by Nuudella** [LunaPixelStudios/Better-Minecraft#254]
### Describe the Bug

Hi, yesterday i installed Better Minecraft (Fabric) v4 on MultiMC and started playing, i played for like 2 hours, walked to a location where i wanted to build (everything was fine, no error, crashs or anything like that) and then i went off to sleep. Today i wanted to continue playing but after like 1-3minutes of playing i get a connection lost message and the game kicks me in the Main Menu or the game closes completely with the error 
"Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / byg:firecracker_shrubland]=net.minecraft.class_1959@ef3f316}]"

Seed: -3875439633326674672

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/x8yJhqU7

### Operating System

7

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

1.18.2 v4

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
this will be fixed in the next version but if you want you can fix it by removing the mod ecologics and then replacing it with the latest updated one that fixes it

**Comment by Nuudella** [comment]
ok, ty
