### ISSUE TITLE
Game crash upon loading modpack Fabric 1.18.2

### ISSUE THREAD

**Issue by leonewashere** [LunaPixelStudios/Better-Minecraft#255]
### Describe the Bug

Using Curseforge, the game crashes before it opens. This happens without extra mods or resourcepacks and without optifine.
Better Minecraft FABRIC 1.18.2 v4

The game crashed whilst initializing game Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_312 failed Exit Code: -1

### Reproduction Steps

1. Click 'Play' on Better Minecraft instance on Curseforge app
2. Click 'Play' on the Minecraft launcher
3. Crash

### Screenshots and Videos

![Picture1](https://user-images.githubusercontent.com/91973919/162574833-0e33f88d-8113-4960-9ecb-dee50ee8d717.png)

### Crash Report or Log

https://pastebin.com/MZYLyUeS

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

### Other Mods

N/A

**Comment by SharkieTV** [comment]
so you say its without mods but you added okzoomer? which is the cause of the crash so remove that.
