### ISSUE TITLE
some recipes doesn't show in the crafting table

### ISSUE THREAD

**Issue by CrocodileDZ** [LunaPixelStudios/Better-Minecraft#258]
### Describe the Bug

recipes like the stone tools doesn't show in my crafting table i have to craft them manually

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10 

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

I used Optifine

### Other Mods

i removed the 2 magnesium mods and the dynamic lights to enable my shaders

**Comment by CrocodileDZ** [comment]
update i made a clean reinstall to the game and the mod without the optifine and still same issue

**Comment by SharkieTV** [comment]
Set "Automatic Recipe Unlock" to true in Quark config
