### ISSUE TITLE
vanilla fish buckets cannot be used

### ISSUE THREAD

**Issue by omggg218** [LunaPixelStudios/Better-Minecraft#260]
### Describe the Bug

Happens in both server and sp, none of the buckets of aquatic mob from vanilla mc can be placed down, this includes bucket of cod, bucket of salmon, bucket of pufferfish, bucket of tropical fish and bucket of axolotl. Have tested with natually spawned mobs, spawn egg mobs and buckets from creative mode.

### Reproduction Steps

1. Use water bucket on aquatic mobs/get bucket of aquatic mobs
2. Use bucket of aquatic mobs
3.
4.
...

### Crash Report or Log

https://gist.github.com/omggg218/0c08c8ef2783221c1a7e3edc1d892fb5

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V3

### Optifine

No

**Comment by SharkieTV** [comment]
Update the Modpack to latest version
