### ISSUE TITLE
Better Minecraft 1.18.2 V5

### ISSUE THREAD

**Issue by Tarkore** [LunaPixelStudios/Better-Minecraft#261]
### Describe the Bug

Broken citadel from the cataclysm mod spawned in the overworld

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-04-11_18 52 22](https://user-images.githubusercontent.com/103450790/162801178-bdaba0f6-19f3-4b11-8061-4c57f318f764.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

### Other Mods

none

**Comment by SharkieTV** [comment]
Thanks, I reported it to the Mod Devs
