### ISSUE TITLE
[1.18.2 Fabric] Chipped Tables not working for client

### ISSUE THREAD

**Issue by DcMbse** [LunaPixelStudios/Better-Minecraft#262]
Chipped Workbenches do not show up any chipped recipes when inserting items. So no crafting of chipped blocks possible.
Tested on dedicated server with v5 and the included chipped version.
Also reported the issue to the mod author of "chipped".
https://github.com/Toadstool-Studios/Chipped/issues/122

**Comment by SharkieTV** [comment]
Will be fixed in next version
