### ISSUE TITLE
Create moving blocks available

### ISSUE THREAD

**Issue by MagicMancake** [LunaPixelStudios/Better-Minecraft#263]
### Describe the Bug

Any block in the Create mod that is capable of movement is completely invisible when attempting to view

### Reproduction Steps

1.Place a Create block such as a Water Wheel or Shaft
2.View

### Screenshots and Videos

![CreateBug](https://user-images.githubusercontent.com/103480617/162884341-887924e5-e2b1-400c-829a-9cb0bc274df5.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] v5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Could you see if updating the Rubidium Mod fixes it?

**Comment by MagicMancake** [comment]
There is no Rubidium mod in this pack, so I don't see how that could tackle this issue

**Comment by MagicMancake** [comment]
For reference this is on a server and it is a consistent issues for all players on the server so I can attempt to see how it works in Single Player

**Comment by SharkieTV** [comment]
Yes I think this is happening client side and Rubidium could be the cause

**Comment by MagicMancake** [comment]
Checked Rubidium, it is updated to the newest version already on the modpack, which the server runs on, it's also updated client side so I doubt its that.

**Comment by SharkieTV** [comment]
Rubidium is not updated to the latest for PLUS and its not on the server so not sure why you are saying that.
PLUS uses rubidium-0.5.1a.jar not latest rubidium-0.5.2a.jar.
I just tested myself and the new version does not fix it so I will do more testing and hopefully fix it in the new update

**Comment by SharkieTV** [comment]
It seems Oculus is the cause, remove that mod if you want to use create for now and its been reported, waiting for a update to fix it.
https://github.com/Asek3/Oculus/issues/43
