### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Qblolz** [LunaPixelStudios/Better-Minecraft#264]
### Describe the Bug

Crash on generate chunk in end
seed: 7391629486
coord: 518 106 -10359

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/0SBrpjdg

### Operating System

Ubuntu 20.04

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v16.5

### Optifine

No

**Comment by SharkieTV** [comment]
1.18.1 is now out of date and not being worked on, maybe see if updating the BetterEnd mod help fix it
