### ISSUE TITLE
Can't enter my world

### ISSUE THREAD

**Issue by CalualaMic** [LunaPixelStudios/Better-Minecraft#266]
So i just updated to 1.18.2 from the last version of 1.18.1 (v20) and when I tryed to enter my world it would say that there's an error with the datapacks and I had 2 choices: 1. safe mode 2. back to title screnn and fix it mannualy. I tried safe mode but it wouldn't work. So what can I do? Should I wait more so I can upgrade the world?

**Comment by SharkieTV** [comment]
Try this https://github.com/LunaPixelStudios/Better-Minecraft/issues/237

**Comment by ShadowSlayerFX1** [comment]
video is not available
