### ISSUE TITLE
Cant summon the wither in v6

### ISSUE THREAD

**Issue by ProvoGo** [LunaPixelStudios/Better-Minecraft#267]
### Describe the Bug

Cant summon the wither in v6, you could summon it just fine in v5

### Reproduction Steps

1. Build the wither summon thing
2. Nothing happens

### Screenshots and Videos

![Uploading 2022-04-13_20.32.51.png…]()

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v6

### Optifine

No

**Comment by SharkieTV** [comment]
The mod called Bygone Nether is causing the issue, either remove it or wait for a modpack update with the mod fix

**Comment by ProvoGo** [comment]
as it turns out its not actually bugged, spawn method is just changed by Bygone Nether from soul sand to soul stone
