### ISSUE TITLE
Better Minecraft FABRIC - 1.18.2 - V5

### ISSUE THREAD

**Issue by xPown3d** [LunaPixelStudios/Better-Minecraft#268]
My bees don't make any babys.

Whenever i breed my bees, they don't make any babys, i don't get any XP.

Should have something wrong.

**Comment by SharkieTV** [comment]
The mod called Immersive Weathering is causing the Issue, reported it to the Dev will see when they fix it

**Comment by jlangholzj** [comment]
For anyone following, the bug submittal on Immersive Weathering is [here](https://github.com/AstralOrdana/Immersive-Weathering/issues/47) and appears fixed in TBD upcoming revision.
