### ISSUE TITLE
Unable to place crops on Lush Farmland

### ISSUE THREAD

**Issue by Chrispytoast** [LunaPixelStudios/Better-Minecraft#269]
### Describe the Bug

Lush Farmland is created from tilling the Lush dirt from the "Oh the Biomes You'll Go" mod. It looks like it would behave like normal farmland but you are unable to place any crops on it. Not normal wheat seeds, and not anything from "Croptopia"

### Reproduction Steps

1. Find / place `Lush Dirt`
2. Till the `Lush Dirt` with a hoe. This creates `Lush Farmland`
3. Try to place crops on `Lush Farmland`

**Observed Behavior:**
Crops are unable to be placed on `Lush Farmland`

**Expected Behavior:**
Crops are placed on `Lush Farmland` and grow normally

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft V5

### Optifine

No

**Comment by SharkieTV** [comment]
Croptopia is no longer in the Modpack and replaced by Farmers Delight which works

**Comment by Chrispytoast** [comment]
This is not just for Croptopia, this is a problem for all native Minecraft seeds as well. Does the addition of Farmers Delight fix this issue for normal seeds or was this closed prematurely due to the assumption that Croptopia is no longer there?
