### ISSUE TITLE
[Suggestion] Inventory Sorting mod

### ISSUE THREAD

**Issue by ShaneCourtrille** [LunaPixelStudios/Better-Minecraft#27]
### Describe the Bug

I checked the key binding and I don't see anything related to sorting so I'm wondering if there is already inventory sorting or if one could be added?  Or are you waiting for one to appear that supports both Forge & Fabric?  

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

9

### Optifine

No

**Comment by SharkieTV** [comment]
Forge has one and one will be added to fabric in next version
