### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by lotrg54** [LunaPixelStudios/Better-Minecraft#270]
### Describe the Bug

When I try to launch the game it crashes after luma pixel shows up

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://paste.ee/p/XFkEq

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v6

### Optifine

No

**Comment by SharkieTV** [comment]
Did you try to run it again and how much ram did you allocate?

**Comment by lotrg54** [comment]
> Did you try to run it again and how much ram did you allocate?

3570 mb

**Comment by SharkieTV** [comment]
Not enough ram allocated, atleast have 6-8gb allocated and try again
