### ISSUE TITLE
CANT GET RID OF EFFECTS AT ALL AFTER EVERY ATTEMP 

### ISSUE THREAD

**Issue by dhkperk666** [LunaPixelStudios/Better-Minecraft#271]
### Describe the Bug

I raided a mansion and went to blow the place up and after doing so it gave me 3 random achievements and then gave me slowness and sickness for 0:03 seconds and i've tried every single possible way to remove this and it wont go away at all this has to be a bug right? it was running on a server that no one else was on at the time and when my friend joined he had it too 

### Reproduction Steps

1.blow up a mansion on the second floor? idk 
2.
3.
...
thats it

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft

### Optifine

No

**Comment by SharkieTV** [comment]
Need the Version of the pack your playing and a screenshot of the mansion

**Comment by dhkperk666** [comment]
For sun reason I went on today and it was gone sorry but it lasted like 7
hours and I was so worried
