### ISSUE TITLE
Better Minecraft - 1.18.2 - FORGE - Black scattered lines 

### ISSUE THREAD

**Issue by ZaedeX** [LunaPixelStudios/Better-Minecraft#274]
### Describe the Bug

Whenever moving about the world or breaking blocks black scattered lines appear on the screen. I have not had this issue in other modpacks before so I do not believe it is my end.

### Reproduction Steps

1.Move
2.Brek blocks
3.Lines
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v6.zip

### Optifine

No

### Other Mods

N/A

**Comment by SharkieTV** [comment]
Hi, I am unable to reproduce this issue, can you provide a screenshot or video of what this is? and what are your video specs?

**Comment by ZaedeX** [comment]
Hi, I will try get a video out to later today if that is alright.

**Comment by ZaedeX** [comment]
https://user-images.githubusercontent.com/88979312/163563787-dd845695-e098-4b37-876b-00b84af26a9f.mp4

**Comment by ZaedeX** [comment]
In this clip you can see the lines appearing on screen as I mine through some stone. Also what specs would like me to give you?

**Comment by ZaedeX** [comment]
Hi, is there any update on what this might be ?

**Comment by SharkieTV** [comment]
I am unable to reproduce this issue, could you provide a F3 screenshot?
