### ISSUE TITLE
Better Minecraft | Fabric |

### ISSUE THREAD

**Issue by TenVerLurior** [LunaPixelStudios/Better-Minecraft#276]
Fighting the bosses of mass destruction crashes my game every single time, can’t even load into it

**Comment by SharkieTV** [comment]
Need the crash log and version of the modpack and minecraft

**Comment by TenVerLurior** [comment]
1.18.2 v13  https://bytebin.lucko.me/fX3JPxxwz3

**Comment by SharkieTV** [comment]
their is no v13 for 1.18.2 so i can only assume you are playing on an outdated 1.18.1 version which you should update to v18
