### ISSUE TITLE
Incomplete set of tags

### ISSUE THREAD

**Issue by Kokodrove** [LunaPixelStudios/Better-Minecraft#277]
### Describe the Bug

Hello, I'm having this bug where I usually start a forge server, whenever a player wants to enter when they have the screen “Loading Terrain...” it appears seconds later the message of "Incomplete set of tags" I've been searching for help.
I'm using Betrer Minecraft 1.16.5 V56

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://paste.ee/p/WEL95

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

### Other Mods

Sophisticated Backpacks
Simple Farming

The issue happens with and without these mods

**Comment by SharkieTV** [comment]
It means your server and client mods dont match, since you modify the pack you might have done something wrong. Reinstall both with no Modifications
