### ISSUE TITLE
Every moving block become invisible (Vanila/Create Blocks)

### ISSUE THREAD

**Issue by Ramazzottt** [LunaPixelStudios/Better-Minecraft#278]
### Describe the Bug

Every Block which moves like a piston or a shaft are invisible but you can see it again if it doesn't move

### Reproduction Steps

1. Reinstalled the modpack
2. Start a World
3. Place a Piston from Vanila and create
4. power the block and ist invisible 

### Screenshots and Videos

https://youtu.be/SrP0SLKgxZU

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v6 [Beta]

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate of https://github.com/LunaPixelStudios/Better-Minecraft/issues/263
