### ISSUE TITLE
Pregen on 1.18.1 @Montruh Cool, also if you are going to play with a lot of friends I recommend running a pregen.

### ISSUE THREAD

**Issue by jusobreira** [LunaPixelStudios/Better-Minecraft#28]
I want to know how can i pregen the world if the mod still on 1.16. Can I use the same mod?
@Montruh Cool, also if you are going to play with a lot of friends I recommend running a pregen.

_Originally posted by @SharkieTV in https://github.com/LunaPixelStudios/Better-Minecraft/issues/17#issuecomment-1008471867_

**Comment by SharkieTV** [comment]
You can try this video https://www.youtube.com/watch?v=UkkIpZSUnr4
