### ISSUE TITLE
Bag Display Bug

### ISSUE THREAD

**Issue by KiritoKing** [LunaPixelStudios/Better-Minecraft#280]
### Describe the Bug

The items you put in the bag will still be shown after you close the bag.

### Reproduction Steps

1. Open the bag
2. Store some items in it
3. Close the bag
...

### Screenshots and Videos

![T89ZC$)``A9 0N ({TIQIHV](https://user-images.githubusercontent.com/19513548/163681976-f20221c4-7fba-4ad5-a676-a43be965c8a3.jpg)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6

### Optifine

No

### Other Mods

CustomSkinLoader

**Comment by SharkieTV** [comment]
Press O or I
