### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by diamondpixel** [LunaPixelStudios/Better-Minecraft#281]
### Describe the Bug

When we enter the Aether dimension the whole server crashes.
 
The Error : "Error executing task on Chunk source main thread executor for the_aether:the_aether net.minecraft.class_148: Feature placement"

### Reproduction Steps

1. Join a server.
2. Go to Aether

### Crash Report or Log

https://pastebin.com/4vQTuW7b

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft [Fabric] v6

### Optifine

No

**Comment by SharkieTV** [comment]
Remove Probably Chests mod
