### ISSUE TITLE
Crash entering aether

### ISSUE THREAD

**Issue by RogueZombieDog** [LunaPixelStudios/Better-Minecraft#282]
### Describe the Bug

Whenever i enter an aether portal it just crashes

### Reproduction Steps

1. load world
2. create aether portal
3. go in
...

### Crash Report or Log

https://pastebin.com/RXJQFwpS

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6

### Optifine

No

**Comment by RogueZombieDog** [comment]
i did some looking and found it it seems to be probably chests causing this issue the aether works fine without it

**Comment by RogueZombieDog** [comment]
the paradise lost devs have just reported this to the probably chests devs so it would probably be best to remove the mod for now? idk

**Comment by SharkieTV** [comment]
Thanks yeah will remove the mod

**Comment by ReillyGregorio** [comment]
I have pushed a fix for this issue. It was a problem with a bound check on my end and the fact that the aether was spawning overworld features which my mod didn't account for.

**Comment by JadedChain** [comment]
Hey i saw you guys had a solution but don't know which mod to remove, can someone help me out?

**Comment by ReillyGregorio** [comment]
Either update the pack which has probably chests removed or download the latest version of probably chests 0.3.1 and replace the version in the mods folder.

**Comment by SharkieTV** [comment]
> Either update the pack which has probably chests removed or download the latest version of probably chests 0.3.1 and replace the version in the mods folder.

@JadedChain

**Comment by RogueZombieDog** [comment]
> 

thanks, also nice that you fixed it so quickly :)
