### ISSUE TITLE
Better Minecraft PLUS [Forge] 1.18.2 - Oculus breaks Create

### ISSUE THREAD

**Issue by Zyratoxx** [LunaPixelStudios/Better-Minecraft#283]
### Describe the Bug

[Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) breaks the [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel) rendering engine which is used by [Create](https://www.curseforge.com/minecraft/mc-mods/create). Removing Oculus should do the trick.

### Reproduction Steps

1. Run the modpack --> create a world...
2. Get a cogwheel (or anything similar) from the "Create" mod
3. Hold "W" for tooltips - There will be a blank page
5. Try to place the cogwheel
6. It will be invisible

Remove / Disable "Oculus" and try again and it will do the trick.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/23664236/163688007-60796755-3495-4939-9c67-ace24b00de91.png)
![image](https://user-images.githubusercontent.com/23664236/163688022-756df0ff-2fe7-45c7-9534-ad62d5b6ac98.png)
What it looks like when running Oculus

> -----------------------------

![image](https://user-images.githubusercontent.com/23664236/163688201-6d5875c5-4ce3-4a5f-9d63-b1b17cd52167.png)
![image](https://user-images.githubusercontent.com/23664236/163688207-2d2a387f-6ad3-4da2-acee-79f4d8d52b48.png)
What it looks like after removing Oculus

### Crash Report or Log

-

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] v6 (and probably v5 as well)

### Optifine

No

### Other Mods

-

**Comment by SharkieTV** [comment]
Duplicate #263
