### ISSUE TITLE
Crashes after starting a raid

### ISSUE THREAD

**Issue by ClassfiedFliqqzy** [LunaPixelStudios/Better-Minecraft#284]
### Describe the Bug

Hello. I ran into the following problem - not so long ago I accidentally stumbled upon a patrol of pillagers. After killing them, I received a debuff of a Bad Omen, there was a village made with my own hands next to me - when I approached it, the world closed down in an emergency without the opportunity to enter. The logs indicate that the reason is just in the raids.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/q7UmG2e2

### Operating System

Windows 10 Home (21H1)

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

(I dont know what is this)

### Optifine

No

### Other Mods

I added the following mods to the build to optimize and add some small content: ferritecore-4.2.0-fabric-1.18.2, FpsReducer2-fabric-1.18.2-2.0, Decorative-Blocks-fabric-1.18.2-2.1.0, Wandering-Trapper-fabric-1.18.2-1.2.0, weaponmaster-1-18-x-fabric and sodium-fabric-mc1.18.2-0.4.1build.15.

**Comment by SharkieTV** [comment]
Your Modpack version is outdated and was fixed many versions ago so either update that or update illager expansion. Also not sure why your adding like sodium and ferritecore when they are already in the pack
