### ISSUE TITLE
Nether Structures From Repurposed Structures Spawning In BYG's End Biomes In Better Mc Plus

### ISSUE THREAD

**Issue by GoatRammaHamma70** [LunaPixelStudios/Better-Minecraft#285]
### Describe the Bug

When flying around in the end in creative, many nether wastes mineshafts, temples, pyramids, outposts and other structures from repurposed structures spawn in BYG's end biomes.

### Reproduction Steps

1. Go to the end
2. Go to outer islands
3. Locate any of repurposed structure's nether wastes structures (ex: nether pyramid)
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/94216350/163690071-1bc34003-0474-4d1f-bb87-3b1068cf77d2.png)
nether mineshaft
![image](https://user-images.githubusercontent.com/94216350/163689915-3ef03ca5-eecb-495f-9c39-8cc732234061.png)
nether outpost
![image](https://user-images.githubusercontent.com/94216350/163689928-1b1d80d8-94a4-46f0-a90d-44b738b79c6a.png)
nether temple
![image](https://user-images.githubusercontent.com/94216350/163689935-8acfa502-6a49-455a-8b91-f96c11bcf800.png)
nether pyramid. these are a few examples, since there are a lot more that also generate.

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMCP V6

### Optifine

No

### Other Mods

Music Duration Reducer, Dragon Mounts Legacy

**Comment by SharkieTV** [comment]
Issue has been reported, have to wait for a Mod update to fix.
https://github.com/TelepathicGrunt/RepurposedStructures/issues/198

**Comment by TelepathicGrunt** [comment]
Aether? Last time I checked, none of my structures spawned in aether. Which aether mod are you using? I’ll look again and see what tags they put their biomes into

**Comment by SharkieTV** [comment]
> Aether? Last time I checked, none of my structures spawned in aether. Which aether mod are you using? I’ll look again and see what tags they put their biomes into

Sorry didn't see this but its not just your mods honestly its a lot of mods seems to spawn in the Aether. Its Paradise Lost the latest 1.18.2 for fabric version of their mod

**Comment by TelepathicGrunt** [comment]
Latest byg is said to have fixed their biome tagging so rs nether structures no longer spawn in the end. Please give it a try and let me know if the issue persists.

**Comment by GoatRammaHamma70** [comment]
works great, the issue is gone.
