### ISSUE TITLE
nether not generating like half the biomes?(better minecraft forge 1.16.5)

### ISSUE THREAD

**Issue by RichPrune** [LunaPixelStudios/Better-Minecraft#286]
### Describe the Bug

so I started a new survival world and used the nature compass to find my favorite biome, the basalt delta. The first time I used it it said one was about 2200 blocks away. But, when i died on a later trip to the nether i left the world immediately to try and load the save before i died and it corrupted the nether chunks around me so i had to reset it(remove the dim-1 folder). I did and when i came back the spawn area was completely the same (just uncorrupted) but i used the compasss and it said "not found" to basalt delta. It also said not found for warped/crimson forest and some better nether biomes. I also went into another creative test world and it still didnt work?? It had the same issue as the survival world, and after further exploring in both worlds it seems to overgenerate (generate biomes way too frequently) much of the byg biomes, especially the warp-crimson big forest, the wither woods, the magma lands and the bone reef for some reason. Like seriously it felt like these four biomes were all that generated for thousands and thousands of blocks of flying in the creative world. And they're my least favorite lmao. Resetting the nether again didnt change this bug either; it just reloaded all the chunks to how they were when i spawned in. I tested for way too long and found out the only way to sorta reset the generation was to remove all the nether mods and try and load the game and then try and load the nether (it doesnt let you into the nether portal)and then you restart the game with the mods on and ONLY THEN it seems to temporarily reset the generation; as in bring back the basalt delta showing up on the compass, but the glitch then returns after a while??? as in it disappears from the compass. this is the strangest glitch ive ever encountered; i dont expect anyone to actually understand whats causing it lol but is there a way i could import a nether from a world that actually works into my survival world? I just wanna play the game man

### Reproduction Steps

1.download better minecraft forge 1.16.5
2.generate the nether
3.It always generates like the same few biomes at spawn(the brimstone one, the big crimson-warp forest, the bone reef, etc.) but it initially says on the nature compass basalt deltas are always about 2000 blocks away; idk why its so specific but i tested like 5 worlds and they all had this extremely similar generation)
4.idk exactly when it happens but at some point the generation of the nether bugs. Its super hard to pinpoint and changing some aspects of its generation dont seem to change it?(e.g. removing byg temporarily)
5.cry to sleep
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

I used Optifine

### Other Mods

tinkers construct, create, mutant beasts, chisel, morpheus,findme, ht tree chop, loot beam, itemphysic lite,optifine (as far as im aware none of these change the nether generation except tinkers construct, but after a lot of testing i can safely say it isnt the cause of it. Removing it doesnt remove the glitch for example when i reset the nether generation)

**Comment by SharkieTV** [comment]
This has been reported to the mod dev. https://github.com/Someone-Else-Was-Taken/BetterNether-Reforged/issues/53
only fix is removing better nether mod

**Comment by RichPrune** [comment]
wow. thank you, ive been looking everywhere to solve this and omg this has been a problem for too long lol. my only question is why wasnt this mod removed from the pack if it breaks nether generation? Also I deleted my nethers in my test worlds and now theyre just... not letting me in the nether, and in one that i was already in the nether for it just generated the vanilla biomes. Idk how to reset it
