### ISSUE TITLE
I want to use Optifine but it keep crashing

### ISSUE THREAD

**Issue by kenzih95** [LunaPixelStudios/Better-Minecraft#287]
### Describe the Bug

Game crashed after press Play button. I tried delete all mods and it work well with Optifine installed.
Thanks for reading.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc 

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
This is not a github issue and can be asked in the discord. Remove dynamic lights rubidium and oculus
