### ISSUE TITLE
Broken world because of sign

### ISSUE THREAD

**Issue by Jaydenb361** [LunaPixelStudios/Better-Minecraft#288]
### Describe the Bug

When I placed a "flowered azraela sign" (not sure if thats how you spell azraela) it completely crashed my game and when I attempted to load back into my world it showed me a frozen screen of the sign placed in my house and then crashed again after a few seconds. I tried loading in and spamming destory to try and get rid of the sign before the freeze and/or crash and it worked but I wanted to make sure you were aware of the issue anyways. Thanks for all your hard work.

### Reproduction Steps

1. Place a flowered azraela sign
2.
3.
...

### Operating System

Windows 10 home

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft [FABRIC] - 1.18.2

### Optifine

No

**Comment by SharkieTV** [comment]
Can i please get the crash report

**Comment by CityGrump** [comment]
same issue here on 2 clients, world broken atm... trying to force remove sign with ( /execute @e ~ ~ ~ setblock x y z air)

[crash-2022-04-18_15.06.28-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506218/crash-2022-04-18_15.06.28-client.txt)
[crash-2022-04-18_15.04.09-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506219/crash-2022-04-18_15.04.09-client.txt)

**Comment by CityGrump** [comment]
> same issue here on 2 clients, world broken atm... trying to force remove sign with ( /execute @e ~ ~ ~ setblock x y z air)
> 
> [crash-2022-04-18_15.06.28-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506218/crash-2022-04-18_15.06.28-client.txt) [crash-2022-04-18_15.04.09-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506219/crash-2022-04-18_15.04.09-client.txt)

/execute command didn't work..... However, I found a workaround to save my world from the crashing Flowering Azalea Wall Signs of Doom!! 
In my case i had two bugged signs in my world so i had to do this twice, but by forceloading the chunk with the sign/s (/forceload add -208 336 -192 351 & /forceload add -336 128 -321 143) i used the setblock (/setblock -202 64 377  jungle_trapdoor & /setblock -312 64 133 ) to remove the signs.

You can find the sign location and chunk in the crash log (Underlined for block & italics for chunk)
-- Block Entity Details --
Details:
Name: ecologics:sign // samebutdifferent.ecologics.block.entity.ModSignBlockEntity
	Block: Block{ecologics:flowering_azalea_sign}[rotation=0,waterlogged=false]
	Block location: World: **(-202,64,337)**, Section: (at 6,0,1 in -13,4,21; chunk contains blocks _-208,~,336 to -193,~,351_), 

Just remember to unmark the force loaded chunks after this fix (/forceload remove all).
Hope this helps anyone else whos affected by this bug!!

**Comment by SharkieTV** [comment]
Reported it to the Devs, since Ecologics mod is crashing your game its best to remove it

**Comment by Seeker14491** [comment]
There's a new release of Ecologics that fixes this issue: https://github.com/samedifferent/Ecologics/issues/30#issuecomment-1107651629
