### ISSUE TITLE
unable to upload architectury to my server.

### ISSUE THREAD

**Issue by GandalfGreyham3** [LunaPixelStudios/Better-Minecraft#289]
### Describe the Bug

I know nothing about this kind of thing so my issue might be dumb. I am trying to upload the architectury mod to my forge server hosting site and it refuses to load. Nothing loads without it so I have no idea what to do. 

### Reproduction Steps

1. I tried to upload it to my mods folder on the serverminer mod hosting service's website
2.
3.
...

### Screenshots and Videos

<img width="682" alt="Screen Shot 2022-04-17 at 2 04 38 PM" src="https://user-images.githubusercontent.com/103898145/163726820-262d2343-aab3-401b-a2de-568d9356b258.png">
been stuck on this for like an hour

### Operating System

macos

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v6

### Optifine

No

### Other Mods

did not add any others

**Comment by SharkieTV** [comment]
Not really anything to do with me rather your host
