### ISSUE TITLE
WDA maps not generating properly

### ISSUE THREAD

**Issue by ProvoGo** [LunaPixelStudios/Better-Minecraft#291]
### Describe the Bug

Unable to find WDA maps to other dungeons

### Reproduction Steps

1. Loot a monastery 
2. Find empty map instead of infested temple map
3. Still get the infested temple map found advancement 

### Screenshots and Videos

![2022-04-17_23 07 27](https://user-images.githubusercontent.com/36768970/163732315-97d22f2f-8e10-41dc-afa8-adde2e110bfc.png)
![2022-04-17_23 07 30](https://user-images.githubusercontent.com/36768970/163732318-88b8ca23-2dd3-43e2-a589-f2fbbb70d964.png)

The same with bandit towers, looted the top. 4 maps all just empty maps, they do stack

![2022-04-17_23 26 08](https://user-images.githubusercontent.com/36768970/163732634-94c5253e-f726-4386-a399-18d94cbaad97.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v6

### Optifine

No

**Comment by SharkieTV** [comment]
They dont generate in chests anymore you get them from a cartographer

**Comment by ProvoGo** [comment]
funny you should say that, i havent been able to trade for any either, also trading with cartographers freezes the game/server when it tries to find a location for a map
