### ISSUE TITLE
Can't get WDA maps from cartographers

### ISSUE THREAD

**Issue by ProvoGo** [LunaPixelStudios/Better-Minecraft#293]
### Describe the Bug

I have been unable to find any WDA maps from cartographers even tho i have gotten 60 to master level, so they either don't spawn or they are obscenely rare

I have only been able to buy

RS Monument
RS Mansion
Ocean Explorer
Woodlands Explorer
Jungle Fortress
Distant Theater

And then pathfinder and adventure maps, which leads to a mix of mineshafts/villages/shipwrecks and probably a few other more vanilla destinations

This was a creative world test with 60 villagers all leveled to master

### Reproduction Steps

1. Get a cartographer
2. Level them up to master
3. Never get a WDA map

### Screenshots and Videos

![2022-04-18_13 59 59](https://user-images.githubusercontent.com/36768970/163805242-0c180267-7b20-4140-9655-da8e4148e8fa.png)

![2022-04-18_13 42 55](https://user-images.githubusercontent.com/36768970/163803856-1ba9b18b-9fce-42be-8c2d-4942aeb68729.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v6

### Optifine

No

**Comment by SharkieTV** [comment]
Contacted the Dev of WDA, he will push out a fix. Thanks for the report
