### ISSUE TITLE
Dripstone Bug

### ISSUE THREAD

**Issue by PlasmaDragon04** [LunaPixelStudios/Better-Minecraft#296]
### Describe the Bug

As soon as i step on a dripstone spike the game crashes and i cant relog the world.

### Reproduction Steps

1. Step on pointed dripstone that is on dripstone block
2. Game crashes
3.
...

### Crash Report or Log

Exit-Code: -805306369

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Again need a crash report not just exit code, need the text cant just help with no info

**Comment by PlasmaDragon04** [comment]
[crash-2022-04-18_13.08.48-fml.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506378/crash-2022-04-18_13.08.48-fml.txt)

**Comment by PlasmaDragon04** [comment]
[crash-2022-04-18_14.52.01-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8506388/crash-2022-04-18_14.52.01-client.txt)

**Comment by SharkieTV** [comment]
Remove all the mods you added and then create a new world to see if it crashes.
