### ISSUE TITLE
Moving parts of Create mod are invisible

### ISSUE THREAD

**Issue by Jissee** [LunaPixelStudios/Better-Minecraft#297]
### Describe the Bug

Moving parts like water wheels of Create mod are invisible.

### Reproduction Steps

1. Download and install Better Minecraft [PLUS] v6 modpack snd server pack from Curseforge;
2. Start the client and server, and then connect;
3. Place a water wheel one the ground and it is invisible. And things in ponder are also invisible.
4. Also tried in singleplayer mode.
5. I guess that some of the mods in the pack conflict with create mod or flywheel mod.

### Screenshots and Videos

![2022-04-18_22 29 19](https://user-images.githubusercontent.com/50765103/163823389-afaf2e02-c2ef-4cd9-89e7-669a0d41f5b3.png)

### Crash Report or Log

No errors or crashes

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] v6

### Optifine

No

### Other Mods

No other mods

**Comment by Jissee** [comment]
It has been confirmed that the conflict is caused by Create and Oculus mod. To solve it, one of those two mods should, maybe, be removed before their development teams improve the compatibility.

**Comment by SharkieTV** [comment]
Duplicate #263
