### ISSUE TITLE
Unlimited poison, slowness, hunger and shaking screen after killing wither or awful ghast

### ISSUE THREAD

**Issue by maylolxd** [LunaPixelStudios/Better-Minecraft#298]
### Describe the Bug

We just killed the wither, but after that we always get a lot of effects that only go away after waiting like an hour. 
This also happens when killing the awful ghast. There also is a problem that sometimes when everything is fine the hunger bar just goes down in seconds, and you can't get it full for like 15 minutes of waiting. 

### Reproduction Steps

1. 
2.
3.
...

### Screenshots and Videos

https://youtu.be/kpMq8E26EUo

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Plus 1.18.2 V6

### Optifine

No

**Comment by SharkieTV** [comment]
Does drinking milk or a relog help?

**Comment by SharkieTV** [comment]
Hi, I am unable to reproduce this, can you see if v7 fixed it? and if not can you show a video>?

**Comment by maylolxd** [comment]
V7 doesn't fix it. I made a video: https://youtu.be/xpWOlmBut9w

**Comment by AnimatedAspect** [comment]
Can confirm, having issues with this too. My assumption is it's something to do specifically with these advancements:

From OP's youtube video:
![image](https://user-images.githubusercontent.com/76705806/164277541-c26e5c04-dfe1-4e0b-808a-7aae29ecac16.png)

And from my play-through
![image](https://user-images.githubusercontent.com/76705806/164277690-51d0fc44-b59e-41be-8b1c-666b40ee7531.png)

These advancements are triggered when you are subject to multiple explosions yet survive them.

**Comment by maylolxd** [comment]
Seems like some kind of environment mod is causing this. 
You can look this up by opening up the advancements with L, then look for the Sustainability tab.
If you pollute the world with explosions or something else, you get these achievements. 

![Base Profile Screenshot 2022 04 21 - 00 46 10 94](https://user-images.githubusercontent.com/103942046/164338941-7cf3fc88-1817-487c-bd29-d10f7319fa52.png)

But i can't find the mod where the achievements come from.

**Comment by AnimatedAspect** [comment]
The mod is Seeds! I've removed it from my mod folder for the time being and I'm no longer affected by it anymore. Downside though is that the grass enemies and Waste enemies not appear within the removal of this mod.

**Comment by maylolxd** [comment]
Oh yeah that was it! 
Thx!! :)
