### ISSUE TITLE
Problem installing the server

### ISSUE THREAD

**Issue by Jocky69** [LunaPixelStudios/Better-Minecraft#299]
### Describe the Bug

When trying to install the server, i have a message ''  Uncaught exception in thread "main"
java.lang.OutOfMemoryError: Java heap space ''
[2022-04-18-1.log.gz](https://github.com/LunaPixelStudios/Better-Minecraft/files/8509098/2022-04-18-1.log.gz)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMF 6.5

### Optifine

No

**Comment by SharkieTV** [comment]
Not enough memory on your device or you dont have the correct java version. Not really an issue with the modpack.
https://adoptium.net/temurin/releases
