### ISSUE TITLE
Server crashes when you enter evenbright 

### ISSUE THREAD

**Issue by UPsyk0tic** [LunaPixelStudios/Better-Minecraft#30]
https://bin.bloom.host/vefabodihom

**Comment by Auseawesome** [comment]
That link appears to be invalid and just takes me to bin.bloom.host

**Comment by Sotxri** [comment]
Again taking this thread over: 
Same problem as OP. Just built the portal. As soon as you would normally "enter" the dimension the server crashes with internal server error.
Logs attached:
[2022-01-13-2.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7866084/2022-01-13-2.log)

**Comment by switchnlade** [comment]
Ah, the java.lang.NoSuchFieldError: DIRT error. This is casued by the removal of the forge:dirt tag in forge version 39.0.18. Until Blue Skies updates their mod to match the change, please use forge version 39.0.17.

**Comment by SharkieTV** [comment]
I will push an Update out for it later today since they updated the mod

**Comment by SharkieTV** [comment]
Fixed in v12.5. If you are on Bisect Hosting just wait till they get it updated. Thanks for the reprorts!
