### ISSUE TITLE
Can't make wooden tools with modded wood

### ISSUE THREAD

**Issue by jeremyng353** [LunaPixelStudios/Better-Minecraft#301]
### Describe the Bug

Title. Can't create wooden tools with modded woods from Oh the Biomes You'll Go. Tested the mod by itself (with it's dependency, terrablender) and I could craft tools from modded woods, so I was thinking it's an incompatability with one of the mods in the pack. I also tried to craft tools after updating BYG to the latest version (RC-10). The crafting was attempted in both a modded and vanilla crafting table. 

### Reproduction Steps

1. Attempt to craft wooden tools with modded wooden planks in a crafting table. 
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6.5

### Optifine

No

**Comment by SharkieTV** [comment]
I am able to craft wooden tools with BYG Planks, maybe see if updating to v7 of the modpack works?
Ps. there is no v6.5

**Comment by jeremyng353** [comment]
![image](https://user-images.githubusercontent.com/69836033/164186991-f4e11a3a-2e40-4b44-8e42-2c4421e6ef68.png)

![image](https://user-images.githubusercontent.com/69836033/164187075-46aac49b-0ff4-438d-8c4e-f5df6a959cd1.png)

I'm running this version. Where's v7?

**Comment by SharkieTV** [comment]
oh sorry you meant fabric my bad ill check

**Comment by SharkieTV** [comment]
Sentimentally 3 mod is causing the Issue either remove it or wait for a Mod update
