### ISSUE TITLE
Mod Missmatch 1.16.5

### ISSUE THREAD

**Issue by Saltypeper** [LunaPixelStudios/Better-Minecraft#302]
### Describe the Bug

I've been trying to set up a private better Minecraft server but when I use the server files (1.16.5) from v56 25th of February and the client files from also 1.16.5 v56 from the 25th of February I see that I have the wrong mods.

### Reproduction Steps

1. Downloaded the server file v56
2. extracted it in my server folder
3. started my server
4. get the error on the client-side that the mods are mismatched
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

### Other Mods

i didnt add anything

**Comment by SharkieTV** [comment]
Its mismatch cause you are doing something wrong reinstall the modpack and serverpack and mkae sure you are running the correct versions. I cant help much as this is a user error

**Comment by Saltypeper** [comment]
is it possible that you can send me the download link for both the files since I do believe that i downloaded the same version of the modpack
