### ISSUE TITLE
Game crash, Exit Code: 1

### ISSUE THREAD

**Issue by Kitaki99** [LunaPixelStudios/Better-Minecraft#303]
### Describe the Bug

[](https://user-images.githubusercontent.com/104082646/164250918-1511943f-fb6d-4dc0-b53e-ccfd4379716d.png)[](https://user-images.githubusercontent.com/104082646/164251038-50cf7644-d778-4fef-9e92-2b29c8ff9597.png)Hello i have a similar problem with that. I'm in Version 1.18.2 of better Mc Forge and when i press play on the Mc launcher it crushes and shows these two messages.

I'm completely new to all this and i have asked around but we dont see to find a solution. I uninstall and re-installed everything twice, i updated my drivers and my java and still nothing. :<

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot_2](https://user-images.githubusercontent.com/104082646/164251914-28ad1cd0-11ea-4864-bc59-1dc899ab95e7.png)
![Screenshot_1](https://user-images.githubusercontent.com/104082646/164251928-e2f273fa-5788-4eee-87c9-f66d0a09c87a.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v.7

### Optifine

No

**Comment by SharkieTV** [comment]
It says you have an issue with your JAva version on your pc, try reinstalling java 17 if that doesnt work try another launcher like gdlauncher or ATLauncher
