### ISSUE TITLE
No squids

### ISSUE THREAD

**Issue by RogueZombieDog** [LunaPixelStudios/Better-Minecraft#304]
### Describe the Bug

there is no normal squids anywhere i cant find them

### Reproduction Steps

1.go in ocean/river
2.cant find squids anywhere
3.
...

### Crash Report or Log

https://pastebin.com/GNrcbZyj

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6.5

### Optifine

No

### Other Mods

(removed goblin traders + end goblin addon)
all macaws mod 
terralith
amplified nether 
logical zoom
legendary advancements
item borders

**Comment by SharkieTV** [comment]
I found squids straight off spawn, please only report issues without mods you add

**Comment by SharkieTV** [comment]
Because many people tend to leave that crucial part out and lie about it most of the time and then they think its my job to fix their issues they caused

**Comment by zenril** [comment]
@RogueZombieDog I do not have any of the mods you have. I'm on Forge and I also am getting no squid spawning. It happened after one of the updates I think.
