### ISSUE TITLE
Unable to start server. Missing data pack.

### ISSUE THREAD

**Issue by niche-7** [LunaPixelStudios/Better-Minecraft#305]
After updating to the latest 1.18.2, facing issue where the server is unable to start. issue with missing datapack if I am running mods.
Server is able to start with mods removed. 

Please advise, attached is the error log for your reference.

Thank you.

[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8539343/latest.log)

**Comment by SharkieTV** [comment]
what version where you on last? this suggest its missing starmute datapack which was not in the modpack at all?

**Comment by niche-7** [comment]
decided to reinstall the entire server
works now.
