### ISSUE TITLE
Crash on load in

### ISSUE THREAD

**Issue by TheTzar** [LunaPixelStudios/Better-Minecraft#306]
Numerous crashes on loadup unknown why.

[https://ibb.co/1zKKjQh](url)

[https://textdoc.co/IOgFe4K9cHyGXlCJ](url)

**Comment by SharkieTV** [comment]
None of the links work

**Comment by Seeker14491** [comment]
Here's the fixed links:
https://ibb.co/1zKKjQh
https://textdoc.co/IOgFe4K9cHyGXlCJ

**Comment by SharkieTV** [comment]
Can I get the full Crash Log please, did you add any mods? What version of the Modpack ae you on? This is why you open with the template and not blank
