### ISSUE TITLE
Crashes, Generation Errors and Recipe Balance

### ISSUE THREAD

**Issue by Yukiharuwu** [LunaPixelStudios/Better-Minecraft#307]
### Describe the Bug

==1==
-- Block Entity Details --
Details:
    Name: ecologics:sign // samebutdifferent.ecologics.block.entity.ModSignBlockEntity
    Block: Block{ecologics:coconut_sign}[rotation=0,waterlogged=false]
    Block location: World: (-544,64,597), Section: (at 0,0,5 in -34,4,37; chunk contains blocks -544,-64,592 to -529,319,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
    Block: Block{ecologics:coconut_sign}[rotation=0,waterlogged=false]
    Block location: World: (-544,64,597), Section: (at 0,0,5 in -34,4,37; chunk contains blocks -544,-64,592 to -529,319,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)

Coconut Signs crash the game, please fix.

==2==
Golden Apple crates take 8 gold blocks, and an apple crate, to craft:
Not one golden apple crate, but eight, too.
effectively letting you use 72 gold to get 576 ingots' worth of golden apples for no reason,
Fix: Adjust Blockus' recipe for to give 1 instead of 8.

==3==
There are three recipes for Tridents, added by three different mods
While this doesn't sound like an issue at first, one of the recipes is 2 sticks and 3 iron, while the rest contain some form of prismarine, thus breaking the balance of the game.
Impaled already adds a pitchfork recipe of a similar calibre, taking 2 sticks and 3 iron bars (the block from 6 iron = 16 of these), creating an earlygame alternative to the trident, like the spears from Gate of Babylon does.
Remove the early trident recipe entirely to fix.

==4==
Paradise Lost and Oh The Biomes You'll Go conflict with each other.
The Aether loads in with none of its intended biomes and instead generates with default Minecraft biomes, allowing overworld hostiles to spawn in this dimension, and stops anything aether related from spawning.
Fix? Blacklist OTBYG from interacting with Paradise Lost in some shape or form.

### Reproduction Steps

==1==
1. Place a Coconut Sign
2. Crash the Game

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMC Fabric v6.5

### Optifine

No

**Comment by SharkieTV** [comment]
Remove the Ecologics mod, the mod dev is working on a fix
