### ISSUE TITLE
Dupe with soulbound 

### ISSUE THREAD

**Issue by RogueZombieDog** [LunaPixelStudios/Better-Minecraft#308]
### Describe the Bug

when you die with an item with soulbound you drop an item called the persevering totem but the item with soulbound is already in the inventory, it also stacks. so it duplicates every time 

### Reproduction Steps

1. get soulbound
2.die
3.have 2
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6.5

### Optifine

No

### Other Mods

(removed goblin traders + end goblin addon)
all macaws mod
terralith
amplified nether
logical zoom
legendary advancements
item borders
better animals+
(none of these mods would make this happen)

**Comment by RogueZombieDog** [comment]
it seems to be an issue with charm though can be easily fixed in configs

**Comment by SharkieTV** [comment]
Im not getting this issue in my own testing but ill still disable the totem of preserving anyways
