### ISSUE TITLE
Bees not breeding

### ISSUE THREAD

**Issue by jlangholzj** [LunaPixelStudios/Better-Minecraft#309]
When using flowers to breed bees, they go into the "lovemaking" animation but do not produce a baby bee. Tested with several types of flowers.

Edit: I see another user had this issue and sharkie may have forwarded to mod. Just confirming this is still persistent on Fabric v6.5 (beta).

**Comment by MoniMosa** [comment]
I came here because I am having the same issue as well. I'm currently running Fabric v5 for 1.18.2.

**Comment by SharkieTV** [comment]
Duplciate #268
