### ISSUE TITLE
Sophisticated Backpacks mod is missing, or all backpacks are gone

### ISSUE THREAD

**Issue by ArthasLightmoon** [LunaPixelStudios/Better-Minecraft#31]
### Describe the Bug

Not sure if this is something to mention here but I am not sure who or how to fix this. I updated the server to the latest modpack version, V12, after I backed up my world from the server and I had everything running, not longer getting that crash error of before, and things were running fine. But when I checked my inventory as well chests, all of my backpacks were gone. I only made one, as the rest of them I found them all around. I didn't consider it a problem until I realized, 80% of my items, including all my metals like diamonds, is now gone in this new working version of the server.
Was there a reason that mod was removed from the whole pack? Can I just add the mod manually on the server and keep using it even if it wasn't in the forge modpack originally?
Or if this is meant to be, and that mod is gone, any recommendation on how I can recover all my stuff from the backed up world before the server update?
I'm sorry for the trouble and I know this sound like a rookie request, but I do not want to have all of my progress and items i got  from dungeons, mines and locations I explored and died many times, gone because of it.
Thank you.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v12

### Optifine

No

### Other Mods

Sophisticated Backpacks, or tried to at least.

**Comment by switchnlade** [comment]
Sophisticated backpacks was removed in v11. If you have a backup, restore the server to it, and add in the backpack mod once more before starting your server, then take out your items/continue using the sophisticated backpacks mod (your choice).

The reason it was removed is that it was never going to be the main backpack mod, it was just a temporary fill in. It's always good to read the changelogs of each version, so you know what will be there still and what won't be.
