### ISSUE TITLE
crash when placing sign 

### ISSUE THREAD

**Issue by ypssehlig** [LunaPixelStudios/Better-Minecraft#310]
### Describe the Bug

When placing a walnut sign from the ecologics mod, the game instantly crashes and it is no longer possible to rejoin the game.

### Reproduction Steps

1. get a (ecologics) walnut sign
2. place it
3. crash
...

### Crash Report or Log

https://pastebin.com/Eq3CXSRu

### Operating System

Windows 10 and MacOS (Monterey)

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6.5

### Optifine

No

### Other Mods

no other mods  were added

**Comment by SharkieTV** [comment]
Fixed in v7
