### ISSUE TITLE
Game crashed, can't load in now

### ISSUE THREAD

**Issue by Mitch0530** [LunaPixelStudios/Better-Minecraft#312]
### Describe the Bug

Game randomly crashed, can't load in now without same crash. Any help would be appreciated. I haven't made any changes to the modpack in any way.

Pic of crash report attached.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2022-04-26 214528](https://user-images.githubusercontent.com/104475068/165421699-eca373d3-cc76-491e-bcc8-0166996386cf.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

6.5

### Optifine

No

**Comment by SharkieTV** [comment]
Can I please get the full crash report not just a screenshot and can you see if updating to v7 fixes this issue.

**Comment by Mitch0530** [comment]
> Can I please get the full crash report not just a screenshot and can you see if updating to v7 fixes this issue.

Updated to v7, game froze but still had audio the first time I tried to load into my world. Closed the game and loaded back in and didn't crash. I'll add the crash report for v7 as well.
[Crash v6.5.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8568541/Crash.v6.5.txt)
[Crash v7.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8568542/Crash.v7.txt)
l

**Comment by SharkieTV** [comment]
So v7 your getting a different crash with a sound crash. See if reinstalling the Modpack helps but if you got back in it should be good i think
