### ISSUE TITLE
Dragon Mount

### ISSUE THREAD

**Issue by DarthRexPoke44** [LunaPixelStudios/Better-Minecraft#313]
### Describe the Bug

The dragon is tping after you, and the wiki for the mod says to right click with a bone, but it isn't doing anything. Just wondering if it is the mod, or something in the pack is interfering with that command. 

### Reproduction Steps

1.Have an adult dragon
2.Try to right click with bone for it to sit
3.The dragon still follows you
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v7

### Optifine

No

**Comment by DarthRexPoke44** [comment]
Currently we're leading the dragon to a fence post, but when log back in, it would tp to you. And my friend says now that that doesn't work

**Comment by SharkieTV** [comment]
Have you tired shift right clicking without a bone?

**Comment by DarthRexPoke44** [comment]
So we tried it multiple times. All ice dragons, it didn't work on two out of five of them. So we've just been cheating them in until we get one that it works on.
