### ISSUE TITLE
Server lagging

### ISSUE THREAD

**Issue by iamshoXy** [LunaPixelStudios/Better-Minecraft#314]
### Describe the Bug

Sometimes the server is lagging and people get a high ping on the scoreboard.
Can that be by not pregenerating the world? But that shouldn't drive the ping up so much, should it? Everything is fine with the network and there is also enough ram allocated.

### Reproduction Steps

Play and wait for the lags

### Operating System

Ubuntu 20.04.4 LTS

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft v6.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
I dont know how many players you are talking about and if its lagging with ping then it have to do something with the serverhost

**Comment by SharkieTV** [comment]
If its that many players then yes you need to pregen otherwise it will lag
