### ISSUE TITLE
Aether Crash

### ISSUE THREAD

**Issue by OGTKells** [LunaPixelStudios/Better-Minecraft#315]
### Describe the Bug

When entering the aether in creative mode, my game crashed,

### Reproduction Steps

1. Start Creative World
2. Build Aether Portal
3. Game crashes
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v6

### Optifine

No

**Comment by SharkieTV** [comment]
update to v7
