### ISSUE TITLE
Overworld generation in the Aether

### ISSUE THREAD

**Issue by jeremyng353** [LunaPixelStudios/Better-Minecraft#317]
### Describe the Bug

Overworld structures are being generated in the Aether. The first screenshot shows an ocean monument generated in a cube of water, and the second screenshot shows a mineshaft.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/69836033/165692674-cb26c701-86af-45f2-8012-c12bef7c2244.png)
![image](https://user-images.githubusercontent.com/69836033/165692741-fd8731bc-13b1-43ce-9ff6-2a397c1eebf8.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v7

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate #285
