### ISSUE TITLE
Infusion process seems to not work except for making Hydralux petals

### ISSUE THREAD

**Issue by Gregg626** [LunaPixelStudios/Better-Minecraft#32]
### Describe the Bug

So there seems to be an issue with the BetterEnd Forge mod where when I try to use the infusing table, then I go to right click it but I just pick the book back up instead of starting the infusing process. Like in my title it only seems to work when I try it with the hydra petals. Just trying to make sure I'm not doing anything wrong or this is a bug

### Reproduction Steps

1. I simply just place the items in their proper place and right click it, but instead of activating it it just picks it up
2.
3.
...

### Screenshots and Videos

![SPOILER_SPOILER_unknown-1](https://user-images.githubusercontent.com/97806165/149635355-ac00a8f9-be5d-4552-8358-551c65da6882.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V53.5

### Optifine

No

**Comment by SharkieTV** [comment]
What is it suppose to make? The BetterEnd for Dummies book? Maybe remove the Shulker box or maybe it needs BetterEnd Pedestals? I haven't tested it myself just let me know what the ritual does?

**Comment by Gregg626** [comment]
> What is it suppose to make? The BetterEnd for Dummies book? Maybe remove the Shulker box or maybe it needs BetterEnd Pedestals? I haven't tested it myself just let me know what the ritual does?

It is supposed to make a mending book, but I did remove it after I took the picture and tried again but to no success

**Comment by SharkieTV** [comment]
So where did you find out you can make a mending book from this ristual?

**Comment by Gregg626** [comment]
![image](https://user-images.githubusercontent.com/97806165/149715401-5e72dcd9-d454-4997-a074-a744232d44d5.png)
It was the crafting tooltip in game, it's how I made the hydralux infused petal

**Comment by Gregg626** [comment]
After I updated my game and then flipped it, the infusion worked perfectly fine
