### ISSUE TITLE
Blue Skies Crashing The Game Before It Starts

### ISSUE THREAD

**Issue by NoPlayerGuy** [LunaPixelStudios/Better-Minecraft#320]
### Describe the Bug

I really love this modpack but everytime I launch the game with blue skies installed
the game crashes before the game starts. I really need help about this

Thank you

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

I didn't generate a crash report

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v8

### Optifine

I used Optifine

### Other Mods

None

**Comment by SharkieTV** [comment]
The mod is already in the modpack? are you adding another version and thats why?

**Comment by NoPlayerGuy** [comment]
I Didn't add a mod though plus, my game didn't generate a crash report for some reason. Yes, Blue Skies is in the modpack. Also when i add a new mod it also crash
maybe i think it is about the ram i allocated to minecraft

My Minecraft Crashed With Exit Code: 1

**Comment by SharkieTV** [comment]
Send your latest.log, I jsut realised you said you added Optifine? so thats probably what is crashing your game so remove it.

**Comment by NoPlayerGuy** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8598862/latest.log)
 here is the latest.log file

**Comment by SharkieTV** [comment]
yes optiifne is crashing your game, not sure why you have it in as it states its not needed, remove Optifine and anything related to it
