### ISSUE TITLE
Unrendered blocks on Forge 1.18.2 with the immersive weather mod

### ISSUE THREAD

**Issue by carefulpear21** [LunaPixelStudios/Better-Minecraft#321]
### Describe the Bug

I have jumped on to notice that some blocks linked with the immersive weather mod do not render. So far it has been diorite and red oak tree leaves. When the mod is applied to other versions it works fine. Not sure if this is one for you or the mod creator.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

Could not get accurate screenshots

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

### Other Mods

None

**Comment by SharkieTV** [comment]
Its probs an issue with Rubidium/Oculus, can you see if removing those mods work?

**Comment by carefulpear21** [comment]
Just tried this and they remain in the game

**Comment by dodolello** [comment]
I have the same problem, I tried reinstalling removing the oculus but works only for the first login, then the texture are glitched again
![image](https://user-images.githubusercontent.com/82171794/166076687-509daf2f-cffe-4094-848c-2775353c77d3.png)

**Comment by SharkieTV** [comment]
> I have the same problem, I tried reinstalling removing the oculus but works only for the first login, then the texture are glitched again ![image](https://user-images.githubusercontent.com/82171794/166076687-509daf2f-cffe-4094-848c-2775353c77d3.png)

I think yours is a different issue

**Comment by SharkieTV** [comment]
> Just tried this and they remain in the game

Might be a mod issue ill check when i can

**Comment by Wilhelm552** [comment]
Hey this may be a false lead but I had a similar issue when I updated Verdure to the most recent version. Red oak leaves specifically had a missing texture. 

I believe this may be the cause as this bug report comes right after the update and upon reading the changelog it has references of adding it's own version of fallen leaves.

**Comment by SharkieTV** [comment]
Should be fix when next update comes out
