### ISSUE TITLE
Server structures problem

### ISSUE THREAD

**Issue by raresqn** [LunaPixelStudios/Better-Minecraft#322]
### Describe the Bug

Hello, I have a server on hosting and everything works fine, but generating structures from mods does not work properly as in singleplayer, how to fix it or change it in the config

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Not sure what you mean by generating structures? They automatically generate and their is no issues with it

**Comment by raresqn** [comment]
Yes, but some structures do not appear on the server, If they appear, it is very rare

**Comment by SharkieTV** [comment]
all structures are rare and thats how they generate? not sure what you want me to do and this is not a bug
