### ISSUE TITLE
Sleeping bag / White wool Slaps Recipe overleaping

### ISSUE THREAD

**Issue by NotXD08** [LunaPixelStudios/Better-Minecraft#325]
Hello LunaPixelStudios

I found out that the Recipe for every type of Sleeping bags is the same like every type of wool slabs.
This make it impossible to Craft sleeping bags

**Comment by Chrispytoast** [comment]
There should be a little switch icon next to the crafting output when you craft it. See if that allows you to switch between the two outputs

**Comment by SharkieTV** [comment]
Polymorph is in the game and can change same recipes
