### ISSUE TITLE
Vanishing Snow

### ISSUE THREAD

**Issue by Dioxiz** [LunaPixelStudios/Better-Minecraft#326]
### Describe the Bug

Hey, not sure if it's a bug or a feature.
Whatever world I generate, snow seems to be generated correctly in cold-type biomes but vanishes immediately when in entity-radius (only the thin snow, not blocks).
Even when its snowing, the snow falls down onto blocks and melts a few ticks later.
Not only is it ugly (snow biomes without snow), it's also causing hard lags whenever I enter such environments for the first time.
Which mod is causing this? Same seed in Vanilla doesn't have this issue. (Btw Serene Seasons deactivated - still the same)

### Reproduction Steps

1. Try seed "Hot RGB" without quotes, for example
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V8

### Optifine

No

**Comment by SharkieTV** [comment]
Can you see if removing immersive weather works?

**Comment by Dioxiz** [comment]
Immersive Weathering is deactivated, same issue. I'm going to deactivate a few others for a process of elimination.

**Comment by Dioxiz** [comment]
I don't know what happened but know it's solved.
