### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by NeonStar-tv** [LunaPixelStudios/Better-Minecraft#327]
### Describe the Bug

In the blue skies one in the blue portal when it snows it breaks the game and fails to load chunks. I after a few hours of testing and trial and nothing, I noticed it just... Stopped. It was because it was snowing. And I looked into the crash log and it was because of snow blocks and sounds from the data pack? I believe the chunks being generated could not load noises properly. I have no clue if it is the packs fault seasons nonsense or blue Skies but clearing the weather after a test seemed to fix it as well, I have no idea what I did but it stopped and I want you guys to know that this can happen and maybe fix it. :

Here is a log

https://paste.ee/p/DDHfK 

And here is the twitch vod, (I will highlight it on my channel incase we need it in the far future DM me on twitch or discord and I will send the link) 

https://www.twitch.tv/videos/1474636678

### Reproduction Steps

1.Load the chunks
2.crash and repeat like 15 times
3. It stopped and I have no idea how...?
...

### Screenshots and Videos

https://www.twitch.tv/videos/1474636678

### Crash Report or Log

https://paste.ee/p/DDHfK 

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v8

### Optifine

No

### Other Mods

none

**Comment by SharkieTV** [comment]
Is this on a new world or a world made before v8?

**Comment by NeonStar-tv** [comment]
It was made before v8, v6 is when it was made.

**Comment by SharkieTV** [comment]
yes so this happens when you update the modpack because mods updates change things causing these issues . New worlds wont cause this issue
