### ISSUE TITLE
No access to shader packs

### ISSUE THREAD

**Issue by Sage009** [LunaPixelStudios/Better-Minecraft#328]
Minecraft 1.18.2 with Forge 40.1.0
In my video settings, there's no option to access shader packs.
![2022-05-04_10 50 33](https://user-images.githubusercontent.com/32518671/166707954-0a5b11a2-d1b3-411e-bb11-26df0868f926.png).

**Comment by SharkieTV** [comment]
Reinstall the Modpack, the mods are in the pack so either you removed them or it installed wrong
