### ISSUE TITLE
Soot won't burn

### ISSUE THREAD

**Issue by Mereni** [LunaPixelStudios/Better-Minecraft#329]
### Describe the Bug

The item 'soot' from the mod 'Immersive Weathering' is supposed to provide .5 fuel while smelting.  It currently won't go into the furnace.

### Reproduction Steps

1. Get some soot.
2. Try to put it in the fuel slot of the funace.

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [Forge] v5

### Optifine

No

### Other Mods

None

**Comment by SharkieTV** [comment]
It doesnt seem like soot can be used as fuel anymore
