### ISSUE TITLE
neutral Mobs/Sleep issue

### ISSUE THREAD

**Issue by ItzVik** [LunaPixelStudios/Better-Minecraft#334]
### Describe the Bug

the wolfs and bees attack you even if you dont do anything to them, i tired sleeping but wont turn to the next day

### Reproduction Steps

1. generate new world
2. find wolfs or beehive
3. they will attack you
1. let it be night
2. go to sleep

...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

### Other Mods

no

**Comment by GoatRammaHamma70** [comment]
You probably equipped the ring of 7 curses when you first spawned in. Some of the curses are not allowing you to sleep and making all neutral mobs hostile towards you. Once you put it on, you can't take it off, so removing the mod Enigmatic Legacy will solve your issue
