### ISSUE TITLE
Bugged Wold?

### ISSUE THREAD

**Issue by Hannoxx** [LunaPixelStudios/Better-Minecraft#335]
### Describe the Bug

I was exploring the End and decided to teleport to my last death, it never teleported me so I moved on and noticed I could no longer do anything on my world. I cant use any commands, cant take damage, cant break blocks, nothing. All my other worlds are fine I can do all of the above but this one specifically I'm basically stuck not being able to do anything.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Cant help much with no log
