### ISSUE TITLE
Missing Texture Andesite Ores

### ISSUE THREAD

**Issue by FreestyleStorm** [LunaPixelStudios/Better-Minecraft#336]
### Describe the Bug

Andesite Ores have the black and purple missing texture issue.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Base Profile Screenshot 2022 05 05 - 22 13 25 62](https://user-images.githubusercontent.com/28576297/167071263-047d25ff-74a6-47db-829a-2ea08f6b6592.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V9

### Optifine

No

### Other Mods

No other mods used.

**Comment by FreestyleStorm** [comment]
Also noted that this world was created in V7

**Comment by SharkieTV** [comment]
Reported it to the Dev
