### ISSUE TITLE
Hopper Minecart crash

### ISSUE THREAD

**Issue by xstarlin** [LunaPixelStudios/Better-Minecraft#337]
### Describe the Bug

I am trying to make a compact chicken cooker. I crafted a hopper minecart and placed it on top of a rail that was sitting on top of a regular hopper. When I placed the hopper minecart on the rail my game crashed and now I can't open the world without it crashing.

### Reproduction Steps

1. Place hopper facing into chest
2. Place rail on hopper
3. Place hopper minecart on rail.
...

### Crash Report or Log

https://pastebin.com/ZQTSaJRY

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

I used Optifine

### Other Mods

Inventory Sorter

**Comment by xstarlin** [comment]
Tested again in a super flat creative world and the same issue happened where I crashed once I placed the hopper minecart

**Comment by SharkieTV** [comment]
Seems to be an issue with Create/Flywheel Mod, best is to remove it and launch the world and see if it fixes it if it does then I recommend not doing it again until the mod fixes it

**Comment by xstarlin** [comment]
I was able to find a work around without removing it just so you know. I opened MC and went into the mod config window and disabled Backend for flywheel and it works now.
