### ISSUE TITLE
Illusionist entity bug

### ISSUE THREAD

**Issue by ThePlugPedro** [LunaPixelStudios/Better-Minecraft#338]
### Describe the Bug

When fighting a raid, I got to a wave where an illusionist spawned, and after I kill it, the game has started crashing. I thought it was maybe one of the buffs or debuffs ticking on my character, but the game keeps crashing even after I drank some milk.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/FcwYT7ZA

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft version 7

### Optifine

No

**Comment by SharkieTV** [comment]
Can you see if updating the modpack helps?

**Comment by ThePlugPedro** [comment]
I've updated to the most recent version, and the while the game last longer before crashing, it's still sadly crashing the game. I'm still getting a similar crash report as before. https://pastebin.com/MF9k4Y82

**Comment by SharkieTV** [comment]
I tested it and didnt crash after finishing the raid. Can you see if removing the Illager Expansion mods helps?

**Comment by ThePlugPedro** [comment]
I’m not sure exactly what it was that was crashing me, I tried the /kill command to see if dying cleared whatever it was on me and it did, so the problem is thankfully solved!
