### ISSUE TITLE
Better Minecraft PLUS 1.18.2 Crashing (

### ISSUE THREAD

**Issue by torbis123** [LunaPixelStudios/Better-Minecraft#339]
### Describe the Bug

Using Better Minecraft PLUS 1.18.2 with CurseForge, ATLauncher and GDLauncher will yield in a crash named 'Exit Code 1' 

### Reproduction Steps

Quite straight forward, you click play on either of the Launchers and once the MC Launcher pops, you click play and it crashes on launch.

### Screenshots and Videos

![Screenshot_35](https://user-images.githubusercontent.com/23709366/167234703-21ac2d39-d2b9-4d08-86ff-0e5d4e84022d.png)

### Crash Report or Log

https://pastebin.com/n3tJUfqG

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft PLUS v9

### Optifine

No

**Comment by SharkieTV** [comment]
Not sure why you are getting this as everyone else can install and play, can you try Cusreforge Launcher?

**Comment by Reypatey** [comment]
I've got the same issue, but with the non PLUS edition. A fresh install from CurseForge Launcher get's the same error for me. I'm attaching my log file.

[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8644615/latest.log)

**Comment by halfhoney00** [comment]
I'm receiving the same issue (also non PLUS edition) - v8 works fine, it seems to just be v9.

**Comment by t0mmyyyS** [comment]
I´ve got the same issue but in the "Forge" edition (1.18.2) v8 works but v9 is no chance 
i tried with a older java update (newest is Update 333, i tried update 331. Both don´t work)
i reinstalled all (curse launcher, minecraft itself, java) but nothing helps

**Comment by GoatRammaHamma70** [comment]
i have the exact same issue.

**Comment by Azarath20047** [comment]
same. i thought it was a couple mods i added, but it wasnt them. fresh installs/reinstalls of curse, modpack, and i even repaired minecraft itself, and it wont work. tried java 17/18, no luck, and someof my other modpacks are having the same problem as well.

**Comment by SharkieTV** [comment]
Best is to wait for v10 since I cant recreate this issue as it installs fine and launcher fine

**Comment by Azarath20047** [comment]
I did some more testing and found out the blocks plus mod was actually
causing the error I had, so I removed it and the BH menu mod as well and
it's been running fine since. Also is there a page or something where I can
suggest mods to be added into the pack? Got a few that I think would run
pretty nice with it.

**Comment by psw1n** [comment]
I got it to work editing profile for the mod in curseforge:
Advanced settings 
Modloader version = forge 40.1.54 (curseforge had defaulted to 40,1.52)
Preferred release type = Release (recommended)
