### ISSUE TITLE
53.5 server pack for 1.16.5 does not match with client pack so I cannot connect to server.

### ISSUE THREAD

**Issue by gamer20088** [LunaPixelStudios/Better-Minecraft#34]
### Describe the Bug

Server connection does not work due to client-side having more mods.

### Reproduction Steps

1.
2.
3.
...

### Operating System

10 Windows

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

53.5

### Optifine

No

**Comment by switchnlade** [comment]
Please verify your installs, and reinstall as needed. Client packs will always have more mods than the server packs due to having client side only mods, such as magnesium, magnesium extras, etc. V53.5 does work when properly installed on both server and client.
