### ISSUE TITLE
Missing textures on andesite coal ore

### ISSUE THREAD

**Issue by timingplanet** [LunaPixelStudios/Better-Minecraft#340]
### Describe the Bug

Missing textures on andesite coal ore.

### Reproduction Steps

1. Search andesite
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/27646155/167242059-22d89002-ed4d-4185-9d82-76c310bbdb1a.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate #336
