### ISSUE TITLE
unable to plant crops on cultivated land except on vanilla cultivated land

### ISSUE THREAD

**Issue by HZDY** [LunaPixelStudios/Better-Minecraft#342]
### Describe the Bug

unable to plant crops on cultivated land except on vanilla cultivated land except on vanilla cultivated land.
<img width="966" alt="截屏2022-05-08 上午11 05 19" src="https://user-images.githubusercontent.com/59334092/167279974-9096fc76-e547-4978-b620-96c49b06db5b.png">

Every time I right click the cultivated land in mods(otbyg and farmer's delight) I just eat my carrot.

Though I've removed some of the mods, they seem to be unrelated to the problem.

### Reproduction Steps

1.
2.
3.
...

### Operating System

macOS Monetary

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v8

### Optifine

No

### Other Mods

Added: 
Apple Skin

Removed:
adorn
architectspallete
betterf3
betternether
blockus
blur
chipped
creeperoverhaul
cullleaves
decorativeblocks
fallingleaves
highlighter
illagerexpansion
notenoughanimations
thegraveyard
probablychests
pickupnotifier
quartzelevator
youareingravedanger
styledchat
stylednicknames
styledplayerlist
grizzlybears

**Comment by SharkieTV** [comment]
This is known issue and I'm trying to find the fix
