### ISSUE TITLE
Crash while fighting Shulkers

### ISSUE THREAD

**Issue by arial-cs50x** [LunaPixelStudios/Better-Minecraft#345]
### Describe the Bug

In **version 9**, fighting shulkers for a few minutes results in a **ticking entity crash**.

```
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5643(net.minecraft.class_1282, float)" because "attacker" is null
Exit Code: -1
```

My suspicion is on the Netherite shield with the Reflection 3 enchant. When the shulker dies before the player reflects the damage of the shulker bullet, the game cannot find the said shulker and crashes.

### Reproduction Steps

1. Go to an End City
2. Get a full set of Dragon armor, **Netherite shield with Reflection 3** enchantment, Dragon sword with vanilla enchants
3. Fight the shulkers while **blocking with the netherite shield**
4. Keep fighting until the game crashes

### Screenshots and Videos

[Video](https://streamable.com/ts8ezb)

### Crash Report or Log

https://gist.github.com/arial-cs50x/6b26d68b5b2c5672c672da977a7d3698

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v9

### Optifine

No

### Other Mods

- **Starlight 1.0.2 Fabric** (Replaced Phosphor Fabric 0.8.1)
- **Fabric Chunk Pregenerator 0.3.4 for 1.17** (Still works in 1.18.2)

**Comment by SharkieTV** [comment]
Yeah seems like a Basic Shields crash, remove it if you dont want it to crash again and ill report it to the dev
