### ISSUE TITLE
Game crashes when trying to login

### ISSUE THREAD

**Issue by Thiagovskii** [LunaPixelStudios/Better-Minecraft#346]
### Describe the Bug

[](url
[crash-2022-05-08_00.35.58-fml.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8647487/crash-2022-05-08_00.35.58-fml.txt)
)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 7

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] 1.16.5

### Optifine

No

**Comment by SharkieTV** [comment]
you added botania and its crashing, next time dont leave the other mods empty, remove the mods you added
