### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by EddieEsper** [LunaPixelStudios/Better-Minecraft#347]
### Describe the Bug

"Failed Getting Mod Files" "InternalServerError"

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

<img width="1440" alt="Screen Shot 2022-05-08 at 2 32 07 PM" src="https://user-images.githubusercontent.com/105170922/167310410-c626e973-d3ca-4f62-abfa-4ba71d5e258b.png">

<img width="1440" alt="Screen Shot 2022-05-08 at 2 32 07 PM" src="https://user-images.githubusercontent.com/105170922/167310425-2aab53d3-59a0-46a4-8355-9f029d464f38.png">

### Operating System

Mac

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

### Other Mods

no.

**Comment by SharkieTV** [comment]
Cursefroge is having issues, not much i can do so can people stop making this issue
