### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by bngapple** [LunaPixelStudios/Better-Minecraft#348]
### Describe the Bug

EDIT: I fixed it I thought I  used forge but I used fabric and it works now
When ever I put shaders on with better minecraft the screen is just black I can see the hotter and crosshair

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-05-08_14 55 36](https://user-images.githubusercontent.com/104392278/167311338-3be291dc-5056-4fc3-be4d-813df0f565d1.png)

### Operating System

Mac OS

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V8

### Optifine

No

**Comment by SharkieTV** [comment]
using the shaders settings in game or you added optifine? also you have a Mac so it could be that as it works on windows

**Comment by bngapple** [comment]
I also fixed this whole time I thought I was using forge but I was using fabric and it works now
