### ISSUE TITLE
 Raid Ravager Sound Crashing Server

### ISSUE THREAD

**Issue by Beehoo0** [LunaPixelStudios/Better-Minecraft#349]
### Describe the Bug

A member of my server started a raid and attacked a ravager and it crashed the server and the players game as a whole. 
[crash-2022-05-09_02.08.19-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8648366/crash-2022-05-09_02.08.19-server.txt)

### Reproduction Steps

1.Start a raid
2. attack a ravager
3. ravager roars/ makes hit noise and then crashes
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc f v9

### Optifine

No

### Other Mods

just added a voice chat mod

**Comment by SharkieTV** [comment]
Remove the warden mod
