### ISSUE TITLE
Book randomly pops up as I play

### ISSUE THREAD

**Issue by Krennilackin** [LunaPixelStudios/Better-Minecraft#351]
### Describe the Bug

A book with prompts like "How to Enter", "How to Leave", "How to find Caves", "Discs", "Mobs", and "Flagon & Powers".

This is preceded by a sound prompt that causes book to pop up for player.

The player is on a new account and running their game for the first time.

No steps to repro issue as this is a randomly occurring issue that happens when they're standing still or moving around.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/105265268/167547678-34ec1d49-82e8-4dc3-9452-2313b2bcfdf9.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
Press F1 to remove it or look at the keybinds?

**Comment by Krennilackin** [comment]
Thanks for the response!

Just a bit of input, player said they walked away after logging in, noticed that the book popped up after they had afk'd.

Looks like resetting keybinds to default fixed the issue!
