### ISSUE TITLE
BUG Redstone: Honey blocks stick to slime blocks when pushed by piston

### ISSUE THREAD

**Issue by Frodon69** [LunaPixelStudios/Better-Minecraft#353]
### Describe the Bug

So I was trying to make a two wide flying machine bridge and it kept breaking down ... I eventually found that when placing honey blocks adjacent to slime blocks and only pushing the honey block with a piston, the honey block followed. In regular minecraft slime blocks do not stick to honey blocks... 
It is worth mentionning that when i push the slime block there is no bug. It is really only if the honey block is pushed.

Hence there must be a mod which breaks this mechanic. 

PS: this is on server and v7 of the modpack 

### Reproduction Steps

1. place sticky piston down facing up
2. place down honey block on face of the piston 
3. place slime block adjacent to the honey block
4.  activate piston and see that the slime block is taken as well 

Notice that if the the slime block is pushed instead of the honey block the bug does not occur.

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better minecraft v7

### Optifine

No

**Comment by SharkieTV** [comment]
Can you update to newest version and let me know if it still happens?

**Comment by SharkieTV** [comment]
Tested on latest and does not occuer

**Comment by Frodon69** [comment]
Still doesn't work in v9

Have you tried on server ?
