### ISSUE TITLE
Server is up but can't connect

### ISSUE THREAD

**Issue by MajsterBartosz** [LunaPixelStudios/Better-Minecraft#354]
### Describe the Bug

I start up my server first time it crashed at start then I got it up and running but cannot connect

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/xWUg8ERb

### Operating System

Ubuntu

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
The log didn't mention that you tried to connect, could you get one that does and also your clientog too
