### ISSUE TITLE
Better Minecraft Plus 1.18.2 - Crash

### ISSUE THREAD

**Issue by thvndra** [LunaPixelStudios/Better-Minecraft#355]
### Describe the Bug

everytime i click on "create new world" my game crashes

### Reproduction Steps

1. Open minecraft
2. Click on singleplayer
3. Click on create new world
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
Need a log of the crash or latest log otherwise I can't help and how much ram have you allocated?
