### ISSUE TITLE
Vanishing enchnts

### ISSUE THREAD

**Issue by Birca12** [LunaPixelStudios/Better-Minecraft#356]
### Describe the Bug

I Have sword with sharpness And Its disspear

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V56

### Optifine

I used Optifine

**Comment by RichPrune** [comment]
if you give it to an allay or maybe some other modded mob it removes enchants

**Comment by SharkieTV** [comment]
The allay thing or the mob in the desert that can rip off enchants if it hits you
