### ISSUE TITLE
Invalid Java Runtime Configuration; Exit Code 1 on Better Minecraft FORGE 1.18.2 v9

### ISSUE THREAD

**Issue by Boydie64** [LunaPixelStudios/Better-Minecraft#358]
### Describe the Bug

I've tried everything I can think of to fix this issue, I've reinstalled the modpack, curseforge, minecraft, everything. I've attached the log, but have no clue what is causing the issue or if it's an issue with a specific mod. Any help would be appreciated. Thanks.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/QTEFmfY0

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

### Other Mods

No other Mods

**Comment by SharkieTV** [comment]
Can you see if removing snow under trees mod fixes it?

**Comment by Boydie64** [comment]
I don't see a mod file for snow under trees in the mod list??

**Comment by SharkieTV** [comment]
see if adding that mod fixes it? https://www.curseforge.com/minecraft/mc-mods/snow-under-trees/files/3694488

**Comment by Boydie64** [comment]
I added that mod and noticed the CraftTweaker mod was missing as well and added that. THis allows the game to launch, but sits there perpetually with a white and black screen. This is the latest log: https://pastebin.com/whqePmzD

**Comment by SharkieTV** [comment]
Does not make sense why that mod would be missing especially if you reinstall the modpack, the log provides nothing as it seems to run fine, what are your pc specs? and when abouts does the black screen come up?

**Comment by Boydie64** [comment]
I was able to actually just get it to work. I did nothing different, but it works perfectly fine now. I'm not sure why it was downloading without crafttweaker as I downloaded this modpack on another PC at the same time and it has worked perfect on that one for my wife. Thanks for the help though!
