### ISSUE TITLE
Bee Breeding Bug

### ISSUE THREAD

**Issue by monic025** [LunaPixelStudios/Better-Minecraft#359]
### Describe the Bug

Minecraft 1.18.2
Better Minecraft v8 FABRIC

Bee can't breed and produce babies.
In both Multiplayer and Singleplayer.

### Reproduction Steps

1. get 2 bees
2. give them flowers
3. wait for them to get babies
4. babies doesn't appear and they just went on their business like usual.
...

### Screenshots and Videos

![bee-breeding-bug](https://user-images.githubusercontent.com/98271365/167765734-211cff72-5bde-41be-958f-1dadc945d90c.gif)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft v8

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate #268
