### ISSUE TITLE
When holding a tool with mending, the tool doesn't absorb all the exp

### ISSUE THREAD

**Issue by Gregg626** [LunaPixelStudios/Better-Minecraft#36]
### Describe the Bug

I've noticed when using mending tools, and I double checked to see if my armor with mending is full of durability as well, that sometimes the exp goes into my bar rather than my tools. Making it hard to repair my tools using EXP.

According to the minecraft wiki mending is supposed to heal 2 points of durability for every 1 point of exp absorbed, it also stops you from gaining the exp yourself because the tool is suppose to be in it's place taking it. So seeing as I gain exp while holding a mending tool makes me think something is off.

### Reproduction Steps

1. Equip mending tool
2. Gain exp
3. Exp does not solely go into tool, sometimes it gets absorbed by the player
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V53.5

### Optifine

No

**Comment by SharkieTV** [comment]
Can you show a screenshot of what you have in your inventory and what item you have mending on/.

**Comment by Gregg626** [comment]
![image](https://user-images.githubusercontent.com/97806165/149888941-8a050dfa-5b03-4f53-b224-70b1021c0b7a.png)

**Comment by SharkieTV** [comment]
In my testing with the latest version of the pack, the mending does work and fills up the item durability first before giving me the xp.

**Comment by Gregg626** [comment]
Hmmm there may be a bug with my world then, is there a way for me to restart or refresh it?

**Comment by SharkieTV** [comment]
Not sure, when did you start your world on what version of the modpack?

**Comment by Gregg626** [comment]
I started it on 52.5 and moved to 53.5

**Comment by Gregg626** [comment]
Also noticed a new version is out, will I have to update my server version as well by downloading the new world pack and moving my old world in there or some other way

**Comment by SharkieTV** [comment]
I guess update other than that its not happening to me in testing
