### ISSUE TITLE
Better Minecraft FORGE 1.18.2 v9 - server Crash - Exception generating new chunk

### ISSUE THREAD

**Issue by MrGcGamer** [LunaPixelStudios/Better-Minecraft#360]
### Describe the Bug

Server crashes on chunk generation in the everbright.

### Reproduction Steps

I am told, the server crashes, when a certain dungeon in the everbright is being loaded in, although I don't know which dungeon.

### Crash Report or Log

https://pastebin.com/eguqbTQX

### Operating System

Server Crash - Exaroton server

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

**Comment by MrGcGamer** [comment]
I can't really test that, as Exaroton doesn't allow editing the modpack

**Comment by SharkieTV** [comment]
then I guess dont pregen the blue skies mod
