### ISSUE TITLE
Better Minecraft FORGE 1.18.2 v9 - server Crash - Ticking entity

### ISSUE THREAD

**Issue by MrGcGamer** [LunaPixelStudios/Better-Minecraft#361]
### Describe the Bug

Server crashes when a "chorus monolith" as I was told, is being shot in the end.

### Reproduction Steps

1. Shoot "chorus monolith" in the end

### Crash Report or Log

https://pastebin.com/TDisVkfj

### Operating System

Server Crash - Exaroton server

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
Remove the Warden and Schulk mod
