### ISSUE TITLE
Error loading modpack.

### ISSUE THREAD

**Issue by Thicketts** [LunaPixelStudios/Better-Minecraft#362]
### Describe the Bug

Upon first load up of the most recent edition of Better Minecraft 1.18.2 for Forge I receive an error loading Additional Additions which makes the game unplayable.

### Reproduction Steps

1.Download Mod
2.Click Play
3.Wait for Loading
4.Error Screen
...

### Crash Report or Log

https://pastebin.com/d6psXn2g

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v9

### Optifine

No

### Other Mods

No other mods added

**Comment by SharkieTV** [comment]
Did you try running it again or you tried once and gave up? Sometimes some mods randomly dont want to load
