### ISSUE TITLE
Advancements disappear on reload

### ISSUE THREAD

**Issue by da-d1** [LunaPixelStudios/Better-Minecraft#363]
### Describe the Bug

Advancements work normally until exiting and reloading world. On reload, advancements screen says "There doesn't seem to be anything here..."

### Reproduction Steps

1. Create world
2. Unlock any advancement
3. Exit world
4. Load world
5. Check advancements screen

### Screenshots and Videos

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86082458/167985821-47a93eb5-937f-400b-ad09-a46cc346e1e4.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86082458/167985921-c12b9f03-44d0-45d1-abf3-7551c477156a.png">

### Crash Report or Log

https://pastebin.com/wuXmytjq

### Operating System

macOS Big Sur 11.4

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v9

### Optifine

No

**Comment by camjoh24** [comment]
i've been having the same issue.

**Comment by SharkieTV** [comment]
will be fixed in next update
