### ISSUE TITLE
Missing Andesite textures

### ISSUE THREAD

**Issue by seveig** [LunaPixelStudios/Better-Minecraft#365]
### Describe the Bug

There is 3 missing textures for the Andesite copper ore iron ore and coal ore.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC V9

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Duplicate #336
