### ISSUE TITLE
The Chunkloader in the Quest Book is Missing

### ISSUE THREAD

**Issue by ChivalKnight** [LunaPixelStudios/Better-Minecraft#368]
### Describe the Bug

The chunkloader shows as 'missing' in the quest book in the rewards panel for the void lilly, and the mod for it, Sentimentality 3, was removed in V7 of this modpack.  It would be nice to have a chunkloader for Tom's Simple Storage Mod.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Missing Reward Item](https://user-images.githubusercontent.com/105532842/168411857-af9427f9-7e25-4e02-bbcb-76b8afd74e4b.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v9

### Optifine

No

**Comment by SharkieTV** [comment]
Thanks will remove it from quests as the mod was removed
