### ISSUE TITLE
Minecraft 1.18.2 better minecraft [forge] bug

### ISSUE THREAD

**Issue by kotsuki017** [LunaPixelStudios/Better-Minecraft#369]
### Describe the Bug

i can't add any other mods on this modpack[forge 1.18] 
when i try to add some mods i need that there are all last updated after the forge 40.1.19 offered just like the modpack used it crashed so i don't think it is a mod issue but a modpack issue 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

### Other Mods

i can't do this

**Comment by SharkieTV** [comment]
If the mod doesnt work with the modpack I cant do anything about it, its not my job to fix an issue that you are trying to do, i can add mods fine
