### ISSUE TITLE
Flax right click shows wired image

### ISSUE THREAD

**Issue by ZzingH** [LunaPixelStudios/Better-Minecraft#37]
### Describe the Bug

Hi, I’m using the version V12.5 forge sever. And game version 1.18.1 with forge 39.022.

Few hours ago, I planted a flax seed and wait till it matured. After I use right click to the matured flax, suddenly turn to a wired man face instead of beautiful blue flowers.

Not sure which mobs caused the issue, so far all the other thing works fantastic, thank you for your hard work to made this modpack, if there anything not clear in this report, please let me know if I can provide anything to make it clear. Thank you.

### Reproduction Steps

1.Planted a flaxseed.
2.Wait till it matured.
3.Use right click to matured flax.

### Screenshots and Videos

![4A729191-856D-44EA-B468-085AD183D1F4](https://user-images.githubusercontent.com/97979547/149995400-7d59ad2e-8f49-42ec-88fb-5c275ed945b5.jpeg)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

12.5 server

### Optifine

I used Optifine

### Other Mods

QuickHomes made by itsmeowdev 
QuickTeleports made by itsmeowdev

**Comment by SharkieTV** [comment]
That is caused by the mod
