### ISSUE TITLE
Missing file for mod "Advanced Netherite"

### ISSUE THREAD

**Issue by blanketless** [LunaPixelStudios/Better-Minecraft#370]
### Describe the Bug

unable to install better minecraft fabric 1.18.2

### Reproduction Steps

1.click install
2. fail
3.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/105561342/168443216-a8b806b6-d49e-4904-81fa-2c5ad701a749.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
Not an issue with the Modpack, issue with CF Launcher, either try installing it again or ask in their discord
