### ISSUE TITLE
BUG Redstone (still not fixed): Honey blocks stick to slime blocks when pushed by piston ON SERVER

### ISSUE THREAD

**Issue by Frodon69** [LunaPixelStudios/Better-Minecraft#371]
### Describe the Bug

So I was trying to make a two wide flying machine bridge and it kept breaking down ... I eventually found that when placing honey blocks adjacent to slime blocks and only pushing the honey block with a piston, the slime block followed. In regular minecraft slime blocks do not stick to honey blocks...
It is worth mentionning that when i push the slime block there is no bug. It is really only if the honey block is pushed.

Hence there must be a mod which breaks this mechanic.

PS: this is on server and v9 of the modpack

### Reproduction Steps

1. place sticky piston down facing up
2. place down honey block on face of the piston
3. place slime block adjacent to the honey block
4. activate piston and see that the slime block is taken as well

Notice that if the the slime block is pushed instead of the honey block the bug does not occur.

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v9

### Optifine

No

**Comment by SharkieTV** [comment]
remove the bumblezone mod but it will cause a datapack error so you have to delete the dimension aswell in level.dat file
