### ISSUE TITLE
Game Crashes when I open the map

### ISSUE THREAD

**Issue by Trisckyt** [LunaPixelStudios/Better-Minecraft#373]
### Describe the Bug

I was lost in the nether and opened my map to figure out where to go but it crashed upon opening.

### Reproduction Steps

1.Enter the world.
2.Open map.
3.Crash
...

### Crash Report or Log

https://pastebin.com/Bd0sbQVi

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by SharkieTV** [comment]
seems liek a waypoint on xearos map has caused it, do you know any waypoints you made and what they were?
If not can you just delete your xaero map data from the modpack folder

**Comment by Trisckyt** [comment]
> seems liek a waypoint on xearos map has caused it, do you know any waypoints you made and what they were? If not can you just delete your xaero map data from the modpack folder

I tried deleting the map data from the folder and that didnt work but I figured out that the map works when there are 0 waypoints on it so I just disabled waypoints on the world map. I can set way points now and open the map.

**Comment by SharkieTV** [comment]
Thanks ill report it to the dev
