### ISSUE TITLE
Server chrashing for [FABRIC] 1.18.2

### ISSUE THREAD

**Issue by pentatrax** [LunaPixelStudios/Better-Minecraft#375]
### Describe the Bug

Im honestly not sure how it happened, since the server worked fine for about 4 hours. Afterwards we left it on over night and after trying to join again, the server chrashes if a player tries to join everytime.

### Reproduction Steps

1. Make a server play on it for some time
2. Leave overnight (Might even happen after a single restart)
3. Make a player join the server
4. Server crashes

### Crash Report or Log

https://pastebin.com/gZqDiq1G

### Operating System

Tried on both Windows 10 and Linux

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by SharkieTV** [comment]
Did you update from v9?

**Comment by CrimsonSoul** [comment]
I can confirm this issue. It appears adding back the advancements debug mod fixes this. This mod was removed with v10 for some reason.

**Comment by SharkieTV** [comment]
Yeah that was what I was going to say, the mod advancements debug is removed due to breaking advnacanents and not showing any so the only fix is adding it back in
