### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by LoafofBread11** [LunaPixelStudios/Better-Minecraft#377]
### Describe the Bug

Running the server crashes every time, not really sure how to fix it. Using Java 17 I'm pretty sure.

### Reproduction Steps

1.Run ./start.sh
2.Server crashes on startup
3.
...

### Crash Report or Log

https://pastebin.com/ZtRcgxBm

### Operating System

Fedora 36

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V10

### Optifine

No

**Comment by SharkieTV** [comment]
it says the mod Curious Elytra failed to load, did you try to run it again or donwload the serverpack again?

**Comment by LoafofBread11** [comment]
Yes I redownloaded the server pack from scratch, tried running several times and ran into the same issue every time

**Comment by SharkieTV** [comment]
The mod curiouselytra-forge-1.18.1-5.0.1.0.jar is failing to load and not sure why. Remove it
