### ISSUE TITLE
Cannot craft certain items

### ISSUE THREAD

**Issue by TH3P1NK5T3R** [LunaPixelStudios/Better-Minecraft#378]
### Describe the Bug

Hello! I was playing the 1.18.2 Forge version of Better Minecraft and noticed that I could not craft certain items, most notably Windswept Sandstone from the "Oh the Biomes You'll Go" mod (from Windswept Sand that is) and the specialty workbenches for the "Chipped" mod (AKA Shepherd's Table, Carpenter's Table etc.). For the latter in particular, I cannot craft them using different variants of crafting table; I can only use the classic Oak. If you guys have any way of resolving this, that'll be great! Thanks!

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/105680957/168697409-d23fb326-9193-48ae-8ee1-a3ba886d2395.mp4

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Version v10 Beta

### Optifine

No

**Comment by SharkieTV** [comment]
The Chipped mod has not made it to be compatible with modded crafting tables. I might or might not add a script for it ill see
