### ISSUE TITLE
Can't access Shaders

### ISSUE THREAD

**Issue by Bohemiangrove666** [LunaPixelStudios/Better-Minecraft#379]
### Describe the Bug

I read another post similar like this but the owner of this mod just said that it was not properly installed but no solution, so here I am.

I'm installing Better Minecraft Plus and I'm using the server .rar pack, but when I go to .config it lacks the option to use shaders, and the game performs poorly, the interface also changes compared to Singleplayer. What am I doing wrong? What should I install in order to get the fancy interface and shaders?

### Reproduction Steps

1. Install Better+Minecraft+Server+Pack+[PLUS]+v10.
2. I place the Better+Minecraft+Server+Pack+[PLUS]+v10 mod folder in my .minecraft folder. 
3. Run the game.
4. Check config, no shaders.
...

### Screenshots and Videos

![2022-05-16_20 24 56](https://user-images.githubusercontent.com/105663224/168708500-0f92b2e8-490d-429c-951c-1df3e62bbccc.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

### Other Mods

![image](https://user-images.githubusercontent.com/105663224/168706830-487c238b-c28f-47c0-88c8-3d9ed84249f7.png)

**Comment by SharkieTV** [comment]
Thats not how you install a modpack, use a launcher
