### ISSUE TITLE
OPs becoming immortal/creative

### ISSUE THREAD

**Issue by panromir** [LunaPixelStudios/Better-Minecraft#38]
### Describe the Bug

I believe ever since Update 12 in the Forge 1.18 Version of Better MC, whenever I reconnect to my server, I am immortal. Not only that, but mobs also ignore me and PVP doesn't damage me.

It's as if I was specifically in creative mode, but setting my mode explicitly to survival doesn't change the behavior, only using /kill will fix it, until the next reconnect.

### Reproduction Steps

1. Reconnect to the server
2. Be immortal
3. use /kill on self
4. be mortal
5. reconnect
6. be immortal again

### Operating System

Linux Server on Docker

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v13

### Optifine

I used Optifine

### Other Mods

Adaptive Performance Tweaks 2.0.0, Dynmap 3.3b4

**Comment by Auseawesome** [comment]
Does this occur without added mods?

**Comment by panromir** [comment]
Maybe I should have tried this before creating a ticket. I could indeed narrow this down to adaptive performance tweaks. Sorry!
Closing
