### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by AFKfreak** [LunaPixelStudios/Better-Minecraft#381]
### Describe the Bug

There's a texture error with Andesite Ores, and Mushroom Bark

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-05-17_17 57 55](https://user-images.githubusercontent.com/105736864/168856118-3e104f86-1b41-4b52-9876-ec4fa21972d0.png)
![2022-05-17_17 56 13](https://user-images.githubusercontent.com/105736864/168856123-4996b17b-df9a-42f1-aadc-77b5b6b64e03.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

forge 40.1.19

### Optifine

No

**Comment by SharkieTV** [comment]
Duplicate https://github.com/LunaPixelStudios/Better-Minecraft/issues/336
