### ISSUE TITLE
still having the v9 broken advancements issue

### ISSUE THREAD

**Issue by camjoh24** [LunaPixelStudios/Better-Minecraft#382]
Describe the Bug
On a fresh installation of v10, the same issue as #363 

Reproduction Steps
1. Create a new world
2. Load world and create a crafting table to unlock the advancements menu
3. Save & quit
4. Reload world and open the advancements menu

Crash Report or Log
https://pastebin.com/8NHcLzmw

Operating System
Windows 10

Minecraft Version
1.18.2

Modloader
MultiMC/Fabric

Modpack Version
Version v10

Other Mods
No

**Comment by SharkieTV** [comment]
This is so frustrating, it seems it is not fixed. I'll try to put put a hotfix today but I will see
