### ISSUE TITLE
Cannot launch Better Minecraft v10.5 on fabric.

### ISSUE THREAD

**Issue by SuperBABA38** [LunaPixelStudios/Better-Minecraft#384]
### Describe the Bug

Hello, I play Better Minecraft and since the version 10.5 is here, I cannot launch my game because of the mod "You're in Grave Danger".
Here is the crash report below.

### Crash Report or Log

https://pastebin.com/enajSApt

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft v10.5

### Optifine

No

**Comment by SharkieTV** [comment]
Ill do a hot fix for this
