### ISSUE TITLE
Unable to import v10.5 into MultiMC

### ISSUE THREAD

**Issue by camjoh24** [LunaPixelStudios/Better-Minecraft#385]
### Describe the Bug

Trying to import v10 of Better Minecraft as a new MultiMC instance is blocked by the error message "Job 'Mod download' failed to process:"

### Reproduction Steps

1. Download the latest v10.5 HF version of Better Minecraft
2. Drag and drop the .zip file into the MultiMC window
3. Watch the progress bar fill up and freeze around 99%

### Screenshots and Videos

![MultiMC_kfZr9cY6C3](https://user-images.githubusercontent.com/2850130/169148444-7bb80908-e599-4bf5-b42f-f33e2a81e00c.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v10.5 HF

### Optifine

No

**Comment by SharkieTV** [comment]
I have no issues installing it, maybe try another launcher

**Comment by Angular-Angel** [comment]
I'm currently also having issues installing v10 in multimc, it says some of the mod IDs can;t be resolved - though it doesn't say which ones.
