### ISSUE TITLE
Server wont start upon last reset.

### ISSUE THREAD

**Issue by Legned00** [LunaPixelStudios/Better-Minecraft#386]
### Describe the Bug

After my server i host with better Minecraft was restarted it keeps giving me an error and crashes. It seems its because of a few mods but I'm not 100% sure.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Legned00/94a407149bf64d4fee753832d115dabe

### Operating System

windows 10 

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft v10 

### Optifine

No

**Comment by SharkieTV** [comment]
When you restarted did you get rid of the World folder? are you using the correct configs? make sure to replace everything

**Comment by Legned00** [comment]
Forgot to mention the server is through g-portal so I'm not sure how to get to the world folder. It was running fine up until the daily restart i have set, then keeps giving errors since.

**Comment by SharkieTV** [comment]
it says mods are loading to fail so i can only assume its and issue with the server host or possibly the world but you said you restarted so did you delete the old world?

**Comment by Legned00** [comment]
I didn't restart the world, it was the daily restart of the server that happens at midnight every day that i have set to automatically do. Yesterday is the only time I've had a problem with it.

**Comment by SharkieTV** [comment]
Ok since it says dqu.additionaladditions.config.Config.load, it cant load the config correctly, can you delete the additionaladditions config in the config folder where the server folder is located and maybe see if their is a config of the additionaladditions in the world folder > serverconfig

**Comment by carguygamer** [comment]
I encountered this same issue, Mods not loading correctly after restart. Deleting additionaladditions config in the config folder, Allowed the server to start up and generate a new additionaladditions config.
