### ISSUE TITLE
[FORGE] Can't get villager to get jobs from the More Villagers Mod

### ISSUE THREAD

**Issue by PinaTutorials** [LunaPixelStudios/Better-Minecraft#387]
### Describe the Bug

If I try to place down any of the new workplaces provided by the More Villagers mod, no villagers, unemployed or not, will assume the job.

### Reproduction Steps

1.Get a Villager
2.Place down the workplace block, 
3.The villager won't get his job
...

### Screenshots and Videos

![2022-05-19_22 08 45](https://user-images.githubusercontent.com/41023844/169405136-84eeb10e-6753-46b4-92aa-7be255800797.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] - 1.18.2 V8

### Optifine

No

### Other Mods

Removed a mod called Allay, as it was causing excessive entity counts.

**Comment by SharkieTV** [comment]
This would only happen if you dont use the correct configs. so so idk if this is MP or SP but whatever you did was wrong and please use the configs that are shipped with the pack
