### ISSUE TITLE
Server Won't Allow Anyone To Join

### ISSUE THREAD

**Issue by LiviqOU** [LunaPixelStudios/Better-Minecraft#389]
### Describe the Bug

Using the server pack provided I tried to run a server but whenever anyone tries to join the server we are greeted with an error saying "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2532363 into 3".  I have looked around and can't seem to find a solution as the only one I have found is to delete the scoreboard.dat file but due to it being a brand new world and nobody ever joining it there isn't one to delete.

### Reproduction Steps

1. Start the server
2. Join the server
3. Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2532363 into 3
...

### Screenshots and Videos

![Screenshot 2022-05-20 022126](https://user-images.githubusercontent.com/105906044/169465592-bf876a76-434c-4c34-91d7-07540192c55d.png)

### Operating System

Window

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft [plus] v10

### Optifine

No

### Other Mods

- Epic Fight 
- Cyclic
- Dimensional Dungeons
- Mystical Agriculture
- Mystical Agradditions
- Doggy Talent
- Meet Your Fight
- Origin
- Origin ++
- Improved Mobs
- Sons of Sins
- Mahou Tsukai

**Comment by SharkieTV** [comment]
Unfortunately due to you adding so many mods I wont help as their is no issue with this in the Modpack and that its the mods you added

**Comment by LiviqOU** [comment]
Do you at least know what I should be looking for because I don't know in the slightest what this error means

**Comment by SharkieTV** [comment]
Well if this happened to me I would do a lot of testing to find out what mod it is so start by removing the mods 1 by one

**Comment by LiviqOU** [comment]
Ok will do, I was just confused since single-player worlds were working fine.

**Comment by SharkieTV** [comment]
yeah some things dont work the same on MP, this is why things get tested for hours
