### ISSUE TITLE
Crash Loading in 

### ISSUE THREAD

**Issue by nyobb** [LunaPixelStudios/Better-Minecraft#39]
### Describe the Bug

Minecraft loads up, I click my apex server and then get,
java.lang.nullpointerexception unexpected error exit code -1 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Window 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v53

### Optifine

No

**Comment by switchnlade** [comment]
Can we get the latest.log for whatever is crashing? Crash report too if that generated. Currently with just that little bit of info, we can't help.

**Comment by nyobb** [comment]
This is all I have

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by nyobb** [comment]
wait that didnt work
[crash-2022-01-18_20.45.50-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7893499/crash-2022-01-18_20.45.50-client.txt)
this

**Comment by switchnlade** [comment]
Remove Fallingleaves from the mods folder

**Comment by nyobb** [comment]
This is on a server so should I remove it only on my side or on the servers side

**Comment by nyobb** [comment]
I am the host, I am reporting this for one of the players

**Comment by switchnlade** [comment]
Have the player do what I said for their client

**Comment by nyobb** [comment]
I am so sorry, I am completely new to this and have no knowledge, would they go to their download of better minecraft, mods, then look for fallingleaves and then delete it

**Comment by switchnlade** [comment]
Yep, it'll be in their mods folder, just have them delete and try loading once more

**Comment by nyobb** [comment]
This is after they deleted the mod

**Comment by SharkieTV** [comment]
Your player has only allocates 3gb to the game which is not enough, and are they using a cracked version of the game?

**Comment by nyobb** [comment]
no they're downloading it off curseforge

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by nyobb** [comment]
so they added more 6gb of allocated and same thing occurred

**Comment by nyobb** [comment]
[crash-2022-01-18_23.24.16-client_m.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7894054/crash-2022-01-18_23.24.16-client_m.txt)

**Comment by nyobb** [comment]
This crash is with the fallingtrees deleted and 6gbs of allocated memory

**Comment by nyobb** [comment]
[crash-2022-01-18_23.54.23-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7894169/crash-2022-01-18_23.54.23-client.txt)
This is prob the last report of the night, I updated the server to v54 on curse forge, and this is what happened. I have no idea, they have 6gbs of allocated mem, its just this crash that keeps on happening. They were fine playing 2 days ago with no crashes. This just does not let them play the modpack

**Comment by SharkieTV** [comment]
I see they added a mod called Controlling and that's what's causing it, please don't report issues when you modify the pack
