### ISSUE TITLE
Fabric server "lagging out" and eventually crashing.

### ISSUE THREAD

**Issue by grimbebo** [LunaPixelStudios/Better-Minecraft#390]
### Describe the Bug

Server works perfectly fine, until at random intervals it HARD freezes and all players disconnect. This will persist until the console is interacted with and even a simple "enter" will suffice. After the input is made the game snaps back instantly processing all ticks and starts working again with no issues. As of this morning if it goes on for too long it just crashes when I interact with the console again.

### Reproduction Steps

1. Let server run
2. ????
3. Server lags
4. Interact with server and it works, or don't and it crashes
5. Either the server works again for X amount of time, or it crashed and I'll have to reload.
...

### Crash Report or Log

https://pastebin.com/q8DThYrs

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Fabric V3? The most recent version

### Optifine

No

### Other Mods

There are no other mods added to the pack.

**Comment by grimbebo** [comment]
I will note my hardware.

Ryzen 5800x
Nvidia 3060ti

32 gb DDR4 ram
etc

It has no problem running league, modded minecraft, the server, and stardew valley all at once.
So it's not a system lag problem.

**Comment by grimbebo** [comment]
It was a command prompt issue causing the crashes.
"Turning off quick edit mode in the command prompt solves this problem."

**Comment by SharkieTV** [comment]
Quick edit mode? can you show me it?
