### ISSUE TITLE
No Ender dragon

### ISSUE THREAD

**Issue by Xavegon** [LunaPixelStudios/Better-Minecraft#391]
### Describe the Bug

hey i was playing on my friend server and when we arrived in the end the bossbar didn't  showed up an when we got to the island we didn't seen any dragons or portal there was some <nullstone> small block pile in the middle and the but the obsidian towers where here and the end crystals too we tried to reset the end but the same thing happened still no portal and still no dragon if someone know why

### Reproduction Steps

1. Enter the end
2. ??????
3. No portal

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

### Other Mods

i did not add any other  mods

**Comment by SharkieTV** [comment]
Reset your end dimension by deleting the DIM1 folder
