### ISSUE TITLE
Chisels and bits modells can be picked up and cause client crash (Better Minecraft [PLUS])

### ISSUE THREAD

**Issue by gike12** [LunaPixelStudios/Better-Minecraft#392]
### Describe the Bug

If you build anyting with chisels and bits and accidentally shift rigth click with bare hand the game crash with java.lang.NullPointerException.

### Reproduction Steps

1.Build anything with chisels and bits
2.Try to pick up with shift right click
3.Crash the client

### Crash Report or Log

https://gist.github.com/gike12/2cf5a8c2934602abefe84cafb63bf082

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

**Comment by SharkieTV** [comment]
Will be fixed in next version but its not supposed to be picked up like that with the carry on mod
