### ISSUE TITLE
XAREO MAP CRASH MY GAME

### ISSUE THREAD

**Issue by greekninja1988** [LunaPixelStudios/Better-Minecraft#394]
### Describe the Bug

i play with the mod pack as normally and when i press M to open the map it crashes

### Reproduction Steps

1.I I open the game
2.I load my world
3.I press M to open the xareo map
4.I crash

### Screenshots and Videos

i don'd have a screenshot or a video i have the crash report 
[crash-2022-05-22_11.11.54-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8749373/crash-2022-05-22_11.11.54-client.txt)

### Crash Report or Log

it is in the screenshot and video step

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v10

### Optifine

No

### Other Mods

not any new mod

**Comment by SharkieTV** [comment]
Can you delete the Xaeros Map data and see if that fixes it?

**Comment by greekninja1988** [comment]
you mean delet the mod?
and re install it?

**Comment by SharkieTV** [comment]
Was not meant to close that, in the modpack folder delete the Xaero folders

**Comment by greekninja1988** [comment]
wait let me try this

**Comment by greekninja1988** [comment]
there are 3
XaeroWaypoint
XaeroWaypoint_backup
XaeroWorldMap
which one?

**Comment by greekninja1988** [comment]
all of them?

**Comment by greekninja1988** [comment]
oh you said xaero folders ok wait

**Comment by greekninja1988** [comment]
done

**Comment by greekninja1988** [comment]
now?

**Comment by greekninja1988** [comment]
are you still here?

**Comment by Spielsucht24** [comment]
Did it work @greekninja1988 ?
