### ISSUE TITLE
Unable to play Better Minecraft [Fabric] at all in v18

### ISSUE THREAD

**Issue by craftingmaster13** [LunaPixelStudios/Better-Minecraft#395]
### Describe the Bug

I have no idea the true cause of this bug, but I cannot open any world, single or multiplayer in v18. If I attempt to, my game immediately crashes, showing an error message. No matter what version I have tried, the result is always the same. I have yet to play a single world on v18 because of this issue. If it is a problem with my tech or download specifically, I have no Idea how to fix it. A picture is posted below of the crash message.

### Reproduction Steps

1. Start running Better MInecraft [Fabric] v18
2. Once at the home screen, choose either singleplayer or multiplayer
3. Choose any world in it's respective section, or make a new world
4. Try to load said world.
5. All standard world loading messages play, and right as the world flashes onto the screen, the screen switches to 'Saving World' and shuts down the whole program, showing an crash error message on the launcher.

### Screenshots and Videos

![Screenshot 2022-05-22 143853](https://user-images.githubusercontent.com/106032063/169710823-02e1f23c-a214-4753-b235-72f0fbf6852a.png)

### Crash Report or Log

https://gist.github.com/craftingmaster13/dcf3e8aa6d37d1b9e33ce47e4e723c86

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v18

### Optifine

No

**Comment by SharkieTV** [comment]
1.17.1 is outdated and not supported to me it seems your mods are mismatched to the client
