### ISSUE TITLE
Resourec Pack Issue

### ISSUE THREAD

**Issue by JReade1995** [LunaPixelStudios/Better-Minecraft#396]
### Describe the Bug

Installed Better Minecraft [PLUS] loaded in the Faithful 32x Modded resource pack off Curse Forge for 1.18. Loading into a world some textures are remaining at the base minecraft resource pack.

### Reproduction Steps

1. Download & Install Better Minecraft [PLUS] - 1.18.2
2. Load in this resource pack https://www.curseforge.com/minecraft/texture-packs/faithful-32x
3. Create new world and load in.
4. Find/Spawn some base minecraft blocks (Planks, Stone, Dirt etc)
...

### Screenshots and Videos

![Untitled 1](https://user-images.githubusercontent.com/68743444/169898418-172457fa-bbd7-4b3a-bba4-c2f3f07a119f.png)
![Untitled 2](https://user-images.githubusercontent.com/68743444/169898424-e241b28a-7e27-4411-898d-d73408d0edcb.png)
![Untitled 3](https://user-images.githubusercontent.com/68743444/169898428-b03917ab-9585-4a07-9005-c239f4de9e38.png)
![Untitled](https://user-images.githubusercontent.com/68743444/169898434-f693d103-aff7-48ce-b3d7-f46f7f8a82e0.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] - 1.18.2

### Optifine

No

### Other Mods

N/A

**Comment by SharkieTV** [comment]
Not an issue with the modpack

**Comment by tinxkight** [comment]
This was actually an issue the Stay_True resource pack. I was testing Mizuno's for a friends since a lot of their blocks were staying the same as previous. Just remove Stay True from the selected resource pack list and it should be good.
