### ISSUE TITLE
Freed wandering tradre llamas trying to breed crash the server

### ISSUE THREAD

**Issue by DorthLous** [LunaPixelStudios/Better-Minecraft#4]
### Describe the Bug

Freeing wandering trader's llamas and attempting to breed them immediately crash the server.

### Reproduction Steps

1.Find a wandering trader villager
2.Free both llamas with Llama Key items from the https://www.curseforge.com/minecraft/mc-mods/villager-tools mod
3.Use hay bales on both of them to make them reach the breeding state
4.Let them attempt to breed
5.The server crash the moment they attempt to do so

### Operating System

Arch Linux

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v52.5

### Optifine

No

**Comment by switchnlade** [comment]
Issue report filed for this crash on Villager Tool's GitHub page, awaiting response and fix from the mod author.
Current solution: Avoid breeding llamas freed through the liberation key.

**Comment by SharkieTV** [comment]
The issue has been reported here: https://github.com/Lothrazar/VillagerTools/issues/8
Solution is to not breed them currently, next update will either remove the key or fix the issue with a mod update.
