### ISSUE TITLE
Minecraft Crashes in the Blue Skies Dimensions

### ISSUE THREAD

**Issue by Claudiaxxx1** [LunaPixelStudios/Better-Minecraft#40]
I went into the Brightdawn dimension and was greeted with a crash, now when I log into my server it works for 3 seconds and then it crashes again. I would assume that it works the exact same in the other blue skies dimension
[crash-2022-01-18_17.37.14-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7893491/crash-2022-01-18_17.37.14-client.txt)
.

**Comment by Claudiaxxx1** [comment]
This is the 1.16.5 53.5 version by the way

**Comment by SharkieTV** [comment]
Please use the template next time, see if removing immersive FX (server and client) fixes the issue.

**Comment by Claudiaxxx1** [comment]
Removing Immersive FX fixed the issue, thank you! I can now move around and leave the dimension.
