### ISSUE TITLE
endles poison and stavation after tnt use 

### ISSUE THREAD

**Issue by drokmani** [LunaPixelStudios/Better-Minecraft#401]
### Describe the Bug

after using a certain amount of tnt i get stuck with endless poison and starvation no matter what i do it doesn't go away. i have tried dying, milk, food, golden and enchanted golden apples, golden carrots, water, dying by a creeper. everything it just persists.

### Reproduction Steps

1.set off tnt one after the other 
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft plus

### Optifine

No

**Comment by SharkieTV** [comment]
Which version are you playing on?

**Comment by SharkieTV** [comment]
no i mean which specific modpack version like v11?

**Comment by drokmani** [comment]
v5

**Comment by SharkieTV** [comment]
Your and outdated version so I will close this
