### ISSUE TITLE
Pickaxes dont work in the v11 update of Better minecraft forge

### ISSUE THREAD

**Issue by TheOneTruFrosty** [LunaPixelStudios/Better-Minecraft#402]
### Describe the Bug

As the title says. I have tested nearly every pickaxe I could get at the progression level I am at (early nether) and none of them work.

### Reproduction Steps

1.Craft pickaxe
2.Equip Pickaxe
3.Try to mine
...Fail

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v11

### Optifine

No

### Other Mods

https://user-images.githubusercontent.com/106285405/170387678-83914298-1923-44b1-bd8e-fa7c353c8b7d.mp4

**Comment by ShenCobra** [comment]
Yeah they dont work Im having the same problem

**Comment by tiredabigail05** [comment]
i just downloaded this pack and im having the exact same problem

**Comment by semioniy** [comment]
As a temporary solution, you can roll back to 10.5 (just did that myself). World seems to be compatible, but I'd still make a backup JIC.

**Comment by SharkieTV** [comment]
fixed in v11.5
