### ISSUE TITLE
Pickaxes not working 

### ISSUE THREAD

**Issue by tiredabigail05** [LunaPixelStudios/Better-Minecraft#403]
### Describe the Bug

When I try and mine with any vanilla pickaxe, because that's all I've been able to get to so far, it just's treats it as I am mining the block with my fists.  

### Reproduction Steps

1.Craft Pickaxe
2. Equip Pickaxe
3. Try to mine block that I know for sure can be mined with that pickaxe
4.Block takes 10 years to break
...

### Operating System

Windows 10 Home Edition

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V11

### Optifine

No

**Comment by semioniy** [comment]
I noticed that it's not so a pickaxe not working, but blocks that normally are broken with pickaxe that are extremely robust. Pickaxe works just fine with dirt/wood, but breaks stones as if they're obsidian^2. 
Had to learn this the hard way when I was underwater - no solid ground and underwater debuff - I had a breathable air pocket, but it took me 4 minutes to break a block above me.

**Comment by tiredabigail05** [comment]
> 

so is there a fix?

**Comment by tiredabigail05** [comment]
> I rolled back to 10.5, no compatibility issues I see so far. Waiting for the fix as well.

how do i go back  a version?

**Comment by semioniy** [comment]
![image](https://user-images.githubusercontent.com/21012972/170395410-4e2915b2-8048-461c-b0b5-a5b1748e0cd6.png)

**Comment by semioniy** [comment]
P.S. 11.5 seems to have solved the issue.

**Comment by SharkieTV** [comment]
fixed in v11.5
