### ISSUE TITLE
Game crashes when placing a Mechanical Press

### ISSUE THREAD

**Issue by mtsweir** [LunaPixelStudios/Better-Minecraft#404]
### Describe the Bug

Placed a **Mechanical Press** on the ground and it crashes, it doesn't load the item the next time I load the game (see screenshot) it crashes immediately when the game loads.

```
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Cannot use BufferBuilder with format: 9 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte mc_Entity=2,Generic,Short mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Byte
Exit Code: -1
```

### Reproduction Steps

1. Placed a **Mechanical Press** on the ground
2. Game freezes and crashes
3. Try to load the game again, and starts in the same spot and freezes immediately, then crashes

### Screenshots and Videos

![bmc-plus-v10](https://user-images.githubusercontent.com/4976660/170465462-66402597-ff3e-4dff-abbd-9cfee89e4b31.jpg)

### Crash Report or Log

https://pastebin.com/x2SHJeAR

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC Plus Edition v10

### Optifine

No

### Other Mods

- BSL Shaders v8.1.02.2
- ComplementaryShaders v4.4

Both inside a **shaderpacks** folder

**Comment by SharkieTV** [comment]
Need crash report from the crash folder in the modpack folder

**Comment by mtsweir** [comment]
Thanks, for getting back so quickly - I'll upload that later today.

**Comment by mtsweir** [comment]
> Need crash report from the crash folder in the modpack folder

Just a quick question, where would I find that?

**Comment by SharkieTV** [comment]
Where ever you saved it? If your using CF Launcher just go to the modpack and click the 3 dots

**Comment by mtsweir** [comment]
Here are the crash reports, all I think are related to the same issue.

[crash-2022-05-26_22.06.41-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8784400/crash-2022-05-26_22.06.41-client.txt)
[crash-2022-05-23_21.43.13-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8784401/crash-2022-05-23_21.43.13-client.txt)
[crash-2022-05-23_21.46.54-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8784402/crash-2022-05-23_21.46.54-client.txt)
[crash-2022-05-23_21.57.22-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8784403/crash-2022-05-23_21.57.22-client.txt)
[crash-2022-05-26_21.49.16-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8784404/crash-2022-05-26_21.49.16-client.txt)

**Comment by SharkieTV** [comment]
Disable Flywheel in your config folder
