### ISSUE TITLE
game not opening

### ISSUE THREAD

**Issue by rama9421** [LunaPixelStudios/Better-Minecraft#405]
### Describe the Bug

when i join a world it shows datapacks wont work and has 2 options 1 safe mode and 2 title screen for manual work both of em are not workin :Also it is on version 11.5 for 1.18.2 and fabric version

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/106326845/170501551-4c3418e7-db7e-428d-bbd9-51c4e2507a2e.png)
![Uploading image.png…]()

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v11.5

### Optifine

No

### Other Mods

sodium extra

**Comment by SharkieTV** [comment]
Need the latest.log and did you update from an older world?

**Comment by rama9421** [comment]
No i installed it freshly from curseforge

**Comment by SharkieTV** [comment]
If its a fresh install it doesnt make sense. I can install fine and create a world. Send your latest.log

**Comment by rama9421** [comment]
ok will chuck it
