### ISSUE TITLE
Game crashes instantly on start up, cant even see the Minecraft menu.

### ISSUE THREAD

**Issue by EyyOhItsTaco** [LunaPixelStudios/Better-Minecraft#407]
### Describe the Bug

I updated the version to v11, (I'm on java) and so did my friend (who is also on java). He was fine and was able to play Minecraft. When I open the game on the curse forge launcher and press play the Minecraft launcher pops up, and when I press play it loads up, and then the game opens and there's a white screen, up in the top left where the game name is it says Minecraft 1.18.2 (Not Responding). I've tried to reinstall Curse Forge, and tried reinstalling regular Minecraft. none of that works. I gave it max Memory, and nothing, same outcome. I let it sit for 3 hours and nothing. When I close it out it says this Error Code:
![gfdgfd](https://user-images.githubusercontent.com/106367898/170636712-4a9ea01c-8835-473a-a898-bc15b1b0abc7.PNG)  earlier it said: Error: java.util.ConcurrentModificationException: null Exit Code: -1, (I wasn't able to get a picture of it)
I feel its on my end but I don't know where to start. if someone were to help me, thank you. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![gghfgh](https://user-images.githubusercontent.com/106367898/170636365-ce714894-6635-402c-a3f3-d8dd1d118fe6.PNG)

### Crash Report or Log

https://mclo.gs/v1sLEDD

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2 v11

### Optifine

No

**Comment by Deevomae** [comment]
I've run in the exact same issue. It was even running fine last night...

**Comment by FreestyleStorm** [comment]
have the same issue with version 11. crashes on start. not sure how this gets a release when it crashes for everyone.

**Comment by SharkieTV** [comment]
Can you see if removing the mod enhanced_mushrooms and pollen works?

**Comment by EyyOhItsTaco** [comment]
> Can you see if removing the mod enhanced_mushrooms and pollen works?

Yes, that worked. :D
