### ISSUE TITLE
Install Optiffine but problem with it 

### ISSUE THREAD

**Issue by Volstayy** [LunaPixelStudios/Better-Minecraft#408]
### Describe the Bug

I did the right things to install optifine on forge for my better minecraft 1.16.5. Desinstall magnesium and Dynamic lights after that move optifine files in files mods. I run Better minecrffat but when i enter in my serveur worlds this error appear. https://mclo.gs/yOFpx4I

And this one is when i enter in solo world. 
![Java error](https://user-images.githubusercontent.com/106379503/170678206-4175e7ef-6e78-4f4c-b025-ca4ad40fe2ba.png)

I try to reinstall entire fforge and all the stuff fbut don't work. Please help me .

### Reproduction Steps

1.Remove the [Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) & [Dynamic Lights Reforged](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
2. Open minecraft
3. Enter world 
4. Crash for long time
5. 
6.
...

### Screenshots and Videos

![Java error](https://user-images.githubusercontent.com/106379503/170678983-27a03415-a9de-429c-8fff-7cd9f72fc130.png)

### Crash Report or Log

https://mclo.gs/yOFpx4I

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft Forge v56.zip

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
It says Optifine is crashing your game and nothing else. Its not something I can help fix
