### ISSUE TITLE
Game crashes when open xaero map

### ISSUE THREAD

**Issue by Spielsucht24** [LunaPixelStudios/Better-Minecraft#409]
### Describe the Bug

So when i try to open my map the game freeze and crashes seconds after that i tryd to turn of Shader or to change shaders but it still not work.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/9Rs8vns

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

### Other Mods

Epic fight mod
Removed hd 3d skins

**Comment by SharkieTV** [comment]
Delete the Xaeros data in the modpack folder

**Comment by Spielsucht24** [comment]
Does not Work.

**Comment by Spielsucht24** [comment]
Well a bit it worked but when i click confirm it crashes again with this exit code -1 you know what helps @SharkieTV ?

**Comment by SharkieTV** [comment]
click confirm? you just delete the folder?

**Comment by Spielsucht24** [comment]
Yes all 3 Folders deleted

**Comment by Spielsucht24** [comment]
![Unbenannt](https://user-images.githubusercontent.com/106380307/170819815-80a3c993-1b51-4cab-9c12-2eb7aac46bdf.PNG)

**Comment by Spielsucht24** [comment]
I added the folders again now this D
![Unbenannt1](https://user-images.githubusercontent.com/106380307/170820306-a530df40-47b9-4d9b-bb8e-5f9b5e298850.PNG)
:

**Comment by SharkieTV** [comment]
Can you see if removing the Xaeros Map mod works?

**Comment by Spielsucht24** [comment]
yeah that works but is there no option to fix that ?

**Comment by Spielsucht24** [comment]
@SharkieTV ?

**Comment by SharkieTV** [comment]
deleting the data should fix it but your saying its not so not sure

**Comment by Spielsucht24** [comment]
With Data u mean all 3 Folders with xaeros map, waypoints and the Backup
