### ISSUE TITLE
Server not allowing players to join

### ISSUE THREAD

**Issue by sampoland** [LunaPixelStudios/Better-Minecraft#41]
Players on my server receiving the attached error.

This is typically resolved whenever the server is reset, however, this is occurring multiple times a day and we aren't always available to reset it.

Is there anything we can do to prevent this message from happening in the future?

![Server Error](https://user-images.githubusercontent.com/62923617/150064171-3aadd7f8-ace5-43ae-96d3-931ec0fae9bb.PNG)

**Comment by switchnlade** [comment]
What modpack version is this on? Should be fixed on v10.5 and up.
