### ISSUE TITLE
Textures for metal ores in andesite load as pink and black checkerboards

### ISSUE THREAD

**Issue by McFlurryface** [LunaPixelStudios/Better-Minecraft#410]
### Describe the Bug

Basically what the title says: The textures for the metal ores in andesite load as pink and black checkerboards, so no textures could be found.

### Reproduction Steps

Just opened a brand new world and went exploring for a bit in creative mode.

### Screenshots and Videos

![2022-05-27_13 53 08](https://user-images.githubusercontent.com/59805833/170694970-3548ee39-e037-4afe-8391-c88dc2890cec.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] - 1.18.2 - v10

### Optifine

No

### Other Mods

WorldEdit
BSL Shader

**Comment by FreestyleStorm** [comment]
have reported the same issue. still needs a fix

**Comment by SharkieTV** [comment]
waiting for a mod update/fix from the mod dev
