### ISSUE TITLE
Mod loading error has occurred! [Server Crash]

### ISSUE THREAD

**Issue by SenZ01** [LunaPixelStudios/Better-Minecraft#412]
### Describe the Bug

Server crashed on startup after a restart.

It happened once and i haven't been able to reproduce the crash unfortunately.

### Reproduction Steps

1.
2.
3.
...

Mentioned in the tab Above ^

### Crash Report or Log

https://pastebin.com/qdg1S0mW

### Operating System

Client Windows, Server Linux.

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

### Other Mods

X

**Comment by SharkieTV** [comment]
Its just a mod that didnt load
