### ISSUE TITLE
Several Issues with Forge v11

### ISSUE THREAD

**Issue by mincapweebertarian** [LunaPixelStudios/Better-Minecraft#414]
With the update of BM Forge to v11, several things have broken.

The game kept crashing on game initialization (Exit Code -1).
See logs here: https://mclo.gs/DHaZmzu

After deleting Better_mushrooms and Pollen from the mod folder, the game launched.

At times, the game will stop loading new chunks until I restart the game.

Also there is inconsistencies with audio. Some sounds are delayed. Others, namely combat sounds, don't play at all.

I am running Java 64bit.
8gb Ram allocated
Did a complete purge and reinstall of MC, Curseforge, and the modpack to rule out all other issues.

No issues in Vanilla MC
No issues (that I've seen) in Better MC [Fabric]

Looking at the discord, it seems that several people are having similar issues as I am.

**Comment by SharkieTV** [comment]
Was planning on removing Better_mushrooms and Pollen in next update as for the audio im unable to reproduce that
