### ISSUE TITLE
Game crashing due to Enlightened End mod

### ISSUE THREAD

**Issue by NovaRift24** [LunaPixelStudios/Better-Minecraft#415]
### Describe the Bug

We have been playing normally with 0 issues up until we killed the dragon and got elytras, when ever I approach certain parts of the end, namely the desert temple things or if I hang out in one of the newer biomes, I will crash and then cause the entire server to crash. If I do not log in the server will continue to run fine for all others but If I relog the server will crash again. The only fix is to had the admin /tp me out of the end to someplace in the overworld in the split second between my name showing up as logged in and the server crashing. Otherwise I would be unable to log in again. That would be fine, I can avoid all the crash prone areas but now someone else is crashing, only their own account not the entire server at least, but they cannot log back in period, they are not in the end they were just in their base and ran to get some emeralds for the Wandering trader and then she crashed and it won't let her back in for more than 5 seconds without booting her again. The crash report is blaming the Enlightened End mod for her even though she has no end materials and is in the overworld.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Crash Sites](https://user-images.githubusercontent.com/106467249/170859476-a970bab4-c4bc-4dd7-bd7e-1f27ae6cb01c.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

### Other Mods

n/a

**Comment by SharkieTV** [comment]
Need the crash report

**Comment by NovaRift24** [comment]
The crashes that generate a report for me have no mention of the Enlightened End mod, I can post one however. The crashes I get are ones that crash the server and send it offline for about 5 minutes then it is back up. If I log back in it will again disconnect me and recrash the server

**Comment by NovaRift24** [comment]
My most recent Crash Report




[crash-2022-05-27_02.59.06-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8793013/crash-2022-05-27_02.59.06-client.txt)

**Comment by SharkieTV** [comment]
can i get the server crash report? as client is different
