### ISSUE TITLE
chunks not loading

### ISSUE THREAD

**Issue by dklp23** [LunaPixelStudios/Better-Minecraft#416]
### Describe the Bug

no idea why but chunks will not load after entering the world. The initial chunks around the player will load but you can walk to the edge of them and they will no longer load. normally waiting or forcing the chunks to update fixes this in most modpacks but not here.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

11.5

### Optifine

No

**Comment by SharkieTV** [comment]
Whats your pc specs? or is this on a server? This doesnt happen to me so much much I can help
