### ISSUE TITLE
Issues harvesting crops in v.11.5

### ISSUE THREAD

**Issue by jlangholzj** [LunaPixelStudios/Better-Minecraft#417]
### Describe the Bug

Updated from v6.5 to v11.5 and the hoe is no longer harvesting the crops. Didn't have time to test thoroughly, current hoe was an enchanted version, will try to replicate with a vanilla hoe. Seems currently the only way to harvest is an empty fist, r-clicking with another object also does not harvest. Verified this behavior on several different crops, as well as newly planted crops.

### Reproduction Steps

1.mature crop
2.r-click using hoe or any object

### Operating System

w10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

11.5

### Optifine

No

### Other Mods

Only loaded mod is better minecraft

**Comment by SharkieTV** [comment]
It seems the Right Click Harvesting Mod updated so you can only harvest with a empty hand.
