### ISSUE TITLE
Aternos Better Minecraft server chrashing

### ISSUE THREAD

**Issue by n0yv3x** [LunaPixelStudios/Better-Minecraft#418]
### Describe the Bug

At times the crash will take place while turning on the server, then it won't start. When it does work, it'll crash after a short while of playing. This is the crash report, at another point it also talks about recourse packs, and we've encountered textures that won't load and appear as the black and hot pink box. We started this server about a week or some ago, when v10 was up, but it started happening with 11, and continues with 11.5. It keeps happening, never works for a long time and we've tried many times.

### Reproduction Steps

1. Launch the updated aternos server running better minecraft
2. It may crash due to mods not working in some way.
3. If it opens, it will crash at a random short time.
...

### Screenshots and Videos

![Screenshot_2022-05-30-22-26-23-316_com android chrome](https://user-images.githubusercontent.com/106558865/171057922-2527d511-93bd-4311-a20f-d822aadc7e16.jpg)
![Screenshot_2022-05-30-22-28-35-934_com android chrome](https://user-images.githubusercontent.com/106558865/171057927-64b1bb49-a398-487a-8165-9a3ac9439ed3.jpg)
![IMG_20220530_222926](https://user-images.githubusercontent.com/106558865/171057930-c6599329-438d-4303-81e9-211489098e57.jpg)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

No

**Comment by SharkieTV** [comment]
Remove leafcutter ants from spawning and wont help further as Aternos servers dont have enough ram to run these packs
