### ISSUE TITLE
server render distance going above set value

### ISSUE THREAD

**Issue by TameEnderman923** [LunaPixelStudios/Better-Minecraft#42]
### Describe the Bug

In the server.Properties folder I set my renderdistance limit to 8 but when  I launch the server and load in the console report to me how far it has loaded in chunks and it eventually loads past 8 render distance, I have seen this grow up to 15 render distance.

### Reproduction Steps

1.set your server.proporties render distance limit to a set number and start the server
2. join that server
3. then watch console as it the render distance/view distance grow higher and higher until your hardware cant handle it
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V54

### Optifine

No

**Comment by SharkieTV** [comment]
in the config folder in the server there is a config called dynamic view, you can change the max view distance there, It changes depending on server performance or just remove the mod from the server
