### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by MC-honeybear** [LunaPixelStudios/Better-Minecraft#424]
### Describe the Bug

There is no sound. I've checked the settings, everything is as it should be, but the sound is missing. This has happened both times I've used the mod pack, the first altercation was fixed simply by waiting, which then led to a game crash. This time, the sound has yet to come back.

### Reproduction Steps

1. Start the game
2. That's it, you'll have no sound for the rest of it.

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] - 1.18.2

### Optifine

I used Optifine

### Other Mods

No other mods were added to this pack. Just the BSL Shaders by capttatsu.

**Comment by MC-honeybear** [comment]
PC Specs:

Processor:  11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz   2.50 GHz
Installed RAM:  16.0 GB (15.7 GB usable)
System type:  64-bit operating system, x64-based processor

I'm using Optifine but I haven't removed any mods manually, so I'm not 100% sure about those.

**Comment by MC-honeybear** [comment]
I've also run into a problem where most of the mods in the modpack claim to be outdated/incompatible. I've tried figuring out if it might be something on my end, but I cannot seem to fix it. I've removed the incompatible ones when making worlds, but it doesn't seem to make a difference whether they're active or not. One update on the sound: If I play/let things load for a couple hours, then I can hear blocks. Not when I walk on them, but I can hear when I place them. That's as far as I've been able to get.

**Comment by SharkieTV** [comment]
You dont have a graphics card? how much ram have you did you allocate? Can you remove optifine and see if its still the issue?

**Comment by Thangkou** [comment]
press F3 + T to reload mod packs.

**Comment by MC-honeybear** [comment]
> 

I do have a graphics card, every PC has one. The model for my PC is the NVIDIA GeForce RTX 3060 Graphics Card.

I don't quite understand your second question? I've included some of my RAM details in my answer with the PC Specs. I'm not quite sure what you're asking.

I've removed optifine and its has made no difference.

**Comment by MC-honeybear** [comment]
> press F3 + T to reload mod packs.

Reloading the Mod packs sadly hasn't changed a thing. They still claim to be outdated. If I start a world without removing the outdated mod packs, the game will crash or simply stop responding. So I just disabled the ones that were "incompatible". That's the only way I can play for now.

**Comment by FreestyleStorm** [comment]
also having sound issues missing. ambiance noises, footsteps, noises from specific animals, mobs, and hoeing things are odd. just a lot of sound issues.

**Comment by SharkieTV** [comment]
Well I cant help much as I dont get the sound issues and for the crashing and stop responding issues seems to be an issue with your pc. Since you dont understand my ram question I can possibly safely say you are running the modpack at 3/4 gb of ram and thats probably the issue causing this. Any modpack you ever play you should allocate more ram especially if its with so many mods. 
Use one of the links here to allcoate your ram
CurseForge Launcher: [](https://youtu.be/P3hd9MKWvXw?t=130)
GD Launcher: [](https://youtu.be/P3hd9MKWvXw?t=383)
MultiMC: [](https://youtu.be/P3hd9MKWvXw?t=452)

**Comment by MC-honeybear** [comment]
I have now watched the video and followed its instructions to a T. There's, once again, sadly, still no sound. Apart from that the mod packs are still claiming to be outdated and will still cause my game to stop responding if not disabled.  It has sadly not made a single difference.

**Comment by MC-honeybear** [comment]
> also having sound issues missing. ambiance noises, footsteps, noises from specific animals, mobs, and hoeing things are odd. just a lot of sound issues.

Yup! Sounds exactly like the issues I've got. Only specific mobs and blocks make sound. Although I cannot figure out why for the life of me.

**Comment by SharkieTV** [comment]
Can you send your latest.log?

**Comment by FreestyleStorm** [comment]
> > also having sound issues missing. ambiance noises, footsteps, noises from specific animals, mobs, and hoeing things are odd. just a lot of sound issues.
> 
> Yup! Sounds exactly like the issues I've got. Only specific mobs and blocks make sound. Although I cannot figure out why for the life of me.

exact same issues here as well.

**Comment by DahhFly** [comment]
12 Gb Ram are not enough ? I could go up to 24 but thats ludacrisly too much. Tried everything from updating graphic drivers and reinstalling the whole modpack, sadly no changes.

**Comment by EvionLongThong** [comment]
> > > also having sound issues missing. ambiance noises, footsteps, noises from specific animals, mobs, and hoeing things are odd. just a lot of sound issues.
> > 
> > 
> > Yup! Sounds exactly like the issues I've got. Only specific mobs and blocks make sound. Although I cannot figure out why for the life of me.
> 
> exact same issues here as well.

I am having the exact same issues as well. Same sounds that I cannot hear (menu sounds, walking, hostile mobs) I have to export my better minecraft profile and import it as a new profile to be able to hear sound again. I don't see a solution to this issue even though its marked complete?

**Comment by lunaboona** [comment]
Why is this marked as completed? I'm having the same issue where a few sounds straight up don't work such as hitting mobs or getting damaged, but I don't see a solution in this thread.

**Comment by Gubibbles** [comment]
Same problem here... as for example, breaking grass makes noises, but breaking wood don't. 9 ram allocated on CurseForge, no outdated mods, everything normal exept for the missing sounds and still don't know why :c
