### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by MrBootsy** [LunaPixelStudios/Better-Minecraft#425]
### Describe the Bug

Unsure if its a compatibility issue or a direct issue of the mod, Excavated Variants mod appears to be missing some textures.

### Reproduction Steps

1. locate Andesite Copper ore whilst mining.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/106683181/171427890-0125e3c7-3ceb-4280-833e-ab128386f6a7.png)

### Crash Report or Log

N/a

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11 & v11.5

### Optifine

I used Optifine

### Other Mods

N/a

**Comment by SharkieTV** [comment]
waiting for a mod update/fix from the mod dev
