### ISSUE TITLE
Missing textures for andesite ore in Excavated Variants

### ISSUE THREAD

**Issue by DEAFG0AT** [LunaPixelStudios/Better-Minecraft#427]
![2022-06-01_21 58 36](https://user-images.githubusercontent.com/104733108/171556584-e4370b32-1857-413b-be75-461f32c08a63.png)
![2022-06-01_21 59 31](https://user-images.githubusercontent.com/104733108/171556590-d2e1050a-4253-4691-9c09-b32c8ba375b0.png)

**Comment by SharkieTV** [comment]
waiting for a mod update/fix from the mod dev
