### ISSUE TITLE
Wardens and Ancient Cities (Warden & Skulk mod) do not generate in 1.18.2.

### ISSUE THREAD

**Issue by wormbutheswag** [LunaPixelStudios/Better-Minecraft#428]
• Generate new world in Better Minecraft 1.18.2
• /locatebiome warden_and_skulk
• Alas

Does not work for Warden & Skulk 1.0.0, 2.0.0, or 2.4.0.

**Comment by SharkieTV** [comment]
This mod does not add ancient cities? and you cant find its biome as it is not compatible with terrablender so you get a quest reward instead
