### ISSUE TITLE
Guardian Detected An Incompatible world

### ISSUE THREAD

**Issue by player789** [LunaPixelStudios/Better-Minecraft#429]
### Describe the Bug

i installed the pack in the curse launcher and then i launched created the world and played for a bit and quit.Then i noticed everytime i open the pack and try to load my world it says that message in the screenshot i am not sure if it has effects on my actual world like recreating it anew (removing blocks placed by me....).

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Minecraft Screenshot 2022 06 02 - 20 27 37 76](https://user-images.githubusercontent.com/25511188/171723060-1f467296-6cf8-4f01-9cd3-8c46990c143b.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v11.5

### Optifine

No

### Other Mods

_No_

**Comment by SharkieTV** [comment]
Ignore it
