### ISSUE TITLE
Cant Trade with Farmer Villagers

### ISSUE THREAD

**Issue by CraftSmack** [LunaPixelStudios/Better-Minecraft#43]
### Describe the Bug

I have been playing this modpack for a month and i've made some villager breeders and villager powered farms but now i want to trade with some farmer villagers and it wont let me in their UI. im not sure whats causing it but i went into vanilla to test if i could trade with them there and it worked so it might be a mod thats messing with it in some way?

### Reproduction Steps

1.I spawned in a villager and put a composter down next to him and he takes the job but when i click on him it doesn't let me trade with him he just shakes his head
2.I bred some villagers and did the same thing with the same result
3.
...

### Screenshots and Videos

[https://youtu.be/YTvBVRyvveA](url)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v3.5

### Optifine

No

**Comment by CraftSmack** [comment]
Heres a link to the youtube video it didnt work for some reason, https://youtu.be/YTvBVRyvveA , just copy and paste that

**Comment by switchnlade** [comment]
Already fixed in v4+ or update croptopia. If you find bugs in an old version, please test it on the new one before reporting as most likely it's been fixed.
