### ISSUE TITLE
Game crash after launching world with optifine

### ISSUE THREAD

**Issue by Kreyzz** [LunaPixelStudios/Better-Minecraft#430]
### Describe the Bug

I removed Magnesium and dynamiclight and added optifine or rubidium with oculus but it keep crash

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v38

### Optifine

I used Optifine

### Other Mods

Rubidium and oculus

**Comment by SharkieTV** [comment]
you added Rubidium and oculus? if so dont they are very buggy for 1.16

**Comment by Kreyzz** [comment]
same with optifine?
