### ISSUE TITLE
Tnt and creeper not explode

### ISSUE THREAD

**Issue by Cofi32** [LunaPixelStudios/Better-Minecraft#431]
### Describe the Bug

When creeper or tnt explode i get damage but block not get destroyed

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

### Other Mods

gilded
ultimine

**Comment by SharkieTV** [comment]
either its spawn  protection or ftb chunks claimed
