### ISSUE TITLE
Frozen Mobs

### ISSUE THREAD

**Issue by InfinityMage** [LunaPixelStudios/Better-Minecraft#432]
### Describe the Bug

When entering the nether once, the mobs were frozen. I was able to move around and break blocks, but I couldn't go back into the overworld. When I tried to hit mobs, nothing happened. No mobs would move/interact with me. This never happened once through the entirety of my playthrough, and I am unsure if its an issue with the game or my laptop. When I try to close the window, I have to go into the Task Manager and manually shut it down. This was the only way I figured out how to close it. If I tried to exit out of the world via the menu, it would simply freeze.  

### Reproduction Steps

1. Go into the nether
2.
3.
...

### Screenshots and Videos

<img width="881" alt="image" src="https://user-images.githubusercontent.com/106843426/171956124-127a781d-9875-45ff-8702-a85ba12b3d03.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/106843426/171956418-21dc7d7d-838e-41c3-9fc5-3db070feef13.png">

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
What is your pc specs? and how much ram is allocated?

**Comment by InfinityMage** [comment]
> What is your pc specs? and how much ram is allocated?

I allocated 6592 mb.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/106843426/172017256-9578e8f4-2e5f-4667-ac88-96be25ac9405.png">

**Comment by SharkieTV** [comment]
This modpack requires 6-8gb so your barely even running it. Their no issues on my end and this is happening due to the ram/laptop.
