### ISSUE TITLE
Missing Sound 

### ISSUE THREAD

**Issue by FreestyleStorm** [LunaPixelStudios/Better-Minecraft#433]
### Describe the Bug

Ambiance noises like rain and weather are not working, specific mobs not making noises, hoeing not making noises etc

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V 11.5

### Optifine

No

**Comment by SharkieTV** [comment]
I dont get this issue so I cant tell you what to do to fix it. How much ram have you allocated?
