### ISSUE TITLE
Enemies not rendering

### ISSUE THREAD

**Issue by Thatspinnychair** [LunaPixelStudios/Better-Minecraft#434]
### Describe the Bug

Humanoid mobs appear as purple outlines and do not render in.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Most recent

### Optifine

No

**Comment by SharkieTV** [comment]
Humanoid? can you show a screenshot?
