### ISSUE TITLE
Possible Mod issue causing crashes within the end?

### ISSUE THREAD

**Issue by MrBootsy** [LunaPixelStudios/Better-Minecraft#435]
### Describe the Bug

Seems to be happening each time a player enters the end, after X amount of time the server crashes and then reports the following error report. I'm not proficient at reading these so im unsure what any of it actually means and thought its best to just post it here.

This only happens within the End and has only just started, Servers been running now for around a week with no issues, this is the first time anyone has entered the End to which the crash started.

[crash-2022-06-05_23.05.30-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8840881/crash-2022-06-05_23.05.30-server.txt)

### Reproduction Steps

1. Enter the End
2. Wait for a while/Explore a little
3. Await the server Crash.
...

### Crash Report or Log

https://pastebin.com/G2bKjjn1

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

**Comment by KhanhPham05** [comment]
This is caused by a geode+, i am contacting mod author in discord server for a solution

**Comment by SharkieTV** [comment]
Duplicate #420
