### ISSUE TITLE
Configuration conflict

### ISSUE THREAD

**Issue by MiPnamic** [LunaPixelStudios/Better-Minecraft#436]
### Describe the Bug

Unable to start the game after upgrade to v12

### Reproduction Steps

1. Upgrade to v12
2. Start the game
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8841953/latest.log)

### Crash Report or Log

https://pastebin.com/KDGPxtHK

### Operating System

Windows 10 Pro

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

**Comment by MiPnamic** [comment]
Attached crash log
[crash-2022-06-06_07.18.49-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8842027/crash-2022-06-06_07.18.49-client.txt)

**Comment by SharkieTV** [comment]
Did you update any mods?

**Comment by SharkieTV** [comment]
remove the yigd mod
