### ISSUE TITLE
Sound Problems

### ISSUE THREAD

**Issue by DahhFly** [LunaPixelStudios/Better-Minecraft#437]
### Describe the Bug

walking and breaking sounds work but when fighting there are basically no sounds from hits and so on.

### Reproduction Steps

1.Start the game
2.Play
3.start thinking you become deaf
...

### Operating System

Win 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Duplicate #424
