### ISSUE TITLE
crops cannot be planted in Rich Soil Farm in this mode pack.

### ISSUE THREAD

**Issue by mejiro451** [LunaPixelStudios/Better-Minecraft#441]
### Describe the Bug

In the 1.18.2 version  12V
in mode pack 
all crops (except tomatoes) are not planted in Rich Soil Farmland of Farmer Delight mod
The same version of Farmer Delight in another mod pack is works
crops cannot be planted in [Rich Soil Farm] in this mode pack.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

12V

### Optifine

No

**Comment by SharkieTV** [comment]
KNown bug and waiting for a fix from mod dev
