### ISSUE TITLE
Better Minecraft v11 Forge 40.1.23 crash

### ISSUE THREAD

**Issue by eipuras** [LunaPixelStudios/Better-Minecraft#443]
### Describe the Bug

I have tried everything from deleting to reinstalling vanilla minecraft, curse forge, the modpack, updating drivers, different versions of Java to no avail. The mod will not load up. All of my friends are able to play on my server while I'm stuck and not able to play. I am on the brink of just smashing my computer at this point. 

### Reproduction Steps

[crash-2022-06-08_20.19.19-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8865743/crash-2022-06-08_20.19.19-client.txt)

### Screenshots and Videos

n/a

### Crash Report or Log

<script src="https://pastebin.com/embed_js/gykNjs68"></script>

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

11

### Optifine

No

### Other Mods

none

**Comment by SharkieTV** [comment]
v11.5 should fix the issue

**Comment by eipuras** [comment]
Hello,

Thing is I cannot download v11.5 because my server is v11. I’m using Apex
hosting and they don’t have v11.5 to download.

Thank you.

**Comment by eipuras** [comment]
I cannot download v11.5 onto my server since I am using Apex hosting. To my knowledge there is no way to update my server to v11.5. My friends are able to get on it. Can we reopen this please?
