### ISSUE TITLE
Modified Creepers (more hp, taller, ..) can spawn in a Creeper Farm even if there isnt enough space for them

### ISSUE THREAD

**Issue by AlienGurke** [LunaPixelStudios/Better-Minecraft#445]
### Describe the Bug

In my Creeperfarm, Creepers which are taller than normal Vanilla Creepers can spawn, even if there isnt enough space for them, which results them getting stuck in trapdoors so they cant move and cant escape, which effects the efficiency of the farm.

> I spawnproofed everything in the farm, only Creepers can spawn.
> its build in an Ocean Biome, 128 Blocks over the water

Trapdoor Height: 0.18750
Vanilla Creeper Height: 1.7
Modified Creeper Height: less then 1 Pixel to 2.0 Height left (16x16tp) means 1/16=0.0625 height for every Pixel means: 2-0.0625. 
So its at least 1.9375 high, I would say 1.95

However, a Trapdoor is 0.18750 high results that every Mob until 1.8125 Blocks height is only able to spawn.
The Modified Creeper is way taller than 1.18125 Blocks so it shouldnt be able to spawn

On the 3rd picture u can see that it has some effects, which are due to "Mob Enchanted Book(s)". If a player right clicks such a Book he will get the effect but the Player Size gets increased slightly.
However, they shouldnt be able to spawn if there is no space for them (Height: 1.8125 < Modified Creeper Height 1.95)

### Reproduction Steps

1. Built a basic Creeper Farm
2. Stay afk and notice after some time that some Creepers gets stuck in the Farm

### Screenshots and Videos

I have used this creeper farm: 
(just modified a bit with cats)
https://www.youtube.com/watch?v=FHbYXRpn1eE

Difference height Vanilla vs Modified:
![image](https://user-images.githubusercontent.com/48620216/172934544-e7719ab4-7b70-4980-9a84-e3062c217270.png)

Height of Modified:
![image](https://user-images.githubusercontent.com/48620216/172934701-7eb33fb7-4bb9-4388-8c4b-0877e05060d2.png)

Height of Modified + Name and Effects:
![image](https://user-images.githubusercontent.com/48620216/172934817-73d9663d-8d88-44d7-8392-63fadfa7b206.png)

### Crash Report or Log

/

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v11.5

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
Im unable to change the height of the mobs so you will probs need a different creeper farm

**Comment by AlienGurke** [comment]
A differnet farm is prob not possible cause every farm using Trapdoors,
but noticed that they just spawn often in "Hard", so "Normal" or "Easy" Difficulty almost fixing it.
