### ISSUE TITLE
Swift Sneak Enchantment doesnt work

### ISSUE THREAD

**Issue by AlienGurke** [LunaPixelStudios/Better-Minecraft#446]
### Describe the Bug

Swift Sneak Enchantment on Leggings doesnt have an effect at all.

### Reproduction Steps

 self-explaining

### Crash Report or Log

/

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v11.5

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
using new mod should work
