### ISSUE TITLE
Enter another world customer service crashes

### ISSUE THREAD

**Issue by TiaoShu1126** [LunaPixelStudios/Better-Minecraft#448]
### Describe the Bug

Enter another world customer service crashes

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/yrRK58jU

### Operating System

win11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
customer service crashes? what does that even mean?
SO creating another world crashes?

**Comment by TiaoShu1126** [comment]
Entering another world appears loading the world and then saving the world and it crashes

**Comment by SharkieTV** [comment]
It  says the dead_guys_untitled_deep_dark is crashing your game see if removing that mod helps?
