### ISSUE TITLE
No Quests

### ISSUE THREAD

**Issue by Geonaut23** [LunaPixelStudios/Better-Minecraft#449]
### Describe the Bug

I don't know what the problem is, but my server generated without any quests. The server is on Apex Hosting if that makes a difference. Quests are generated in the single-player version of the mod pack as well. I don't have online mode active on the server, so could that be the issue?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/107294969/173175401-ffc28d2c-f808-42e3-be00-2ab068090b52.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by SharkieTV** [comment]
The quests are in the config, make sure they are added to the server
