### ISSUE TITLE
invisible Fluids in Tinkers' Construct Containers with Shaders

### ISSUE THREAD

**Issue by ZeroOneNineMODS** [LunaPixelStudios/Better-Minecraft#451]
### Describe the Bug

When using any shaders with this mod pack. Tinkers construct Fluid goes invisible. 
I'm using Complementary v4.4

### Reproduction Steps

1. chose a shader any
2. look at the tanks on a tinkers construct smeltery
3. liquid transparent 
...

### Screenshots and Videos

With out shaders

![2022-06-12_02 47 54](https://user-images.githubusercontent.com/55348138/173209649-32f9661c-345e-4f07-b252-656a51fe93a4.png)

with shaders
![2022-06-12_02 48 16](https://user-images.githubusercontent.com/55348138/173209650-97dad188-bdf5-4a7b-b2a2-bed5442bcfff.png)

### Crash Report or Log

https://pastebin.com/pqqbcaRF

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better minecraft plus v10

### Optifine

No

**Comment by SharkieTV** [comment]
Youi have tried other shaders? can you try setting compatibility mode on for Complementary shaders?

**Comment by ZeroOneNineMODS** [comment]
Does not work with compatibility mode on all shaders

**Comment by ZeroOneNineMODS** [comment]
Issue solved. 
I found a fix but it will remove the animations for fluids. 

Locate the file in the config folder: tconstruct-client.toml
change TankFluidMode = false to true
