### ISSUE TITLE
Game crashes before even starting to load

### ISSUE THREAD

**Issue by NotGoingToLie** [LunaPixelStudios/Better-Minecraft#456]
### Describe the Bug

When I try to launch Better Minecraft 1.18.2 (Forge), the minecraft launcher works but after a few seconds pressing play it crashes and shows the messege shown below.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image_2022-06-18_191349593](https://user-images.githubusercontent.com/107765187/174447291-ce3f8ca9-c870-42e4-b405-17cdc2e75017.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

No

**Comment by SharkieTV** [comment]
Unfortunately its something to do with the launcher not the Modpack
