### ISSUE TITLE
Radium causing crash in Everbright (MC 1.19)

### ISSUE THREAD

**Issue by RbbrBootz** [LunaPixelStudios/Better-Minecraft#457]
Initially went to the Blue_Skies mod issues and they were able to isolate the issue to Lithium.  
Removed the Lithium mod, named Radium in this mod pack and crashing issues were resolved.
Have an open issue with Radium mod, but upon looking at the open issues, it seems there is a consistent problem with it for quite some time.

Suggestion: Try to locate another Lithium modder to work with.  The colours are quite different without it.

**Comment by SharkieTV** [comment]
Their is not 1.19 version of my Modpack

**Comment by RbbrBootz** [comment]
I know that.  It was MC (Minecraft) version 1.19 
It has been since Minecraft switched over to 1.19 that we had the problem with Radium.
