### ISSUE TITLE
Crashing upon opening map - Xaero why!

### ISSUE THREAD

**Issue by RedemptionWolf** [LunaPixelStudios/Better-Minecraft#458]
### Describe the Bug

Using M to open map will consistently crash the game. I have tried following the other users solutions to fix the issue by deleting the Xaero data folders and it will fix for a time or two and then replicate.

I really don't want to have to remove this mod from the pack. Other players on the server with the same exact settings/mods are not having this issue. I have also tried disabling waypoints per another closed post on here and that did not resolve the crashing either.

Thanks in advance!

### Reproduction Steps

1. Load into multiplayer.
2. Use M to open map.
3. Crash
4. Error: xaero.common.exception.OpenGLException: OpenGL error: 1282
Exit Code: -1
...

### Crash Report or Log

https://pastebin.com/qUciwSas

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v11.5

### Optifine

No

**Comment by SharkieTV** [comment]
See if updating the oculus mod fixes it

**Comment by RedemptionWolf** [comment]
> See if updating the oculus mod fixes it

Added Oculus update and the map is still crashing, unfortunately. 

Thanks for quick reply! https://pastebin.com/GL3uGsh9

**Comment by SharkieTV** [comment]
you could try updating the xaeros mods and if it still crashes I can only suggest removing oculus and rubidium and using optifine instead

**Comment by KhanhPham05** [comment]
I used to have this issue,  best solution is to update it or use an alternative mod

**Comment by RedemptionWolf** [comment]
So far this fix has worked. Much appreciated!
