### ISSUE TITLE
chunk loading issue on singleplayer

### ISSUE THREAD

**Issue by R4ven4koS** [LunaPixelStudios/Better-Minecraft#46]
### Describe the Bug

view distance is high enough but i get more on ground level the chunks become unable to see. basically i see 4 chunks in every direction when im on ground level. 
someone said that it might be something with the fog. but again my view distance is high enough so i dont know.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

heres a link for a youtube video i uploaded with the problem
https://youtu.be/gnoe573K_wM

### Crash Report or Log

the game does not crash when the problem occurs

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC V53 on GDLauncher

### Optifine

No

**Comment by SharkieTV** [comment]
update to latest version or change video settings in advanced

**Comment by R4ven4koS** [comment]
I mentioned I'm on the latest version v53 also I have played with all the setting in advanced.

**Comment by SharkieTV** [comment]
Latest version is v54

**Comment by R4ven4koS** [comment]
goodmorning.
did update to v54. also removed magnesium extras.
still the issue is there

**Comment by R4ven4koS** [comment]
@SharkieTV  hey just wanted to let you know that i found another person with the exact same problem. can you help us? its preety unplayable

**Comment by SharkieTV** [comment]
My bad I meant Immersive FX Environs disable fog, go to Mods > Immersive FX Environs > Fog Options and disable fog

**Comment by R4ven4koS** [comment]
there is no such thing as immersive FX in my mods.

**Comment by R4ven4koS** [comment]
only immersive Cooking

**Comment by SharkieTV** [comment]
Lmao sorry DSurround since latest version I switched it

**Comment by R4ven4koS** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/98081777/150646444-08025613-3d1d-4605-a093-80c49f7dac14.png)
no such thing as "Dsurround" also ;'(
@SharkieTV

**Comment by R4ven4koS** [comment]
do you even know your own modpack? hahaha :P

**Comment by switchnlade** [comment]
Dynamic Surroundings

**Comment by R4ven4koS** [comment]
ohh yessssss
finallyyyyyyyy

**Comment by R4ven4koS** [comment]
thank youuuuu @SharkieTV  @switchnlade
