### ISSUE TITLE
Crash due to Blueprint.

### ISSUE THREAD

**Issue by Ironnoob73** [LunaPixelStudios/Better-Minecraft#461]
### Describe the Bug

It used to have a chance of crashing when launching the game, but now it's every time.
(I'm not using the curseforge app because it doesn't download anything at all. So I use other launcher.)

### Reproduction Steps

1.Launch the game.
2.The game crashes without showing a window.

### Crash Report or Log

[crash-2022-06-11_14.59.09-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8939254/crash-2022-06-11_14.59.09-client.txt)

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

No

### Other Mods

i18nupdatemod-1.18-3.0.0   (https://www.curseforge.com/minecraft/mc-mods/i18nupdatemod)
JustEnoughCharacters-1.18.1-4.3.3   (https://www.curseforge.com/minecraft/mc-mods/just-enough-characters)
polylib-forge-1801.0.2-build.13   (https://www.curseforge.com/minecraft/mc-mods/polylib)
ftbbackups2-forge-1.18.2-1.0.10   (https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
(I have uninstalled these mods, but the problem persists.)

**Comment by SharkieTV** [comment]
What launcher are you using?

**Comment by Ironnoob73** [comment]
> What launcher are you using?

pcl2
