### ISSUE TITLE
Chisel and Bits Bit Storage Crashes game

### ISSUE THREAD

**Issue by Don-Laliberte** [LunaPixelStudios/Better-Minecraft#464]
### Describe the Bug

If you place the block you will softlock your game because as soon as you look at the block the game crashes. Additionally, breaking the block with a Drill from Create through another player causes the whole server to crash. 

### Reproduction Steps

1. Place Chisel and Bits Bit Storage next to Chisel Station
2. Get Softlocked
3. Use another persons account to try and break the block without looking at it
4. Place Create Drill facing it 
5. Place Creative motor
6. Crash Server
7.
...

### Crash Report or Log

https://pastebin.com/u0Azr8FJ

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] 1.18.2

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Can you see if removing the waila/jade mods from the pack and see if looking at it still crashes it?

**Comment by Don-Laliberte** [comment]
I'll try it when I can, but that is what I was thinking too.

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
