### ISSUE TITLE
Weird lines in the sky? 

### ISSUE THREAD

**Issue by fuwadd** [LunaPixelStudios/Better-Minecraft#465]
### Describe the Bug

So, I recently downloaded the modpack, first thing I did was load it up. Then I deleted the two mods that were associated with lighting (Magnesium and Dynamic Lights) so I can get Optifine. Downloaded shaders as well. Then, I see these lines. Thought it was Optifine, so I deleted it. Nope. Then I removed the preinstalled resource packs, nope. Fiddled with some settings, still no. Would love a solution to this, thank you so much!

### Reproduction Steps

1.Open modpack
2.Load into world, look at sky
3. Werid crappy linse
...

### Screenshots and Videos

![2022-06-22_05 15 01](https://user-images.githubusercontent.com/107991989/174993393-34897036-58d5-4374-a42c-558a012cde43.png)
![2022-06-22_05 15 31](https://user-images.githubusercontent.com/107991989/174993406-47676cba-e04d-4bd2-b278-950bee5fdddb.png)
![2022-06-22_05 15 55](https://user-images.githubusercontent.com/107991989/174993433-77964155-4c84-4666-ba33-ca6b36eed5d1.png)
![2022-06-22_04 50 08](https://user-images.githubusercontent.com/107991989/174993458-c4146b41-33cf-4a60-9ff3-12e9cebce59b.png)
(Turns to blue with optifine.)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Remove Dynamic Surroundings Mod
