### ISSUE TITLE
End Ships spawning with no hull / chests etc

### ISSUE THREAD

**Issue by JackAttackIV** [LunaPixelStudios/Better-Minecraft#47]
### Describe the Bug

Every End City has spawned with the Airship half genereted / no elytra/items. 
I went into creative and found 3 more end cities with same generation. (Total 4)
This is on a dedicated server.
See pictures

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-01-20_17 38 46](https://user-images.githubusercontent.com/98116009/150392461-c3fdd300-d973-44e7-9f5c-b11537e8b876.png)
![2022-01-20_17 40 39](https://user-images.githubusercontent.com/98116009/150392562-66bc91f4-0e04-4f33-a853-7d71695a0ff9.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V11

### Optifine

I used Optifine

### Other Mods

+ Shaders client side

**Comment by SharkieTV** [comment]
It seems like you are using a Better End City datapack, thats the only thing that would cause this.

**Comment by switchnlade** [comment]
Tested on v11.5, works perfectly. Looking at the blocks missing and the biomes around the city, it's the better end blocks. Verify that's in the mods folder too.

**Comment by SharkieTV** [comment]
@switchnlade its forge it doesnt have better end and I dont add the datapack either

**Comment by switchnlade** [comment]
Yep, my bad, misread that one

**Comment by switchnlade** [comment]
Actually, this does occur on v11 Forge, I just tested. V13 works fine however.
