### ISSUE TITLE
Ticking World

### ISSUE THREAD

**Issue by Termagent** [LunaPixelStudios/Better-Minecraft#470]
### Describe the Bug

Hosting a server with no additions or subtractions of mods on 11.5v of Better Minecraft 1.18.2 FORGE and recieving Exception Ticking World Error constantly.

### Reproduction Steps

1. Launch Server
2. Run around for a little bit
3. Crash
...

### Crash Report or Log

https://gist.github.com/Termagent/fcea6210e379b94962ca2e3a3ce993d6

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

**Comment by Termagent** [comment]
To add more information I forgot. We have tried putting server in peaceful and removing a nearby bugged spawner and it still crashes

**Comment by SharkieTV** [comment]
Remove the Geode+ Mod from server and client
