### ISSUE TITLE
Modded biomes not spawning in the Overworld

### ISSUE THREAD

**Issue by Diogoes** [LunaPixelStudios/Better-Minecraft#471]
### Describe the Bug

Hey, I just installed a fresh install of Better Minecraft Forge (1.18, v12). BYG biomes arent spawning in the overworld, aswell as any other modded biome that might be in the pack. However, this doesnt seem to be an issue in the nether.

### Reproduction Steps

1.Install BMC on curseforge
2.run game 
3.
...

### Crash Report or Log

https://gist.github.com/Diogoes/966dc6233625f74cfc3d5d94b689aff3

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Forge 1.18.2 (version 12)

### Optifine

No

**Comment by SharkieTV** [comment]
Will fix in v12.5
