### ISSUE TITLE
NullPointerException when trying to connect to server after update

### ISSUE THREAD

**Issue by Cinnarose** [LunaPixelStudios/Better-Minecraft#472]
### Describe the Bug

My friend group set up an Aternos server using Better Minecraft about a week ago that has been running fine with no issues for any of us until now. After Aternos auto-updated to the newest version I went and did the same for my profile, which is now resulting in a crash to desktop whenever I attempt to join the server. One of the others tested it and got in without any issues after she updated to v12, so the problem appears to be specific to me and not a server thing.

I'm not very knowledgeable about this kind of stuff, but the crash logs seem to consistently highlight my customized iron shield as the possible culprit. It seems like something to do with Better Shields or Additional Banners isn't reading as it should for me after switching to the newest version. Or maybe I just messed up somewhere along the line while attempting to update my forge profile, as it's my first time doing so. We haven't stuck with a modpack long enough to find out about the whole auto-update thing until BMC, so hopefully this issue has a fix.

I tried re-installing the modpack in multiple different ways which might have made it worse, but seeing as I'm still getting the exact same error it doesn't seem like it's done much of anything.

### Crash Report or Log

https://pastebin.com/EK2B4Hxn

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v12

### Optifine

No

**Comment by SharkieTV** [comment]
It seems a bettershields:iron_shield has a banner of additionalbanners_squid onit and causing the crash. Best is to reset your player data and from my knowledge Better Minecraft shouldve been removed from Aternos as they banned my modpack

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
