### ISSUE TITLE
Torchberry Plant Bug

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-Minecraft#474]
### Describe the Bug

Hello once again! Im here with a new bug regarding version 12.5 of Better Minecraft

I cant seem to place torchberry plants properly even after checking out the wiki for the Twilight Forest part of the update, This is a harmless issue however i feel that those wanting to start Torchberry farms will be quite confused as to why they cant plant it.

### Reproduction Steps

1. Get a torchberry plant
2. try all you want to place it on the ceiling but it aint gettin up there 
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

12.5

### Optifine

No

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
