### ISSUE TITLE
Banner Issue

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-Minecraft#475]
### Describe the Bug

Hey found another bug today! So i tried to make a Banner with the Add Banners mod and funnily enough, the game crashed! Im not too sure what caused this, but i sure hope this can be fixed asap!

### Reproduction Steps

1. Get any banner pattern from Add Banners
2. Attempt to put dye into it
3.
...

### Crash Report or Log

https://pastebin.com/s11377ME

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

12.5

### Optifine

No

**Comment by SharkieTV** [comment]
I am unable to reproduce this issue, is this a specific banner or dye?

**Comment by FevilGitHub** [comment]
i tried to put in a stack of red dye for a spade pattern after i put in the
banner and pattern, and thats what caused it to crash.

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
