### ISSUE TITLE
probably chests loot not showing up

### ISSUE THREAD

**Issue by Gale-Man** [LunaPixelStudios/Better-Minecraft#476]
### Describe the Bug

I was playing and the first two probably chests I opened had all their loot but after that, every chest I would come across was entirely empty, these were not the ones I had previously opened

### Reproduction Steps

1. play the game and open 2 chests???

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
