### ISSUE TITLE
Alex's Mobs Banner bug

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-Minecraft#478]
### Describe the Bug

Ok i know i put up another bug about banners before but i found another one :c

It has to do with the Alex's Mobs patterns, as it doesnt display the patterns. Meanwhile as i was writing this i tested another one of the same mod and it didnt appear either.

This is a harmless bug but i felt like reporting it regardless

### Reproduction Steps

1. get an alex's mobs banner design
2. attempt to use it
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/106572267/176061520-2e39a868-ab9b-424c-88ac-6f9c5718b57a.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

12.5

### Optifine

No

**Comment by FevilGitHub** [comment]
Update: Still testing the banners and the Quest Ram Swirls from the Twilight mod also doesnt work. :c
![image](https://user-images.githubusercontent.com/106572267/176062190-6f6ede8f-7cf0-4f48-a5c4-49a614308e77.png)

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
