### ISSUE TITLE
Game crashes when putting a Cherry Ladder on a Supplementaries Timber Frame

### ISSUE THREAD

**Issue by adamb1222** [LunaPixelStudios/Better-Minecraft#48]
Game crashes when putting a Cherry Ladder on a Supplementaries Timber Frame, possibly replicatable with other ladders and other frames, havent tried yet.

**Comment by switchnlade** [comment]
Heyo, we have a template next time so please use it to allow us to understand a bit easier. Are you on fabric or forge, and what are the modpack and mc versions, also a [pastebin](https://pastebin.com/) of the crash log if you can?

**Comment by SharkieTV** [comment]
No Response
