### ISSUE TITLE
Missing Key Wizard Tower

### ISSUE THREAD

**Issue by Soulcalibur777** [LunaPixelStudios/Better-Minecraft#480]
### Describe the Bug

Searching for all four keys to unlock the wizard tower dungeon. The last key is nowhere to be found. Checked all the roioms multiple times I'm guessing the last chest within the brewing room with the witch is where the key is supposed to be. However the chest isn't there.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

n/a

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft 1.18.2 (Plus)

### Optifine

No

### Other Mods

n/a

**Comment by FevilGitHub** [comment]
Its actually in the brewing stand for whatever reason, just to let ya know <3
