### ISSUE TITLE
Gravity Compressor from Eden Ring corrupts world

### ISSUE THREAD

**Issue by domtt1** [LunaPixelStudios/Better-Minecraft#481]
### Describe the Bug

When placed, the Gravity compressor crashes the world. You are not able to rejoin the world unless you run a command to remove the block, therefore, corrupting the world. I believe the problem only happens when you look at the block placed.

### Reproduction Steps

1. Open a single-player or multiplayer world.
2. place Gravity compressor
3.
...

### Screenshots and Videos

https://i.imgur.com/z1D0Csv.mp4

### Crash Report or Log

Exit code: -1

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

### Other Mods

No other mods added

**Comment by SharkieTV** [comment]
See if updating the Eden Ring mod helps
