### ISSUE TITLE
Unable to turn daytime when sleeping

### ISSUE THREAD

**Issue by s1xnzs** [LunaPixelStudios/Better-Minecraft#488]
### Describe the Bug

When going to sleep, it shows the notifications in the chat of the advancements and the screen dims, but never actually falls asleep. You can "Leave Bed" but it doesn't switch to day time

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft plus

### Optifine

No

### Other Mods

veinminer enchantment book

**Comment by SharkieTV** [comment]
Sleeping works for me
