### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by FoolishKnish** [LunaPixelStudios/Better-Minecraft#489]
### Describe the Bug

I've tried running other Mod Packs and it works perfectly fine but when I go to run Better Minecraft 1.18.2 [forge] it comes up with a error code 1 and I've tried allocating more ram and still not result and even manually updating mods in the pack itself still not result. Normally Minecraft works perfectly fine alongside other Mod Packs.

### Reproduction Steps

1. Reinstalling Mod Pack
2. Manually Updating Mods
3. Allocating More Memory
...

### Screenshots and Videos

![minecraftcrash](https://user-images.githubusercontent.com/68277854/176911890-c29f467b-334d-45e5-9075-7e46ca0057fa.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft v12.5

### Optifine

No

**Comment by SharkieTV** [comment]
Cant really help with this issue
