### ISSUE TITLE
Java Crash

### ISSUE THREAD

**Issue by Paradox0497** [LunaPixelStudios/Better-Minecraft#49]
### Describe the Bug

I am running a Better Minecraft server and can play normally. I have had people join with no issue until someone uses a furnace. The entire server crashes and from then on the server will crash upon startup. 

### Reproduction Steps

1.Create Better Minecraft server (1.18) 
2.Install Forge 1.18
3. Run server.
4. Join Server
5. Create and place furnace
6. Access Furnace
...

### Crash Report or Log

https://pastebin.pl/view/21edf5db

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

most recent bmc

### Optifine

No

**Comment by jaamesrone** [comment]
@SharkieTV

**Comment by Paradox0497** [comment]
So I went through the closed posts and someone had the same error. Removing the Jade mod fixed the issue but is there any way I could run the server with it?

**Comment by Paradox0497** [comment]
So it turns out that the Jade mod file that gets preinstalled with Better Minecraft v13 on CurseForge is outdates, Version 1.18-4.1.1 gets installed and 1.18-4.1.2 is the most recent version, After installing this updated version, my Better Minecraft server runs fine.
