### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Dark-Skar** [LunaPixelStudios/Better-Minecraft#491]
### Describe the Bug

In the game when I came across some coal ore I saw that the texture for the version in andesite had a debug texture.

### Reproduction Steps

1.Go into JEI
2.search "andesite coal ore"

### Screenshots and Videos

![2022-07-01_17 14 21](https://user-images.githubusercontent.com/108540752/176931993-cb7bbe45-641c-40d6-a233-9f1f3a556c01.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

**Comment by SharkieTV** [comment]
missing texture bug fix:
1. Locate the config folder for Excavated Variants
2. Open the minecraft.json file
3. Change the texture counts for iron, coal, and copper to 10
