### ISSUE TITLE
Backpacked and Carry On compatibility issue 

### ISSUE THREAD

**Issue by SugarHighAaron** [LunaPixelStudios/Better-Minecraft#492]
### Describe the Bug

The backpacked mod allows you to pick up a backpack off a shelf by crouching and interacting, however the carry on mod allows you to pick up chests and what not the same way, this action is prioritized, this makes the player un able to pick up placed backpacks.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/108596962/177020521-e8f0aaf5-9573-447e-ab25-6e3f2f5a8b88.mp4

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
I will fix this in another update, now i guess you can break the block instead?
