### ISSUE TITLE
New Dimensions Not Loading

### ISSUE THREAD

**Issue by Snowmaru128** [LunaPixelStudios/Better-Minecraft#494]
Everbright and Everdawn dimensions not loading.

Stuck on "loading terrain" screen

Fresh server, fresh mods on client and server side. No additional mods or resource packs enabled.

Logs from server during the event below.

04.07 07:07:36 [Server] Server thread/INFO [Waila/]: Syncing config to Playpen4Harambe (6f813329-61ad-4c60-be36-6d4248c3ac71)
04.07 07:07:36 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@26973824 (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:07:36 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@23c158df (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:07:37 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@26973824 (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:07:37 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@23c158df (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:08:42 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@26973824 (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:08:42 [Server] Netty Epoll Server IO #0/ERROR Could not serialize com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument@23c158df (class com.legacy.structure_gel.core.commands.BuildingToolCommand$PlayerNameArgument) - will not be sent to client!
04.07 07:08:42 [Server] Server thread/INFO [ne.bl.mo.ne.NetherPortalFix/]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:overworld] to ResourceKey[minecraft:dimension / blue_skies:everdawn]
04.07 07:08:42 [Server] Server thread/ERROR Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot@d87a628, suppressing error
04.07 07:08:42 [Server] INFO java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectset" is null
04.07 07:08:42 [Server] INFO at net.minecraft.server.level.DistanceManager.m_140828_(DistanceManager.java:259) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
04.07 07:08:42 [Server] INFO at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:2330) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:radium.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:radon.mixins.json:world.ThreadedAnvilChunkStorageAccess,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:446) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:radium.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin,pl:mixin:APP:radium.mixins.json:world.chunk_access.ServerChunkManagerMixin,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:857) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:backpacked.mixins.json:common.ServerPlayNetHandlerMixin,pl:mixin:APP:dragonmounts.mixins.json:EnsureSafeFlyingVehicleMixin,pl:mixin:APP:radium.mixins.json:entity.collisions.replace_streams.ServerPlayNetworkHandlerMixin,pl:mixin:APP:graveyard.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:wildbackport.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:classloading}
04.07 07:08:42 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.m_5797_(ServerboundMovePlayerPacket.java:16) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:classloading}
04.07 07:08:42 [Server] INFO at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:classloading}
04.07 07:08:42 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:classloading,re:mixin}
04.07 07:08:42 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
04.07 07:08:42 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:computing_frames,re:mixin,re:classloading}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.Min
![loading terrain](https://user-images.githubusercontent.com/108655108/177103151-0f3b8af9-065e-45ef-af7f-5160da94a2a6.png)
ecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
04.07 07:08:42 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
04.07 07:08:53 [Disconnect] User Mayhem1228 has disconnected, reason: Disconnected

**Comment by SharkieTV** [comment]
please resubmit with the template and not pasting all this text
