### ISSUE TITLE
Crashing game

### ISSUE THREAD

**Issue by zalathine** [LunaPixelStudios/Better-Minecraft#495]
### Describe the Bug

My computer can play normal Minecraft, but crashes with Error Code 1 whenever I try to use the mod. I've tried updating everything on my computer, uninstalling and reinstalling Curseforge and Overwolf and the mod pack. I'm using Minecraft version 1.19 (it won't let me select that so I had to select 1.18).

### Reproduction Steps

1. Open Curseforge
2. Click play on the mod pack (opens Minecraft)
3. Click play in the Minecraft window this the mod pack selected
4. Game crashes with Error Code 1

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

**Comment by SharkieTV** [comment]
Their is no 1.19 version of the modpack. Send me your latest.log with a pastebin link

**Comment by zalathine** [comment]
Ok so on Curgeforge, it says version 1.18.2, but when I open regular Minecraft, it says version 1.19. And I'm not sure how to do what you're asking.

**Comment by SharkieTV** [comment]
Can you show a screenshot?

**Comment by zalathine** [comment]
![Minecraft crash screenshot](https://user-images.githubusercontent.com/108685066/177231156-ffda1eba-aa7a-4627-add0-7d78825d3389.png)

**Comment by SharkieTV** [comment]
where does it say 1.19?

**Comment by zalathine** [comment]
If I switch to normal Minecraft, it says 1.19. I'll provide another screenshot to show you:
![Minecraft 1 19 screenshot](https://user-images.githubusercontent.com/108685066/177231327-131ad6ec-9671-4c68-8c26-ed0e02cc4a81.png)

**Comment by SharkieTV** [comment]
yeah thats just your launcher? thats not the modpack. I can also see you are not running v12.5 like you are saying so uninstall the modpack install it again

**Comment by zalathine** [comment]
Oh, my friends were using v10 and I was trying to play on a server with them, so that's why I was using that version. I've tried using v12.5 and the same thing happens. Thank you for your help by the way, I really appreciate it. I'm sure it's some setting or something on my computer that's messed up, but I haven't changed anything from when I uninstalled and reinstalled everything, so I'm not sure what it could be.

**Comment by SharkieTV** [comment]
last thing you can do is send me your latest.log with a pastebin link so i can see if their is an issue

**Comment by zalathine** [comment]
Like I said, I don't know how to do that. Can you send me instructions on how to do that?

**Comment by SharkieTV** [comment]
You go into your modpack folder which you can access from the CF Launcher, then you open the logs folder and you see a file called latest.log, you can either try to drag it here and upload it or go to pastebin and upload/drag the text in their and get a link

**Comment by zalathine** [comment]
I think I found it, it's a text file that I'm going to upload here:

[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/9042657/latest.log)

**Comment by SharkieTV** [comment]
AS I suspected it just cuts off giving me no info on the crash. Last thing that I can help with is could you try installing ATLauncher and installing the modpack and see if you can launch it?

**Comment by zalathine** [comment]
I tried doing that, but the upload of the modpack failed because the mod "Upgraded Netherite" no longer exists on the link provided. I'll try again though.

**Comment by zalathine** [comment]
*download

**Comment by SharkieTV** [comment]
It should prompt you to install projects that arent allowed by ATLauncher and it should work

**Comment by zalathine** [comment]
Yes, it allowed me to copy and paste the link to the mod, and the exact link didn't work. I found the mod on curseforge by itself, but it still isn't recognizing that I have the mod downloaded and won't let me open it without that mod.

**Comment by zalathine** [comment]
https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite/download/3773704

This is the link it gives me, and it won't recognize it without the mod being downloaded from this exact link

**Comment by SharkieTV** [comment]
Oh i see the Dev removed his Mod from 1.16.5 -_-,. well best is to wait for a new update

**Comment by zalathine** [comment]
Ok well thank you for your help!

**Comment by SharkieTV** [comment]
wait that doesnt make sense since this is 1.18, maybe that mod has been archived. is this for v11 or v12.5 on atlauncher?

**Comment by SharkieTV** [comment]
I just installed it with no issues, i pressed the open all in browser and it installed all of them for me and the modpack works
