### ISSUE TITLE
My nether is frozen

### ISSUE THREAD

**Issue by Vardul16K** [LunaPixelStudios/Better-Minecraft#496]
### Describe the Bug

Hello, this bug happened to me today, going into the nether. The bug is like all is frozen in nether, mobs, blocks, everything. Yesterday it was all good, went a few times and all okay, but today this happened to me. I go to nether, can't hit mobs, mobs doesnt hit me too and I don't know how to fix it. With this bug, i have to close the game because i can't return to overworld. This bug is only in nether dimension, the other dimensions are working well. 
Im playing it in 1.16.5 forge, and i don't know what i can do, so if anyone has an answer, I would apreciate so much, thanks.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

No

**Comment by SharkieTV** [comment]
Are you sure your on v56 or v57?

**Comment by Vardul16K** [comment]
![image](https://user-images.githubusercontent.com/108689310/177270133-e3f8db25-48b1-402c-8679-84d7d741b519.png)
 Yes, it's v56

**Comment by SharkieTV** [comment]
I have no issue with the nether, try installing v57
