### ISSUE TITLE
Blue Skies Dimensions Not Loading

### ISSUE THREAD

**Issue by Snowmaru128** [LunaPixelStudios/Better-Minecraft#498]
### Describe the Bug

Everbright and Everdawn dimensions not loading.

Stuck on "loading terrain" screen

Fresh server, fresh mods on client and server side. No additional mods or resource packs enabled.

### Reproduction Steps

1. Make new server, fresh 12.5 forge
2. Enter Everbright Portal
3. Stuck on infinite loading terrain screen

### Crash Report or Log

https://pastebin.com/LtenYW6M

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12.5

### Optifine

No

### Other Mods

None

**Comment by SharkieTV** [comment]
I have no issue with this on a server or singleplayer, who is your server host?

**Comment by Snowmaru128** [comment]
> I have no issue with this on a server or singleplayer, who is your server host?

Server host Is Apex Hosting

**Comment by SharkieTV** [comment]
Dunno then, no issues on my end and its mentioning packet issues. So i can only say its an issue with the host or network
