### ISSUE TITLE
Saving strawgolem save data

### ISSUE THREAD

**Issue by Thangkou** [LunaPixelStudios/Better-Minecraft#499]
### Describe the Bug

Server console constantly displaying issue 'Saving strawgolem save data'

### Reproduction Steps

1. start server
2. someone log in or even after no one is online
3. do nothing and issue will just run itself

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/60358710/177357483-fe2e36a8-d3bc-4a3b-9099-b92e8421ddcc.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft 12.5

### Optifine

No

**Comment by SharkieTV** [comment]
This is not an issue, the mod does that every 5 mins
