### ISSUE TITLE
Game crashes on teleport while streaming in discord.

### ISSUE THREAD

**Issue by BuckarewBanzai** [LunaPixelStudios/Better-Minecraft#5]
### Describe the Bug

Game reliably crashes while streaming to discord when using tp command or moving between dimensions. 

Fabric Version:  fabric-server-mc.1.18.1-loader.0.12.12-launcher.0.10.2.jar
Additional Mods: Dynmap-3.3-beta-2-fabric-1.18.jar, player-roles-1.5.0.jar

### Reproduction Steps

1. Stream game in discord voice call (application mode not screen)
2. Use tp command or attempt to move dimensions via portals.

### Crash Report or Log

https://gist.github.com/BuckarewBanzai/9598186d0efb5c3155eba46d4cbd9dd6

### Operating System

Windows 10 

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc fabric v8

### Optifine

No Optifine

### Other Mods

Dynmap-3.3-beta-2-fabric-1.18.jar
player-roles-1.5.0.jar

**Comment by SharkieTV** [comment]
Have you tried it without the mods you added?

**Comment by switchnlade** [comment]
@BuckarewBanzai Please try updating/reinstalling your Nvidia graphics driver. The reason for that is that this, "# C [nvoglv64.dll+0xd57d10]", is connected to the Nvidia graphics drivers.

**Comment by BuckarewBanzai** [comment]
> @BuckarewBanzai Please try updating/reinstalling your Nvidia graphics driver. The reason for that is that this, "# C [nvoglv64.dll+0xd57d10]", is connected to the Nvidia graphics drivers. Also possibly related to other overlays, but not certain on that one, too few sources to be sure. Overall, that's what I found online, hopefully it helps.
> 
> I also see you noted you had optifine, but at the same time you are on fabric. Are you using optifine via optifabric or was that an accidental wrong entry?

My apologies, I am not running optifine (I will update the issue). Updated my nvidia drivers to latest and issue persists. Also have other players that can replicate the issue. This problem existed before I added the player roles plugin and dynmap. It is a very strange bug.

**Comment by SharkieTV** [comment]
I have tried recreating it and im not getting the issue. Did you try uninstalling you java and install new one?

**Comment by switchnlade** [comment]
> My apologies, I am not running optifine (I will update the issue). Updated my nvidia drivers to latest and issue persists. Also have other players that can replicate the issue. This problem existed before I added the player roles plugin and dynmap. It is a very strange bug.
Very strange indeed due to as Sharkie said above, its a java issue with your pc. Try disabling any overlays that might be enabled, including overwolf from curseforge if you are using that modpack launcher since I see a few reports online talking of this. You could possibly try an older graphics driver too. Outside of that, since I can't replicate it doing the same streaming via app mode and tping to a location, I'm out of ideas and can't find much more on my google searches.

**Comment by BuckarewBanzai** [comment]
Thanks fellas. You've given me some places to look. I will try to eliminate some overlays and try again.

**Comment by SharkieTV** [comment]
You could try GDLauncher other than that there are too many variables with it being a PC specific issue.
