### ISSUE TITLE
Console stuck in thinking when starting server

### ISSUE THREAD

**Issue by jaamesrone** [LunaPixelStudios/Better-Minecraft#50]
### Describe the Bug

Console is stuck on thinking when starting 1.16.5 bmc server. Anyone know why it's causing that? Is it their servers problem just curious

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/00nmv62E

### Operating System

Window 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v54

### Optifine

No

**Comment by SharkieTV** [comment]
Whos your serverhost?

**Comment by Mixwiz** [comment]
It's possible that their server host is Bisect. I am using BisectHosting and my console also gets stuck at that exact same location.

[Server] [modloading-worker-17/INFO] [STDOUT/]: [ejektaflex.bountiful.data.json.JsonSerializers:register:14]: BOREG registering json ser

**Comment by SharkieTV** [comment]
there is not much that the pastebin is telling me and BOREG registering json ser doesn't mean anything. If it just freezes can you try a restart? I also dont know if you manually uploaded the mods or chose the pack, if you chose the pack and its not running maybe contact bisect and ask them why its just stopping?

**Comment by OgnistyPoland** [comment]
same problem, any ideas?

**Comment by SharkieTV** [comment]
Well since it works for me and everyone else it seems to be an issue with your pc specifically. You could try deleting it and using another serverpack other than that I cant help with it since it just stops.
