### ISSUE TITLE
Quests don´t appear

### ISSUE THREAD

**Issue by TheTonyCC** [LunaPixelStudios/Better-Minecraft#500]
### Describe the Bug

The missions of FTB Quest don´t appear

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Captura de pantalla ](https://user-images.githubusercontent.com/108764167/177410496-11a06b35-433a-49b6-a598-092c606467a0.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

**Comment by SharkieTV** [comment]
Not sure how you installed/downloaded the Modpack but your missing all the configs from he look of it. so please use CF Launcher and not mess with anything
