### ISSUE TITLE
Server still getting crashed with the modpack upgraded to v 57

### ISSUE THREAD

**Issue by HarryTsui313** [LunaPixelStudios/Better-Minecraft#503]
### Describe the Bug

server crashes after starting for the server for some time. (a few minutes)

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/QSwekDEE

### Operating System

Window10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v57

### Optifine

No

**Comment by SharkieTV** [comment]
v57 specifically told you not to use on an old world
