### ISSUE TITLE
"New Beginnings" quest doesn't autocomplete upon joining a friend's LAN world.

### ISSUE THREAD

**Issue by AK-41** [LunaPixelStudios/Better-Minecraft#504]
### Describe the Bug

The new beginnings quest in the quest logs doesn't autocomplete to acquire the "your NEW adventure" and "monster dictionary" books which has a dependency for completing the quest step for acquiring the blue journal. Every time he joined my world, it wouldn't be completed for him despite it saying so in the top right corner of the screen, and the same thing happened to me when I joined my world.

I don't know how important this is to progress in the world but yeah it's something I noticed as we're trying to do a joint-playthrough on the v57 version of the 1.16.5 FORGE version of the modpack.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

**Comment by SharkieTV** [comment]
LAN Is untested and for a reason it says so as its very buggy, best you can do is complete the quests on his side with cheats, /ftbquests_editing_mode and the they can right click the quests to complete
