### ISSUE TITLE
Exit Code -805306369

### ISSUE THREAD

**Issue by SugarHighAaron** [LunaPixelStudios/Better-Minecraft#506]
### Describe the Bug

game crashes when I try to open a existing world or make a new one

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/SugarHighAaron/aa2da937463defcca567df380b7dd17a

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v12.5

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Go into your saves/world folder in the modpack folder then delete the folder called serverconfigs and launch the game and see if that helps

**Comment by SugarHighAaron** [comment]
> 

Same result

**Comment by SugarHighAaron** [comment]
> > 
> 
> Same result

Update: I deleted, re downloaded the modpack, and moved the worlds save to the new download, I'm able to run said world for now
