### ISSUE TITLE
Crash error when going to Everbright

### ISSUE THREAD

**Issue by DanielDelRincon** [LunaPixelStudios/Better-Minecraft#507]
### Describe the Bug

When you open the portal and go to the everbright, the world/server crashs because a cunk could not be generated. Its imposible to even enter the world.

### Reproduction Steps

1. Create a new world.
2. Open the Everbright portal.
3. Enter the Everbright.
4. The world crash.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V11,5

### Optifine

No

**Comment by SharkieTV** [comment]
Need a crash report Id suggest you to update to v12

**Comment by DanielDelRincon** [comment]
> Need a crash report Id suggest you to update to v12

I solved generating a new everbright in the V12 and copying the archives to the V11,5. The crash repost was about the "Error generating Chunk in -3, 15"
