### ISSUE TITLE
Game freezing and crashing

### ISSUE THREAD

**Issue by BrokenMess** [LunaPixelStudios/Better-Minecraft#509]
### Describe the Bug

Here's what happens:

>Load up CurseForge
>Click play on Better Minecraft Modpack
>It's the only modpack downloaded
>It launches Minecraft Launcher with Better Minecraft [FORGE] - 1.18.2
>I click play again
>It loads the game up as normal
>I load up my world
>I play for 5 minutes
>The game suddenly freezes
>My screen starts flickering
>Game crashes

I fixed it by tabbing out and logging back in, but I'd rather not have to do this every 5 minutes so can someone help me?
It doesn't come up with an error message when this happens

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft v12.5

### Optifine

No

**Comment by BrokenMess** [comment]
Update: It also makes my desktop flicker when CurseForge is open

**Comment by SharkieTV** [comment]
Did you allocate enough ram? and whats your pc specs?

**Comment by BrokenMess** [comment]
So I have a brand new gaming laptop. I seem to have managed to fix the problem?
I think the issue came to loading new chunks since I've never played Better Minecraft before. Anyways, I explored a bit more and each time it crashed and flickered, I restarted the laptop. Now that I've played for a bit, the issue has just disappeared!
