### ISSUE TITLE
Crashing when making patterned banners

### ISSUE THREAD

**Issue by ghost** [LunaPixelStudios/Better-Minecraft#51]
### Describe the Bug

When I go to make a patterned banner with banners not in vanilla minecraft, the game freezes and then crashes. I can put the banner and dye in to the loom, but when I try to add the pattern, it crashes

### Reproduction Steps

1. get a banner (any colour) from inventory
2. get any colour dye
3. try to place the banner, dye, and pattern in a loom

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

**Comment by switchnlade** [comment]
Can you add in your crash log too? Just copy paste it to a site like [pastebin](https://pastebin.com/) then post the link here. Thanks.

**Comment by SharkieTV** [comment]
Cant help if we dont have a Crashlog.

**Comment by SharkieTV** [comment]
No Response
