### ISSUE TITLE
Missing Quotes in server start script

### ISSUE THREAD

**Issue by Greene1337** [LunaPixelStudios/Better-Minecraft#511]
### Describe the Bug

The closing quote was missing at the end of line 31 in start.sh
 
In this line:
31 echo "Something went wrong during the server installation. Please try again in a couple of minutes and check your internet connection.

### Reproduction Steps

Add a quote at the end of line number 31

like this:
echo "Something went wrong during the server installation. Please try again in a couple of minutes and check your internet connection."

### Operating System

ubuntu 18.04

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

**Comment by SharkieTV** [comment]
Unforntely I dont have ubuntu and I am unable to test if it works on it or not, so I cant help much other than you need to set up your own server without my files.
