### ISSUE TITLE
Squid and giant squid does not spawn

### ISSUE THREAD

**Issue by silvioUO** [LunaPixelStudios/Better-Minecraft#514]
### Describe the Bug

Squid does not spawn in the world, I can't find any squid in ocean, river and all the type of deep ocean. I can only find the glow squid. I encountered this glitch in better minecraft 1.18.2

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

### Other Mods

Mr Crayfish gun mod, adventurer compass, additional guns andframework

**Comment by SharkieTV** [comment]
Updated to latest version
