### ISSUE TITLE
(Server Pack) Console Output is not being displayed correctly (not legibly)

### ISSUE THREAD

**Issue by rotgruengelb** [LunaPixelStudios/Better-Minecraft#515]
### Describe the Bug

The Console Output/Command Responses/Chat Messages is not displayed correctly
Chat messages are completely unreadable (see "Screenshots & Videos")

I have no idea what this could have caused, and I did not come across anybody else that has this problem. 

When connecting with the Minecraft client, everything is normal.

### Reproduction Steps

1. Startup Server
2. Wait until World Generates (the texts/outputs/responses/chat messages are now weird)

### Screenshots and Videos

![Bildschirmfoto 2022-07-09 um 11 26 28](https://user-images.githubusercontent.com/75038404/178122585-efa82473-f759-482b-8ef6-fadbd0974ccc.png) 
![Bildschirmfoto 2022-07-09 um 23 10 56](https://user-images.githubusercontent.com/75038404/178122862-d2335f44-c2d1-45c2-a983-a0d3d00d56e7.png) 
![Bildschirmfoto 2022-07-09 um 23 17 54](https://user-images.githubusercontent.com/75038404/178122958-f47b49ed-3465-4066-a4ea-8134a67bd2bc.png)

### Operating System

Debian 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1

### Optifine

No

### Other Mods

no mods added

**Comment by SharkieTV** [comment]
yes its in v1 of the pack, things will be fixed in next updates

**Comment by SharkieTV** [comment]
If you want to fix Server Console Output not being Displayed Correctly remove Immersive Weathering

**Comment by rotgruengelb** [comment]
> If you want to fix Server Console Output not being Displayed Correctly remove Immersive Weathering

Okey
