### ISSUE TITLE
Frequent Crashing in Overworld

### ISSUE THREAD

**Issue by Lodac77** [LunaPixelStudios/Better-Minecraft#516]
### Describe the Bug

When exploring the overworld, there are areas that seem to crash any player that goes near them. The crash log mentions Twilight Forest rending and Occulus. **The crash log will always state ``java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.ShaderInstance.m_173350_(String, Object)" because "$$13" is null`` after crashes like this.** 

### Reproduction Steps

1. Open game, play on world.
2. Enter a "crash zone."
3. Game crashes.
...
Can be loading a new chunk or revisiting the same area you crashed before.

### Screenshots and Videos

:(
![3235131535131135unknown](https://user-images.githubusercontent.com/109001766/178123011-6ad09e09-0d61-4f54-bdb9-709b9c68376e.png)
![313535113unknown](https://user-images.githubusercontent.com/109001766/178123012-c2a09838-643b-443b-be10-102287d6389f.png)
A few of the crash logs, they're all the same really.
[crash-2022-07-09_16.57.19-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/9077949/crash-2022-07-09_16.57.19-client.txt)
[crash-2022-07-09_13.08.58-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/9077953/crash-2022-07-09_13.08.58-client.txt)
[crash-2022-07-08_23.27.46-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/9077954/crash-2022-07-08_23.27.46-client.txt)
[crash-2022-07-08_23.17.13-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/9077955/crash-2022-07-08_23.17.13-client.txt)

### Crash Report or Log

Attached above.

### Operating System

Windows 10, 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [FORGE] v12.5

### Optifine

No

**Comment by SharkieTV** [comment]
Please remove all the mods you added and not sure why you lied on here

**Comment by Lodac77** [comment]
I pasted all the mods I used in other mods I'm not sure why they arent there anymore. sorry
