### ISSUE TITLE
multiplayer game crashes after placing a storage network root without even interacting

### ISSUE THREAD

**Issue by siriux01** [LunaPixelStudios/Better-Minecraft#52]
### Describe the Bug

it was a normal multiplayer server i hosted. at first i got the "place furnace and crash" issue, now i got the "**place storage network root and crash**" issue. i believe there's no one issued this crash before, so here i am. i was able to recover the world save, by removing the placed storage network root in singleplayer. i was wondering what have caused this crash? p.s. i really love this modpack <3

### Reproduction Steps

1. place storage network root
2. server crashed
3. rebooted the server, and the 1 chunk that has the storage network root, didnt load at all. it's just a blank chunk of void spot. i did manage to recover the world as i mentioned before.

### Crash Report or Log

https://pastebin.com/z04SM5CU

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC Forge v13

### Optifine

I used Optifine

### Other Mods

No. I just added OptiFine in my client, not in the server

**Comment by SharkieTV** [comment]
Seems this is a known issue after FORGE changed something, best is to remove the mod or not place the block and wait till the dev brings out the fix
