### ISSUE TITLE
Better minecraft REI mod search fail

### ISSUE THREAD

**Issue by pacman0521** [LunaPixelStudios/Better-Minecraft#520]
### Describe the Bug

the minecraft mod pack better minecraft fabric edition has a mod called roughly enough items the search bar that you can find items with doesnt work for me and i was wondering if anyone else had this problem and fixed it.
### Reproduction Steps

1.i dont think it can be reproduced because my other friends can use it just not me
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1

### Optifine

No

**Comment by SHXRKIIE** [comment]
reinstall the modpack, dont change any settings on it
