### ISSUE TITLE
Infinite apple or golden apple

### ISSUE THREAD

**Issue by pamosa** [LunaPixelStudios/Better-Minecraft#525]
### Describe the Bug

Infinite food or blocks when rightclick an "Overweight Apple Block" from "Overweight Farming" with a hoe or hand.

### Reproduction Steps

1. Create a new world.
2. Find a Overweight Apple Block.
3. Right click it.
4. Craft a hoe and right click it.
5. Infinite food.

### Screenshots and Videos

https://user-images.githubusercontent.com/69703617/178165818-5aaba795-6a11-4b06-8a9a-633550365e82.mp4

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v2

### Optifine

No

**Comment by SHXRKIIE** [comment]
Thanks for the report, will most likely remove this mod due to it having an infinite food bug
