### ISSUE TITLE
Crash in v14 1.18.1 using simple storage network root.

### ISSUE THREAD

**Issue by Black94dragon** [LunaPixelStudios/Better-Minecraft#53]
### Describe the Bug

when setting up a storage system and placing down the 'network root' block the server crashes and the chunk gets corrupted

### Reproduction Steps

1. build a simple storage network (chest ,,> link cable > network cable > root > inventory > crafting grid)
2. place down 'network root' block
3. see the magic happen

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC V14

### Optifine

I used Optifine

### Other Mods

No, btw not everybody used optifine on the server.

**Comment by switchnlade** [comment]
Yeah, seems like it's related to the various forge changes. It's been reported to them so the only thing we can do is wait since certain mods require later forge versions. So for now, either ignore the mod or remove it.
