### ISSUE TITLE
Crash Placing Simple Storage Root Block

### ISSUE THREAD

**Issue by rithirin** [LunaPixelStudios/Better-Minecraft#54]
### Describe the Bug

When placing simple storage root block game crash's.

### Reproduction Steps

Just place the block.

### Crash Report or Log

https://pastebin.com/3Nu73fAL

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [Forge] v14

### Optifine

No

**Comment by switchnlade** [comment]
Known, remove simple storage network if it's recurring.
Duplicate of #53.
