### ISSUE TITLE
server

### ISSUE THREAD

**Issue by TameEnderman923** [LunaPixelStudios/Better-Minecraft#55]
### Describe the Bug

this isnt really a bug but it is still relevant I have a sever with my friends and when I updated to 54.5 version of this modpack I noticed that the server modlist didnt have all the mods that the client side had. Please correct me if I am wrong and if It has something to do with the fact I am using the curse forge launcher. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V54.5

### Optifine

No

### Other Mods

just missing mods on the server side when I downloaded it from the curse forge launcher.

**Comment by SharkieTV** [comment]
Server files dont need Client files.

**Comment by TameEnderman923** [comment]
when I tried to join the server it said mismatched mods

**Comment by TameEnderman923** [comment]
> Server files dont need Client files.

then why does the server say mismatched mods when I try to join the server I haven't added any mods

**Comment by switchnlade** [comment]
Verify your modpack versions and installs, both for the server and client. V54.5 server and client packs connect just fine on my end without modification.

**Comment by TameEnderman923** [comment]
> Verify your modpack versions and installs, both for the server and client. V54.5 server and client packs connect just fine on my end without modification.

will it have something to do with the fact i tried removing dynvewdist mod from both the server mod folder and the client side mod folder

**Comment by switchnlade** [comment]
Possible, only suggestion I can give is revert the pack back to the original state, then modify it, and be ready to revert any changes you do.

**Comment by SharkieTV** [comment]
Also have no problem connecting, so its either you didn't update it properly or the modpack didn't install properly.

**Comment by TameEnderman923** [comment]
> Also have no problem connecting, so its either you didn't update it properly or the modpack didn't install properly.

im just rein installing the modpack and the server folder and not deleting anything. I wanted to try an remove the dynviewdist mod because I didnt like that I could just see the sky while I was mining but I also wanted the view distance of the server to stay at 8chunks of renderdistance and not lower or go higher than that.

**Comment by switchnlade** [comment]
Well, I just removed dynviewdist's jar file without issues on both server and client, connected just fine. Overall, something went wrong somewhere, but what you are asking for is indeed possible and does work.

**Comment by TameEnderman923** [comment]
> Well, I just removed dynviewdist's jar file without issues on both server and client, connected just fine. Overall, something went wrong somewhere, but what you are asking for is indeed possible and does work.

Its fine now, srry for wasting your time and yes something did go wrong because when I removed the mod from both ends everything started to break for me atleast.
