### ISSUE TITLE
Limited Nether Biomes

### ISSUE THREAD

**Issue by BloomQue64** [LunaPixelStudios/Better-Minecraft#57]
While wondering the nether in v54, I've noticed there are at most, around 15 biomes that spawn out of the many biomes this modpack has put together. While I don't have a list of biomes that do spawn, I do have a rough list of biomes that don't.
- Basalt Deltas
- Warped Forest
- Crimson Forest
- Almost all of the biomes from Better Nether and Oh the Biomes you'll go
This bug is easily reproducible by using the /locatebiome command in game.

The mod list is the same, except I've added Quark oddities.

**Comment by Dinoslasher11** [comment]
Have you tried other worlds, also what worldtype are you using

**Comment by BloomQue64** [comment]
> Have you tried other worlds, also what worldtype are you using

I'm using the Default world type. And I believe this is my 4th world, and it's still happening.

**Comment by SharkieTV** [comment]
It has bee reported here to the Dev: [#53](https://github.com/Someone-Else-Was-Taken/BetterNether-Reforged/issues/53)
Best you can do is remove Better Nether and reset your nether
