### ISSUE TITLE
Chunks won't load after player clicks respawn button in server.

### ISSUE THREAD

**Issue by JosephJoJoDa** [LunaPixelStudios/Better-Minecraft#58]
### Describe the Bug

If a player joins the game and never die, the chunk loading is working fine.  But, If the player dies once, the unloaded chunks triggered by this player will never load unless the player re-logins the server. 

### Reproduction Steps

1. Join the server.
2. Dead and click the respawn button
3. The unloaded chunks are triggered by this player won't load.
...

### Crash Report or Log

As the server still working, no log was given. ;(

### Operating System

Linux

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MInecraft v53.5

### Optifine

No

**Comment by SharkieTV** [comment]
Hi, sorry for late reply, this seems like an issue I cant replicate, can you provide a video?

**Comment by SharkieTV** [comment]
No Response
