### ISSUE TITLE
No loran flowers and crafting recipes not working for some blocks

### ISSUE THREAD

**Issue by FaithMalik** [LunaPixelStudios/Better-Minecraft#59]
I can’t seem to find Loran flowers anywhere in my world. Im currently on version 54 of the 1.16 pack. 
I also am using Forge. 
I also notice that blocks such as tuff and variants of deep slate are uncraftable in the crafting table and as for tuff it is not recognised when doing commands such as giving a player the item.

**Comment by FaithMalik** [comment]
Also I’m using Forge

**Comment by SharkieTV** [comment]
Next time please use the template that is provided. Lorans doesn't spawn in the overworld anymore after v52, you get it from the Void Worm Quest. You need to use Stone cutter on Cobbled Deeplsate to get the variants not crafting table. And the tuff command works.
![2022-01-26_10 53 10](https://user-images.githubusercontent.com/79353591/151096433-a2a16df3-058b-417d-aee5-98d07ed4cb5a.png)
![2022-01-26_10 53 35](https://user-images.githubusercontent.com/79353591/151096437-e22931ed-631b-496c-8074-bbf86fa830c2.png)
