### ISSUE TITLE
Random occasional crashes due to waterfall clouds(maybe?)

### ISSUE THREAD

**Issue by PooPooUndees** [LunaPixelStudios/Better-Minecraft#6]
### Describe the Bug

Random occasional crashes with no known cause or reason on a dedicated server. Sometimes can cause a crash on joining the server.

### Reproduction Steps

Sadly, no idea how to reproduce the bug and I don't know what the crash report is trying to tell me.

### Crash Report or Log

https://pastebin.com/jWbCULCU

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v8.5

### Optifine

No

### Other Mods

Crash occurred before I added any additional mods. Here are 3 additional crash-reports from previous versions of the pack.
https://pastebin.com/ijqY1Qkq - bmc v7
https://pastebin.com/3cVDMehU - bmc v8
https://pastebin.com/uQDVNcFQ - bmc v8

All crashes seem related to "WaterfallCloudGenerators" and produce the same error of "java.util.ConcurrentModificationException"

**Comment by SharkieTV** [comment]
The mod Effective is causing the Crash, remove it and it should be fixed. Will probably remove it in next update.

**Comment by PooPooUndees** [comment]
Ya, took me a while to realize that "effective" was the name of the mod and not a class/package name or something lol but you can also set "enable-waterfall-particles" to false to prevent further crashes and to significantly improve fps, tho the mod only adds that and splash particles so not much different from removing it.
