### ISSUE TITLE
Mismatch data issue 

### ISSUE THREAD

**Issue by timingplanet** [LunaPixelStudios/Better-Minecraft#60]
### Describe the Bug

Having a issue where i keep getting a mismatching data for a bunch of mods when everything matches and works fine in game but it keeps saying a bunch of mods arent loaded when they are.

### Reproduction Steps

1. Make bisect better minecraft server
2. Join server
3. Receive mismatch data pop up 
...

### Screenshots and Videos

https://imgur.com/a/AZm98NI

### Crash Report or Log

https://pastebin.com/SmCSaWNx

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better minecraft frabric v12

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/rats-mischief Note was having the issue before this mod was added

**Comment by SharkieTV** [comment]
Even as you say things are matching, it doesnt, make sure your configs and mods are the same.

**Comment by switchnlade** [comment]
I got the same when I updated my local v11.5 server to v12, but after clicking synchronize config on my client, it worked on the second try for joining.

The config that was synchronized according to the server's log:
```[22:42:33] [Netty Server IO #1/INFO]: [bclib] Client requested 1 Files:
[22:42:33] [Netty Server IO #1/INFO]: [bclib]   - bclib.CONFIG_betternether.generator
[22:42:33] [Server thread/INFO]: [bclib] Sending 1 Files to Client:
[22:42:33] [Server thread/INFO]: [bclib]        - bclib.CONFIG_betternether.generator (1855 Byte)```

**Comment by SharkieTV** [comment]
try disabled synchronizing in the bclib config on server

**Comment by SharkieTV** [comment]
No response
