### ISSUE TITLE
Custom buttons are rendered on F3 + ESC

### ISSUE THREAD

**Issue by Awakened-Redstone** [LunaPixelStudios/Better-Minecraft#61]
### Describe the Bug

When pressing F3 + ESC the Suport Sharkie, Report Bugs and Discord buttons are shown

### Reproduction Steps

1. Load into a world
2. Press F3 + ESC

### Screenshots and Videos

![2022-01-25_22 02 15](https://user-images.githubusercontent.com/40528665/151085683-cd71980f-10bb-4010-b1af-70a332c0a8ba.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

### Other Mods

[Fabric Chunk Pregenerator](https://www.curseforge.com/minecraft/mc-mods/chunk-pregenerator-fabric/)
[Item Scroller](https://www.curseforge.com/minecraft/mc-mods/item-scroller/)
[Malilib](https://www.curseforge.com/minecraft/mc-mods/malilib/)

[Blur](https://www.curseforge.com/minecraft/mc-mods/blur/) disabled due to bad performance

**Comment by SharkieTV** [comment]
What mod adds the keybind F3 + ESC? Is it chunk pregen? Also you should not be playing when you are pregenning
