### ISSUE TITLE
Worldgen stops after a certain percentage

### ISSUE THREAD

**Issue by nonatee** [LunaPixelStudios/Better-Minecraft#63]
### Describe the Bug

when loading a world for the first time, the worldgen stops after an error pops up in the log.

### Reproduction Steps

1. literally just make a world.
2.
3.
...

### Crash Report or Log

https://paste.ee/p/pObsu

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

54.5

### Optifine

No

### Other Mods

nope

**Comment by switchnlade** [comment]
Try removing OSV from the mods folder

**Comment by nonatee** [comment]
It worked, thanks but what is the OSV mod?

**Comment by switchnlade** [comment]
It places ores on the various stone blocks in the game, pretty much seems like something went wrong on world gen but it's pretty rare to get as there's been limited reports of it.

**Comment by nonatee** [comment]
will it break my world?

**Comment by switchnlade** [comment]
Nope, it'll be fine
