### ISSUE TITLE
Can´t obtain Alchemist Table and Summoner Table in Survival

### ISSUE THREAD

**Issue by 0TheCho0** [LunaPixelStudios/Better-Minecraft#66]
In blue skies for some reason you can´t obtain the alchemist table and the summoning table if you are in survival, if you open loot bags in creative you can obtain them.

**Comment by SharkieTV** [comment]
Get it from killing the Blue Skies boss, this is also not an issue you should be asking here, there ius a discord for questions

**Comment by clauxzie** [comment]
You will only obtain the summoning table from killing the summoning boss, otherwise not possible. If you have an issue with the rarity of the drop, it could be an issue with your game or files of the modpack. Please elaborate further if this doesn't help you.
