### ISSUE TITLE
Dark Enchantment erases all Level after enchanting

### ISSUE THREAD

**Issue by DaWindschief** [LunaPixelStudios/Better-Minecraft#68]
### Describe the Bug

When you put your Tool (or something else) in the Dark Enchantment Table, the price is usually shown and lower than the amount of EXP you have. Nevertheless all Level are gone after one enchantment.

### Reproduction Steps

1. Have a Tool or so and the Dark Enchantment Table and enough Level for the Enchantment (better more for visibility)
2. Put your stuff in it
3. Enchant
... 

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

### Other Mods

Only better Minecraft

**Comment by SharkieTV** [comment]
This mod I will probably remove since the dev isn't updating the fixes

**Comment by DaWindschief** [comment]
Yes its Fabric. Im sorry that i cannot add a Video right now because this problem only occures on a Server that im playing on i cant replicate it in singleplayer. 

Usually it was with kind of slightly higher Exp than the cost showed.

**Comment by SharkieTV** [comment]
Remove the Mod , it will be removed next update
