### ISSUE TITLE
Advancement impossible 

### ISSUE THREAD

**Issue by Kaledoss** [LunaPixelStudios/Better-Minecraft#69]
### Describe the Bug

Croptopia does not show every recipe. So I can't craft every item to eat and can't reach the achievement 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11 

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V12

### Optifine

No

**Comment by SharkieTV** [comment]
Can you show what recipes?, seems like the mod might not be completed yet.
