### ISSUE TITLE
torch slab mod and lanterns

### ISSUE THREAD

**Issue by SilverSavage98** [LunaPixelStudios/Better-Minecraft#7]
### Describe the Bug

Both regular Lanterns and Soul Lanterns when placed on a slab (like hung from the ceiling) currently take 200% longer to mine and are not dropped upon breaking, despite using a tool that normally works. 

### Reproduction Steps

1.Place a slab on the top half a block
2.Place a lantern on the bottom of that slab
3.try mining with a pick, takes longer than normal and isnt dropped to the player. Breaking animation from the WYLA mod (not sure which one it is) turns red.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC v10

### Optifine

I used Optifine

**Comment by SharkieTV** [comment]
Can you provide a screenshot? I am trying to replicate it but cant

**Comment by SharkieTV** [comment]
Seems like the Torch Slab mod is causing the issue, remove it server and client

**Comment by SilverSavage98** [comment]
Okay! Not super worried about it, just wanted to let you know. Thank you!
