### ISSUE TITLE
Modpack crashing on start after updating to v15

### ISSUE THREAD

**Issue by CalualaMic** [LunaPixelStudios/Better-Minecraft#70]
As the title says I cant open my modapck anymore. After i launched it ti just crashes with code 0 and nothing else. Heres the log:
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7963481/latest.log) (also its the 1.18.1 forge version)

**Comment by SharkieTV** [comment]
Please use the template next time its their for a reason, this log doesnt tell me anything and just cuts off at Optifine so maybe remove that.

**Comment by SharkieTV** [comment]
No Response
