### ISSUE TITLE
Game crash after launch from Launcherfenix 1.16.5

### ISSUE THREAD

**Issue by ImExon** [LunaPixelStudios/Better-Minecraft#71]
### Describe the Bug

When I run the game, it opens, loads a couple of mods and closes giving me "(exit code -1)" 

I only have this mod installed and forge 1.16.5 

### Reproduction Steps

1. Launch Launcherfenix
2. Launch game with forge 1.16.5
3. It opens
4. Load a few mods and closes (exit code -1)

### Crash Report or Log

https://gist.github.com/ImExon/239bcadfa48a6fab64854140d11c81a3#file-gistfile1-txt

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better+Minecraft+[FORGE]+v54.5

### Optifine

No

### Other Mods

Only this

**Comment by switchnlade** [comment]
We do not support pirated launchers. Buy MC and then try again on either Curseforge, GDLauncher, or MultiMC.

![image](https://user-images.githubusercontent.com/96159041/151669326-f3c036f4-2e48-4b87-bb71-bc3895927e81.png)
