### ISSUE TITLE
Server Crash On Chunk load

### ISSUE THREAD

**Issue by wackyzane** [LunaPixelStudios/Better-Minecraft#73]
### Describe the Bug

After exploring the world for a couple hour the game crashed. I assumed it crashed on a chunk load as all we were doing was riding boats along the shore. Now the server crashed whenever we load into the server and the furthest chunks load.

### Reproduction Steps

1. Start Server
2. Load in
3. Crash
...

### Crash Report or Log

https://pastebin.com/ZfeKerWL

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

### Other Mods

****

**Comment by SharkieTV** [comment]
See if removing the Hedgehog mod worrks

**Comment by wackyzane** [comment]
> See if removing the Hedgehog mod worrks

This fixed the issue. Thank you!
