### ISSUE TITLE
Can't drop head of any mobs!

### ISSUE THREAD

**Issue by brayanluc** [LunaPixelStudios/Better-Minecraft#74]
### Describe the Bug

I can't drop any head! I want to drop wither skeleton head but they don't drop nothing but stone sword and soul star (I guess is this the name of the item) 
Sorry, forgot to mention it, i tested a mod called "JustMobHeads" to raise the percentage of head drops and put it on 100% and nothing happens, so I guess the problem is on modpack...

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMC Fabric v11.5 

### Optifine

No

**Comment by SharkieTV** [comment]
Its working for me, see if updating to v12 fixes it otherwise it does work
