### ISSUE TITLE
Crash error on launch v15

### ISSUE THREAD

**Issue by Indraxo** [LunaPixelStudios/Better-Minecraft#75]
### Describe the Bug

i just installed the packs latest version and whenever its launched it crashes and says error code 0 i have checked java/drivers etc and all is fine even reinstalled just incase, fabric version runs fine aswell as other packs only this one having issues, and there was 1 other ticker of the same issue. Think its caused by the latest update to the pack?

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/CRCwak8w

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better minecraft 1.18.1 v15

### Optifine

No

### Other Mods

no, i didnt use other mods

**Comment by switchnlade** [comment]
Try using GDLauncher or MultiMC, see if that fixes it up.

**Comment by SharkieTV** [comment]
No Response
