### ISSUE TITLE
Inventory shows when closed

### ISSUE THREAD

**Issue by Farix2** [LunaPixelStudios/Better-Minecraft#76]
### Describe the Bug

I see my inventory on my screen even if i close my inventory, the gui for my inventory goes away but all the items and where they were placed stay on my screen blocking my view

### Reproduction Steps

all i did way open the game and put stuff in my inventory

### Screenshots and Videos

![2022-01-30_20 30 41](https://user-images.githubusercontent.com/98723329/151731541-58880b85-fba5-4324-bb28-824dd4751515.png)
![2022-01-30_20 30 43](https://user-images.githubusercontent.com/98723329/151731561-567c8510-f5de-4a11-952f-8160e3633738.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v13

### Optifine

No

### Other Mods

The Wild Mod

**Comment by switchnlade** [comment]
Please use this for bug reports. General questions can be answered on our discord, as for the answer, try pressing 'i', it's what brings up the inventory HUD by default.
