### ISSUE TITLE
the abyss mod

### ISSUE THREAD

**Issue by beenuboi** [LunaPixelStudios/Better-Minecraft#77]
### Describe the Bug

I am attempting to get into the abyss however there isn't any loran plants or ore spawning in my world. I looked at the book you get after defeating the void worm and it gives me errors:
"Error building entry theabyss:flora/loran
Error while loading entry theabyss:flora/loran page 1
Failure parsing state matcher
Unknown block type 'theabyss:loranflower' at position 0: <--[HERE]
Check your log for more"
I checked the logs for the minecraft server however as I am not a programmer or coding genius, I was unable to remedy the issue.

### Reproduction Steps

1.I finished all quests in the end dimension
2.noticed there are no loran plants in the overworld
3.checked book "The Abyss: chapter II" and saw "loading error! (hover for info)"
...

### Screenshots and Videos

![2022-01-31_14 36 49](https://user-images.githubusercontent.com/98777564/151870682-32c89e4d-00bb-4036-b315-9ce132bdd578.png)

### Operating System

windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v52.5

### Optifine

No

**Comment by SharkieTV** [comment]
Did you update the pack from an old world before v52?

**Comment by beenuboi** [comment]
I did not. I started fresh.

**Comment by SharkieTV** [comment]
See if updating the Abyss mod to 2.2 or above fixes it, please make sure to back up your world
