### ISSUE TITLE
Game crashes while flying through world

### ISSUE THREAD

**Issue by warrenonedge** [LunaPixelStudios/Better-Minecraft#79]
### Describe the Bug

Describe the Bug
Server crashes when flying around loading chunks. May be related to reported Graveyard issue but crash reports say issue with HedgehogBirchTreeFeature:

java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at net.orcinus.hedgehog.world.gen.HedgehogBirchTreeFeature.m_142674_(HedgehogBirchTreeFeature.java:40) ~[hedgehog-1.1.0.jar%23113!/:1.1.0] {re:classloading}

### Crash Report or Log

https://pastebin.com/7QuzDh6u https://pastebin.com/R1WcYwHj

### Operating System

Ubuntu 18.04.5 LTS (Hosting Server using Forge Installer --installServer cmd line option)

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

### Other Mods

WorldEdit

**Comment by warrenonedge** [comment]
sorry didn't see #73. Im goign to try removing the hedgehog mod to see if that fixes it.

**Comment by warrenonedge** [comment]
This issue appears to be fixed in Hedgehog v1.1.1/v1.1.2 
https://github.com/0rc1nus/Hedgehog-Main/commit/a9a83bae587a5e63b77cfee33455e55c3708a47a

**Comment by warrenonedge** [comment]
Removing Hedgehog mod does fix the issue but couldn't hurt to update to latest version.

**Comment by SharkieTV** [comment]
an update will come out when I have time
