### ISSUE TITLE
watching server error on local server open

### ISSUE THREAD

**Issue by Lawdwynn** [LunaPixelStudios/Better-Minecraft#8]
### Describe the Bug

Running the server on a i7-7700K and 10GB dedicated ram, server opens but once a player connects one is unable to interact with the world, all entities are frozen, and the server disconnects said player and shortly closes after. Crash reports state the server crash was a watchdog server error

### Reproduction Steps

1. Launch server.
2. Connect to server.
3. After 60 seconds player(s) connected disconnects and receives java.io.IOException error
4. Server crashes shortly after.

### Crash Report or Log

https://pastebin.com/SgAD41BQ

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v51

### Optifine

No

### Other Mods

Chunk Loaders for 1.16 by SuperMartijn642 on CurseForge

**Comment by SharkieTV** [comment]
Remove the enchant with mob mod form server and client
