### ISSUE TITLE
Gameplay Issue

### ISSUE THREAD

**Issue by LoPoBiaGoodra** [LunaPixelStudios/Better-Minecraft#80]
The gameplay is very difficult, is not very smooth, a lot of lag spikes, and I'm playing on solo player, do I need a better computer? How do I fix this?

**Comment by SharkieTV** [comment]
Yes you probably need a better pc or need to allocate more ram

**Comment by LoPoBiaGoodra** [comment]
I'm sorry, I asked on discord but after sending this I found the right channel to ask, I'll work on getting a better pc then, I'm really excited to play your mod, thanks for your hard work!
