### ISSUE TITLE
Server stuck when starting

### ISSUE THREAD

**Issue by BartDotRun** [LunaPixelStudios/Better-Minecraft#82]
### Describe the Bug

Server gets stuck when starting, always on `[modloading-worker-31/INFO] [STDOUT/]: [ejektaflex.bountiful.data.json.JsonSerializers:register:14]: BOREG registering json ser`
Issue was reported before [here](https://github.com/LunaPixelStudios/Better-Minecraft/issues/50)

### Reproduction Steps

1. Start server
2. Wait for server to freeze
3.
...

### Crash Report or Log

https://pastebin.pl/view/79bfc89f

### Operating System

3rd party host (bisect)

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v54.5

### Optifine

No

**Comment by switchnlade** [comment]
Try removing bountiful, it's stalling on their processes it looks like.

**Comment by BartDotRun** [comment]
> 

When I do that it freezes 2 lines before it: [pastebin](https://pastebin.pl/view/9c315522)

**Comment by switchnlade** [comment]
How are you installing the modpack onto bisect? Their install or are you manually doing it? Overall this is the same as the issue you linked, random with no cause that would make sense. I can't personally get it nor has Sharkie, and there's only a few reports (this and the one you linked).

**Comment by BartDotRun** [comment]
> How are you installing the modpack onto bisect? Their install or are you manually doing it? Overall this is the same as the issue you linked, random with no cause that would make sense. I can't personally get it nor has Sharkie, and there's only a few reports (this and the one you linked).

I have installed it manually

**Comment by BartDotRun** [comment]
Another update on it: After deleting the world folder (and adding bountiful to the mods folder again) the server does start again with the fresh world.

**Comment by switchnlade** [comment]
Interesting, everything is working fine with that fix?

**Comment by BartDotRun** [comment]
Well, the world is 2 days old now, so I would prefer to be able to play with the existing world. I will try to isolate the problem further.

**Comment by BartDotRun** [comment]
It is fixed, the server is starting once again. These are the steps I did (not sure which of these are the reason that fixed it)

1. server not starting
2. remove the bountiful jar from /mods
3. start server (still freezes)
4. backup /world and remove /world
5. add the bountiful jar to /mods again
5. start server (generates a new /world)
6. remove /world (the fresh world)
7. restore old world file to /world
8. start server

**Comment by switchnlade** [comment]
Thanks for testing and figuring this out for us, really does help since we can't really personally test it. Most likely what fixed it was temporarily taking out the world folder if I had to guess. As to why? No idea.
