### ISSUE TITLE
The audio is error

### ISSUE THREAD

**Issue by BrenWolfpha** [LunaPixelStudios/Better-Minecraft#84]
### Describe the Bug

Some of the audio like breaking block audio is still okay but eating audio, mobs audio, and others doesnt work. How do I fix this?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

The new one :)

### Optifine

No

### Other Mods

Nope

**Comment by SharkieTV** [comment]
See if removing dynamic sound filters mod helps, if that doesnt work try a reinstall and if that doesnt work then its something with your pc
