### ISSUE TITLE
mineshafts Nether errors

### ISSUE THREAD

**Issue by kvermaat** [LunaPixelStudios/Better-Minecraft#86]
### Describe the Bug

i got some isseu's with mineshafts in the nether, the chests give "False MAIN_HAND" error and after a while the chuck save error. (even deleted the chunks but it's still happening) BMC 1.18.1 v15

option did you use optifine (tested with and without)

### Reproduction Steps

1. go to nether 
2. go to mineshaft with minecrat chest (the more the better)
3. open chest 
3.1. get error False MAIN_HAND (in cmd not in minecraft gui)
4. after being there a while ( in the nether mineshaft) the chunk will get chuck errors and overload and won't save
...

### Screenshots and Videos

![unknown](https://user-images.githubusercontent.com/1015046/152375658-378fb4d3-7e49-4805-97bd-3425b6a7acb6.png)

### Operating System

Ubuntu with java openjdk version 17.0.1, client windows 11/10 forge client

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC V15

### Optifine

No

### Other Mods

only mods that are with the BMC 1.18.1 v15 modpack

**Comment by TelepathicGrunt** [comment]
Can you please share you latest.log file after the issue comes up. Without the log, there isn't much we can do to help or troubleshoot. You can get the latest.log from the logs folder above the mods folder.

**Comment by SharkieTV** [comment]
Please dont just copy and paste it in here either.

**Comment by kvermaat** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8004056/latest.log)

im going to update to the new version as well, maybe that will  help

**Comment by kvermaat** [comment]
oh and the mineshaft goes through bedrock
![image](https://user-images.githubusercontent.com/1015046/152553087-63528b29-2628-40c3-b077-5ec09198a962.png)

**Comment by TelepathicGrunt** [comment]
The mineshaft going through bedrock is intentional as vanilla does the same. As long as it doesn’t make a hole into the void under the world, it’s fine https://preview.redd.it/n60zw2et45sz.png?auto=webp&s=6b23d70ffd4ec15b6520eec85cdee7770c4d44f9

**Comment by TelepathicGrunt** [comment]
Your log doesn't show anything about the issue. No `error False MAIN_HAND` or chunk errors or anything. Make sure when you share the latest.log that it is right after the issue actually occurred. The latest.log is rewritten every time you start up Minecraft.

**Comment by kvermaat** [comment]
correct that is what i'm saying you only see those errors in the cmd line

**Comment by kvermaat** [comment]
chunk errors where not present this time, they where not new this time

**Comment by kvermaat** [comment]
hi here is a old log with the chucks not saving (edited the external ips from players).
[2022-02-01-1.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/8004293/2022-02-01-1.log)

**Comment by kvermaat** [comment]
Error False MAIN_HAND is gone after update to BMC v16 and Forge-1.18.1-39.0.66

i'm going set this server to live and test if the chunk isseu's are gone as well.

**Comment by kvermaat** [comment]
update is the fix 👍
