### ISSUE TITLE
Game instantly crashes

### ISSUE THREAD

**Issue by MajestikPanda77** [LunaPixelStudios/Better-Minecraft#88]
### Describe the Bug

I can not load the game at all.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

<script src="https://gist.github.com/MajestikPanda77/f48261c74236d70cfd56d0b5b6bcd837.js"></script>

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc fabric v13

### Optifine

No

**Comment by SharkieTV** [comment]
Outdated, try a fresh isntall
