### ISSUE TITLE
Slow chunk loading

### ISSUE THREAD

**Issue by quiverslug** [LunaPixelStudios/Better-Minecraft#89]
### Describe the Bug

Chunks are very slow to load. It's not so bad while walking around, but if using a boat or flying in creative it can be very annoying since every 30 seconds or so I have to stop to wait for the world to load in front of me.

### Reproduction Steps

1. Move around the world
2. Wait for chunks to load

### Screenshots and Videos

https://thumbs.gfycat.com/SparklingLoathsomeAmericanwarmblood-mobile.mp4
Short clip to show that the chunks load very slowly, also shows what graphics settings I am using and my F3 screen.

https://i.imgur.com/33m1e2Z.png
A static screenshot of my F3 screen.

### Operating System

Linux Mint 20.3

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v13

### Optifine

No

### Other Mods

N/A

**Comment by SharkieTV** [comment]
Seems like your pc is struggling to load chunks as I don't have this issue, I can fly in creative in a straight line without having loading issues. I might suggest try another launcher or this could be an issue with Linux Mint 20.3 as I use Windows 10 and im not familiar with other OS

**Comment by quiverslug** [comment]
> Seems like your pc is struggling to load chunks as I don't have this issue, I can fly in creative in a straight line without having loading issues. I might suggest try another launcher or this could be an issue with Linux Mint 20.3 as I use Windows 10 and im not familiar with other OS

I don't see why my pc would be struggling to load chunks considering the game runs fine otherwise. In vanilla I can play with 12 chunks and never run into any issues with loading.

**Comment by SharkieTV** [comment]
> > Seems like your pc is struggling to load chunks as I don't have this issue, I can fly in creative in a straight line without having loading issues. I might suggest try another launcher or this could be an issue with Linux Mint 20.3 as I use Windows 10 and im not familiar with other OS
> 
> I don't see why my pc would be struggling to load chunks considering the game runs fine otherwise. In vanilla I can play with 12 chunks and never run into any issues with loading.

Its not running fine as you can see? and not sure why you would compare vanilla to Modded with over 200 Mods?
I can't do much to help since there is no issue on my end or others. Only thing i can suggest is removing Terralith and CaveTweaks mod other than that your PC clearly is not running the modpack fine

**Comment by quiverslug** [comment]
> > > Seems like your pc is struggling to load chunks as I don't have this issue, I can fly in creative in a straight line without having loading issues. I might suggest try another launcher or this could be an issue with Linux Mint 20.3 as I use Windows 10 and im not familiar with other OS
> > 
> > 
> > I don't see why my pc would be struggling to load chunks considering the game runs fine otherwise. In vanilla I can play with 12 chunks and never run into any issues with loading.
> 
> Its not running fine as you can see? and not sure why you would compare vanilla to Modded with over 200 Mods? I can't do much to help since there is no issue on my end or others. Only thing i can suggest is removing Terralith and CaveTweaks mod other than that your PC clearly is not running the modpack fine

When I say runs fine I mean it's running at 90-100+ FPS at basically all times, but whatever, thanks for the tip ill try that
