### ISSUE TITLE
Trapdoors open/close simultenously

### ISSUE THREAD

**Issue by Cetins** [LunaPixelStudios/Better-Minecraft#90]
### Describe the Bug

When I click to a trapdoor, all trapdoors nearby open/close simultenously.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/69481095/152526673-18fe6542-3407-4b79-99c5-248c4ba5c568.mp4

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V14

### Optifine

No

### Other Mods

No Mods added, just better minecraft modpack over curseforge app.

**Comment by switchnlade** [comment]
Not a bug, this is a feature of the Double Doors mod, if you do not like it, toggle the feature in the doubledoors-fabric.json file in the config folder and set "enableTrapdoors": to false. This is the desc of the mod from their page:

Double Doors is a minimalistic mod which adds the ability for identical double doors, trapdoors and fence gates to be opened simultaneously. This can be done by clicking any of the (wooden) doors, or via a single pressure plate or button. By default the mod will also find other connected door-type blocks and open those, up to a maximum of 10 blocks away. This can be toggled in the config.

Crouching will disable the double door feature and open/close the single block only.

**Comment by Cetins** [comment]
Silly me :) thanks
