### ISSUE TITLE
No Modded Structures except for Graveyard

### ISSUE THREAD

**Issue by Kasszii** [LunaPixelStudios/Better-Minecraft#92]
### Describe the Bug

After the newest update I made a new world for hardcore and traveled for hours before I realized that I hadn't seen any modded structures other than the graveyards. I did not find stoneholms, "the good place", the fishing house or the towers which are fairly common. I used locate command to double check and sure enough there are none of them in the world. I made another world in a completely squeaky clean instance to double check it wasn't me, and the problem persisted. 

### Reproduction Steps

1. Create a new world
2. Travel or use Locate command
3. Confirm that there are no stoneholms nor several other structures in the world
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

BMC v14

### Optifine

No

### Other Mods

No, I tested it in an untouched instance

**Comment by Aureljz** [comment]
This is the bug you're looking for:

https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/184

**Comment by switchnlade** [comment]
Please give this release of RS a try, Telepathic just released it: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3636954

**Comment by SharkieTV** [comment]
Fixed in latest v14.5 https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric/files/3636992
