### ISSUE TITLE
Better Minecraft Server Crashes when loading new chunks

### ISSUE THREAD

**Issue by Arkytorous** [LunaPixelStudios/Better-Minecraft#93]
### Describe the Bug

Everytime I try travel around the world to explore I come across broken chunks that make the whole server crash .I tried deleting the broken chunks using MCA Selector however this problem still occurs. 

### Reproduction Steps

Travelling around the world exploring new chunks, when entering a certain area the server instantly crashes. 

### Crash Report or Log

https://pastebin.com/gc7kznKq

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18

### Optifine

I used Optifine

### Other Mods

No other mods

**Comment by SharkieTV** [comment]
Update the Modpack to latest or remove/update the hedgehog mod
