### ISSUE TITLE
Server crashing after attempted update to newer version

### ISSUE THREAD

**Issue by davids-tips** [LunaPixelStudios/Better-Minecraft#94]
### Describe the Bug

We are trying to update the modpack and it is crashing with this crashlog
[message (2).txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8008178/message.2.txt)
.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10 (amd64) version 10.0

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v16

### Optifine

No

### Other Mods

croptopia
immersive engineering
cucumber
coloed bricks
applied energetics
iron chest
sophisticated backpacks

**Comment by SharkieTV** [comment]
Immersive Eengineering Mod you added is causing the crash, please only report issues without Modifications
