### ISSUE TITLE
【Suggestion】Can you add this 2 mods in Better-Minecraft ?

### ISSUE THREAD

**Issue by blood789** [LunaPixelStudios/Better-Minecraft#95]
Hi, is it possible to add these 2 mods in Better-Minecraft-1.18.1-FORGE version?
End Remastered allows players to spend more time to get to the end.
Savage Ender Dragon makes ender dragon combat more challenging.

[https://www.curseforge.com/minecraft/mc-mods/endremastered](url)
[https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon](url)

Thanks !

**Comment by SharkieTV** [comment]
This is for crashes and bug reports, you can suggest this in the discord
