### ISSUE TITLE
BetterMinecraft 1.18 Fabric 

### ISSUE THREAD

**Issue by Cratios** [LunaPixelStudios/Better-Minecraft#96]
### Describe the Bug

Modpack: BetterMinecraft 1.18 Fabric
Version: 1.14.5

Hi. 

I updated the Pack to 1.14.5 and since that Upate there are spawning Glares (the Green floating Mobs) way to often. If i type the Command to kill Thais mobs ever 30min in a 200 Block Radius i kill everytime about 400 Mobs. 

Also the SeasonMod causes some heavy Laggs when the Season changes  to Spring and the Snow starts to melt. 

Thanks for the answer

Greetings

Cratios

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric

### Optifine

No

**Comment by switchnlade** [comment]
Well, I haven't been able to get the glare to over spawn so not sure what is going on there, but in regards to the snow situation. Please downgrade Snow! Real Magic! to v3.1.2, and then also set snowMeltsInWarmBiomes to false in their snowrealmagic-common.toml file in the config folder. That should stop it from melting so your FPS is saved.

**Comment by Cratios** [comment]
I will give it a try. Thank you! :-)

And the Glares are from Friends an Foe

Greetings

**Comment by switchnlade** [comment]
Alright, head into the config folder once more, find the friendsandfoes.json file, set "enableGlareSpawn": to false. This will disable their spawning.
