### ISSUE TITLE
Chest Preview numbers flickering

### ISSUE THREAD

**Issue by LastRonin17** [LunaPixelStudios/Better-Minecraft#97]
### Describe the Bug

Pretty much what the title says. Is this a bug, or an easy solve?

https://user-images.githubusercontent.com/99148082/152703777-a88e435d-8a13-482a-8a97-3a1484109fd1.mp4

 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

14.5

### Optifine

No

**Comment by SharkieTV** [comment]
Did you add Optifine?

**Comment by switchnlade** [comment]
Please revert Megane to v7.0.2 and WTHIT to v4.4.1. This will fix the flickering issue. It's already been reported to the mod author of Megane so hopefully it's fixed soon.

**Comment by LastRonin17** [comment]
> Please revert Megane to v7.0.2 and WTHIT to v4.4.1. This will fix the flickering issue. It's already been reported to the mod author of Megane so hopefully it's fixed soon.

It worked! Thanks a ton!
