### ISSUE TITLE
World Crash

### ISSUE THREAD

**Issue by Snoop2357** [LunaPixelStudios/Better-Minecraft#98]
### Describe the Bug

After I summoned the night lich (bosses of mass destruction) it was flying around a bit and i finally shot my bow at it and missed then it did some screech and attacked me but as it did that the world crashed. When I tried to open the world I loaded in my inv but the world was blank and I was in for about a second before it saved and showed the crash again. 

### Reproduction Steps

1. summon lich
2. let lich attack you
3. world should crash
...
[crash-2022-02-07_11.09.35-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8016889/crash-2022-02-07_11.09.35-client.txt)

### Screenshots and Videos

[crash-2022-02-07_11.09.35-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8016892/crash-2022-02-07_11.09.35-client.txt)
(Same screenshot in reproduction steps)

### Crash Report or Log

https://crashy.net/wFUSHD3dHac4vKvWhvAQ

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v13 beta

### Optifine

No

### Other Mods

No other mods were installed

**Comment by switchnlade** [comment]
Update bosses of mass destruction or update the modpack, your choice as both will fix it.
